### ISSUE TITLE
Requesting signInActivity does not get mapped when requested for a single user

### ISSUE THREAD

**Issue by mihaiiftode** [microsoftgraph/msgraph-beta-sdk-dotnet#106]
Using the latest beta sdk and beta endpoints does not map the `signInActivity` at all
A request here
`https://graph.microsoft.com/beta/users?$select=id,displayName,givenName,surname,address,accountEnabled,mobilePhone,businessPhones,streetAddress,identities,mail,createdDateTime,signInActivity`

returns it in the correct property and it's mapped to the user object
```
"signInActivity": {
                "lastSignInDateTime": "theDate",
                "lastSignInRequestId": "requestId"
            }
```

A request here `https://graph.microsoft.com/beta/users/{userId}&?select=id,displayName,givenName,surname,address,accountEnabled,mobilePhone,businessPhones,streetAddress,identities,mail,createdDateTime,signInActivity`

will have a response with another property called `value` and the only ability to access it's contents in the `User` graph object from `AdditionalData` Object
```
.
.
    "value": [
        {
            "id": "userId",
            "signInActivity": {
                "lastSignInDateTime": "theDate",
                "lastSignInRequestId": "requestId"
            }
        }
    ],
.
.
```
This is on a B2C tennant
 
[AB#7172](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7172)

**Comment by peombwa** [comment]
This was a service issue in beta, but it has since been fixed. See the discussion in this issue for more details https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/485#issuecomment-790131773.
