### ISSUE TITLE
New problem, unable to read a user's drive item

### ISSUE THREAD

**Issue by buzznut** [microsoftgraph/msgraph-beta-sdk-dotnet#109]
A new test tenant started showing new behavior. An admin delegated OAuth token (Graph Explorer) can no longer get a user's drive. If the admin is set on the user's SharePoint site with the "IsAdmin" property, then the fetch of the drive succeeds. Removal of the "IsAdmin" property then reverts to being unable to read the drive. Graph should have access to the user's drive if the OAuth token has the appropriate permissions consented.

Executing: GET ../beta/users/id/drive 
[AB#7129](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7129)

**Comment by MIchaelMainer** [comment]
To be clear, when you mention admin, are referring to a tenant admin or a SharePoint admin? 

When you mention "admin delegated OAuth token", is that a token received by an admin or a token received by a user because an admin consented for the application to get a token on behalf of the user? 

@ificator

**Comment by buzznut** [comment]
Tenant admin. This used to work with the tenant admin to get the default drive.. We used the sharepointids to find the sharepoint site url.  Now this is not working. Manually adding the tenant admin to the user's site allows the drive to be opened

On May 28, 2020, at 3:32 PM, Michael Mainer <notifications@github.com> wrote:

To be clear, when you mention admin, are referring to a tenant admin or a SharePoint admin?

When you mention "admin delegated OAuth token", is that a token received by an admin or a token received by a user because an admin consented for the application to get a token on behalf of the user?

@ificator

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-635591532">https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-635591532</a>", "url": "<a href="https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-635591532">https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-635591532</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by buzznut** [comment]
Tenant admin - delegated OAuth flow. Just like Graph Explorer. It also breaks in the Explorer.

On May 28, 2020, at 3:32 PM, Michael Mainer <notifications@github.com> wrote:

To be clear, when you mention admin, are referring to a tenant admin or a SharePoint admin?

When you mention "admin delegated OAuth token", is that a token received by an admin or a token received by a user because an admin consented for the application to get a token on behalf of the user?

@ificator

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-635591532">https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-635591532</a>", "url": "<a href="https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-635591532">https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-635591532</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by ificator** [comment]
Tenant admins do not implicitly have access to all content within SharePoint. They do have the ability to grant themselves access by adding themselves to the user's site but that is not the default state of the system.

An "app-only" (aka application permissions) token would allow access without granting access since it does not contain any user identity information, so if you need the ability to read arbitrary drives I'd suggest using [these steps](https://docs.microsoft.com/en-us/graph/auth-v2-service?view=graph-rest-1.0) to get a token.

**Comment by buzznut** [comment]
All I reported was a change in behavior. Admin delegated access with the permissions stated in the Graph documentation, just like Graph Explorer has, used to be able to access an user's Drives. Now it doesn't. If this is on purpose, fine and should be documented. If it is not on purpose then it is a bug and it needs to be fixed.

On June 1, 2020, at 12:23 PM, Brad <notifications@github.com> wrote:

Tenant admins do not implicitly have access to all content within SharePoint. They do have the ability to grant themselves access by adding themselves to the user's site but that is not the default state of the system.

An "app-only" (aka application permissions) token would allow access without granting access since it does not contain any user identity information, so if you need the ability to read arbitrary drives I'd suggest using these steps to get a token.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-636998788">https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-636998788</a>", "url": "<a href="https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-636998788">https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/109#issuecomment-636998788</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by maisarissi** [comment]
As part of the documentation, there is no mention of delegated permission to access a user's drive. There is though for [app-only authentation](https://docs.microsoft.com/en-us/graph/api/drive-get?view=graph-rest-1.0&tabs=http#get-a-users-onedrive).

This is related to how the API works, unfortunately, we in the Microsoft Graph SDK team do not have any ownership of the APIs. For service behavior, you can use the [Microsoft Q&A](https://aka.ms/askgraph) to ask questions or report issues. Also, you can request new features in the [Microsoft 365 Developer Platform](https://aka.ms/requestgraph).
