### ISSUE TITLE
System.NotSupportedException on Teacher Resources 

### ISSUE THREAD

**Issue by cloudb0x** [microsoftgraph/msgraph-beta-sdk-dotnet#113]
> System.NotSupportedException : The collection type 'Microsoft.Graph.IEducationClassTeachersCollectionWithReferencesPage' on 'Microsoft.Graph.EducationClassTeachersCollectionWithReferencesResponse.Value' is not supported.

Calls that have been working for retrieving Teachers seemingly start to fail after updating to the latest preview 0.18.0.0.  
[AB#7130](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7130)

**Comment by maisarissi** [comment]
Hello @cloudb0x .

Please, reopen if this is still an issue.
