### ISSUE TITLE
NextPageRequest on Assignment Resource ServiceException : Query Parameters must not be tampered with

### ISSUE THREAD

**Issue by cloudb0x** [microsoftgraph/msgraph-beta-sdk-dotnet#114]
I'm currently retrieving user assignments and have hit the current page size limit of 500. I have a requirement to retrieve all users assignments which requires me to traverse beyond this result set.

See code below 
```
        public static async Task<IEnumerable<EducationAssignment>> GetAllAsync(this IEducationUserAssignmentsCollectionRequest request, CancellationToken token)
        {
            var educationAssignments = new List<EducationAssignment>();

            var graphAssignments = await request.GetAsync(token);

            educationAssignments.AddRange(graphAssignments.CurrentPage);

            while (graphAssignments.NextPageRequest != null)
            {
                graphAssignments = await graphAssignments.NextPageRequest.GetAsync(token);
                educationAssignments.AddRange(graphAssignments.CurrentPage);
            }

            return educationAssignments.AsEnumerable();
        }
```

When the loop conditional is satisfied and `GetAsync()` is called I receive the following.

```
    Microsoft.Graph.ServiceException : Message: Query options must not be tampered
    Inner error:
    	AdditionalData:
    	request-id: dba2954f-a331-4fcf-a801-ded7a5d47e06
    	date: 2020-06-03T13:05:36
    ClientRequestId: dba2954f-a331-4fcf-a801-ded7a5d47e06
```

I'm unsure what I'm doing wrong here or if this is expected behaviour. I'm on 0.12.0. 

If I upgrade to latest I receive the same issue as #113 just with the assignment resource. 
[AB#7131](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7131)

**Comment by MIchaelMainer** [comment]
@garethj-msft Have there been changes to the paging mechanism for educationAssignments? Related to #113

**Comment by cloudb0x** [comment]
When attempting to use the class to get the assignments and the same code I get the following 

```
 Microsoft.Graph.ServiceException : Code: 19999
    Message: Something failed, the API cannot share any more information at the time of the request.
    Inner error:
    	AdditionalData:
    	date: 2020-06-23T10:32:04
    	request-id: c519bddf-28c9-41e7-ab77-bd95cf0b7008
    ClientRequestId: c519bddf-28c9-41e7-ab77-bd95cf0b7008
```

Not sure if this helps?

**Comment by cloudb0x** [comment]
`https://graph.microsoft.com/beta/education/classes/dc962d8a-bd4e-4129-a626-0e3e9d129756/assignments?$skip=500`

The next link that is generated adding the skip causes aforementioned error.

**Comment by cloudb0x** [comment]
`https://graph.microsoft.com/beta/education/me/assignments?$skiptoken=eyJGaWx0ZXIiOiJkdWVEYXRlVGltZSBsZSAyMDIwLTA0LTI0VDExOjI4OjUxLjg3NDk2MjZaIiwiT3JkZXJCeSI6ImR1ZURhdGVUaW1lIGRlc2MiLCJUb3AiOjUwMCwiTGFzdEVudGl0eUlkIjoiN2E1ZTM4NmEtZjg3NS00ZTFjLTgxYTQtYTVhZDhiMmE0MGJjIiwiTWF0Y2hpbmdMYXN0RWxlbWVudEZpbHRlckNvdW50IjoxfQ%3d%3d`

Using the skip token Yields in `Message: Query options must not be tampered`

**Comment by cloudb0x** [comment]
@mmast-msft, based on our comms from Firefly this is our primary issue. Copying you in here for any possible assistance as it seems graph related.

**Comment by maisarissi** [comment]
Hello @cloudb0x .

Please, reopen if this is still an issue.
