### ISSUE TITLE
mailFolder/userConfigurations seems to always be missing

### ISSUE THREAD

**Issue by ghelyar** [microsoftgraph/msgraph-beta-sdk-dotnet#115]
When I make a request such as `GET https://graph.microsoft.com/beta/me/mailFolders/root?$select=userConfigurations` then there is no error, but nothing is returned for that property.

In the beta SDK, `MailFolder.UserConfigurations` is always null, and `UserConfiguration` also only seems to have `BinaryData`, not the dictionary.

I'm specifically trying to find the `OWA.UserOptions` user configuration which should be on the root folder and have dictionary data.

Is this actually possible, or is this currently only to store and later retrieve custom binary user configurations, and not to read the built in user configurations?

**Comment by ddyett** [comment]
i'm not sure what specific data you are looking for but maybe you're looking for the mailbox settings  https://docs.microsoft.com/en-US/graph/api/user-get-mailboxsettings?view=graph-rest-beta&tabs=http

**Comment by ghelyar** [comment]
Thanks, but that's not what I'm looking for.

As both of these APIs are available in powershell and EWS, I'll use the powershell documentation as a reference.

Graph's MailboxSettings corresponds to https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxautoreplyconfiguration?view=exchange-ps

While I'm looking for https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxmessageconfiguration?view=exchange-ps

In EWS, you get the UserConfiguration `OWA.UserOptions` on the `root` folder, which has a dictionary on it, which has the values that I'm interested in.

Graph has a beta API for reading UserConfigurations from the root folder, but it's always missing from the response, so I can't work out if I'm doing something wrong or its just not implemented.

**Comment by MIchaelMainer** [comment]
The binary data is the only option available now. There is Microsoft Graph User Voice for opening feature requests. https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests

Please open a feature request on exposing additional UserConfiguration data types.

**Comment by ghelyar** [comment]
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/40749445-expose-additional-userconfiguration-types
