### ISSUE TITLE
Does the beta endpoint support listing users assigned to an application?

### ISSUE THREAD

**Issue by twentytwokhz** [microsoftgraph/msgraph-beta-sdk-dotnet#116]
My use case is the following:

1. assign users to an application via appRoleAssignedTo endpoint
2. list users from an app (based on point 1)

How can I go about solving this?
The users endpoint does not seem to support filtering and searching based on appRoleAssignment.
Please help, since otherwise I would need to go through a lot of hoops.

**Comment by MIchaelMainer** [comment]
Please post this question on StackOverflow, tag it with [microsoft-graph], and then provide a link to the SO post in this issue. Please provide links to the documentation you've used in your StackOverflow post.

**Comment by twentytwokhz** [comment]
Ok
