### ISSUE TITLE
Property privacyAccessControls is missing from Microsoft.Graph.MacOSGeneralDeviceConfiguration model.

### ISSUE THREAD

**Issue by Yomodo** [microsoftgraph/msgraph-beta-sdk-dotnet#117]
The [changelog](https://docs.microsoft.com/en-us/graph/changelog) of May 2020 states:

Addition | beta |
Added the `privacyAccessControls `property to the `macOSGeneralDeviceConfiguration `entity

This does not seem to be the case.

Currently using NuGet package: Microsoft.Graph.Beta 0.18.0-preview

**Comment by zengin** [comment]
This is coming soon in the Microsoft.Graph.Beta 0.19.0-preview package.

**Comment by Yomodo** [comment]
Unfortunately the 0.19.0-preview does not provide this property.

**Comment by zengin** [comment]
This property is available in 0.19.0-preview. I verified with auto complete by installing the NuGet package. Here is [the version of the file in that package](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Models/Generated/MacOSGeneralDeviceConfiguration.cs) (see last property).

**Comment by Yomodo** [comment]
Indeed. my bad.

**Comment by zengin** [comment]
No worries, thanks for confirming that it now works for you.
