### ISSUE TITLE
DeviceCompliancePolicy "All Users" group assignment needs TermsAndConditions build request URL instead of DeviceCompliancePolicies build request URL.

### ISSUE THREAD

**Issue by Yomodo** [microsoftgraph/msgraph-beta-sdk-dotnet#118]
Using a POST and this JSON, I'd like to create a group assignment to the "All Users" group in Azure:
```
{
    {
        "targetGroupId":"acacacac-9df4-4c7d-9d50-4ef0226f57a9",
        "target":
        {
            "@odata.type":"AllLicensedUsersAssignmentTarget"
        }
    }
}
```

The `requestUrl` I use for this is: `https://graph.microsoft.com/beta/deviceManagement/deviceCompliancePolicies/GUID/Assignments` which unfortunately returns a BadRequest (status 400).

However, when I use: `https://graph.microsoft.com/beta/deviceManagement/termsAndConditions/GUID/Assignments`, all is well!

 
[AB#7132](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7132)

**Comment by MIchaelMainer** [comment]
Are you using the SDK? If not, can you post your question to StackOverflow and provide a link to it in this issue?

**Comment by Yomodo** [comment]
Yes, I'm currently and experiencing this using NuGet package: Microsoft.Graph.Beta 0.18.0-preview

**Comment by MIchaelMainer** [comment]
Can you show us how are you using Microsoft.Graph.Beta to make the call that results in the request body you are showing in your original post? It doesn't match what I see in the documentation.

https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-devicecompliancepolicyassignment-create?view=graph-rest-1.0

**Comment by Yomodo** [comment]
The supplied indeed does not help and is very confusing.

Using the url and json, I call my method:
```
public async ValueTask<HttpResponseMessage> CreateAssignmentsAsync(string requestUrl, string jsonAssignment)
{
 var content = new StringContent(jsonAssignment, Encoding.UTF8, JsonMediaTypeFormatter.DefaultMediaType.MediaType);

 using var request = new HttpRequestMessage(System.Net.Http.HttpMethod.Post, requestUrl) {Content = content};

 return await ExecuteQueryAsync(request);
}


private async ValueTask<HttpResponseMessage> ExecuteQueryAsync(HttpRequestMessage request)
{
 using var task = AuthenticateRequestAsync(request); // Adds the bearer token
 await task;

 var client = _httpFactory.CreateClient();

 client.BaseAddress = new Uri(GraphServiceClient.BaseUrl + "/");

 using var query = client.SendAsync(request);
 return await query;
}
```

**Comment by MIchaelMainer** [comment]
Got it. The beta definition is here:
https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-devicecompliancepolicyassignment-create?view=graph-rest-beta

Your request body contains an extra json object, and an unknown property called targetGroupId.

**Comment by Yomodo** [comment]
I've tried every possible combination of json fragments to no prevail.

I you can find the time, I would very much appreciate a working JSON sample.

**Comment by ddyett** [comment]
closing older stale issue.  Try on a V5 or greater and open a new issue if it occurs again.
