### ISSUE TITLE
Missing properties from Microsoft.Graph.AndroidManagedAppProtection model

### ISSUE THREAD

**Issue by Yomodo** [microsoftgraph/msgraph-beta-sdk-dotnet#123]
Using Microsoft.Graph.Beta 0.19.0-preview package, 3 properties are missing
from the `Microsoft.Graph.AndroidManagedAppProtection` model:

```
dialerRestrictionLevel
customDialerAppPackageId
customDialerAppDisplayName
```

When deserializing, these properties are listed in the model's `AdditionalData` property.

**Comment by zengin** [comment]
will be available in next release.
related #127
