### ISSUE TITLE
Missing properties from Microsoft.Graph.IosManagedAppProtection model

### ISSUE THREAD

**Issue by Yomodo** [microsoftgraph/msgraph-beta-sdk-dotnet#124]
Using Microsoft.Graph.Beta 0.19.0-preview package, 2 properties are missing
from the `Microsoft.Graph.IosManagedAppProtection` model:

```
dialerRestrictionLevel
customDialerAppProtocol
```

When deserializing, these properties are listed in the model's `AdditionalData `property.

**Comment by zengin** [comment]
will be available in next release.
related #127
