### ISSUE TITLE
Missing property from Microsoft.Graph.Windows10CompliancePolicy model 

### ISSUE THREAD

**Issue by Yomodo** [microsoftgraph/msgraph-beta-sdk-dotnet#125]
Using Microsoft.Graph.Beta 0.19.0-preview package, 1 property is missing
from the `Microsoft.Graph.Windows10CompliancePolicy` model:

```
deviceCompliancePolicyScript
```

When deserializing, this property is listed in the model's `AdditionalData` property.

**Comment by ddyett** [comment]
generator issue?

<Property Name="deviceCompliancePolicyScript" Type="graph.deviceCompliancePolicyScript"/>

<ComplexType Name="deviceCompliancePolicyScript">
<Property Name="deviceComplianceScriptId" Type="Edm.String"/>
<Property Name="rulesContent" Type="Edm.Binary"/>
</ComplexType>

**Comment by zengin** [comment]
will be available in next release.
related #127
