### ISSUE TITLE
filesFolder on Standard channels

### ISSUE THREAD

**Issue by buzznut** [microsoftgraph/msgraph-beta-sdk-dotnet#126]
Need to have this property for Standard channels so renamed channels can be correctly linked to their underlying Graph DriveItem folder.

This works for Private channels.

**Comment by MIchaelMainer** [comment]
This sounds like a feature request. Please post your question to [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests).

**Comment by buzznut** [comment]
It is really a bug. Channels have the filesFolder property. Currently only Private Channels have this property instantiated. Standard Channels do not. Normally a standard channel’s file space is a folder on the drive and can be correlated to the channel by channel name. If though you change the channel name via the Teams UI, it only changes the channel name but not the underlying folder name on the drive. Internally Teams seems to work but with Graph when matching channel to drive/folder there can exist the issue of not being able to match by name. If both types of channels had the filesFolder property instantiated, then there is no ambiguity.
