### ISSUE TITLE
Call to RevokeSignInSessions() throws JsonReaderException

### ISSUE THREAD

**Issue by twentytwokhz** [microsoftgraph/msgraph-beta-sdk-dotnet#128]
When calling the RevokeSignInSessions method as described in the docs, on a specific user as below:
`await graphServiceClient.Users[id].RevokeSignInSessions().Request().PostAsync();`
a JsonReaderException is thrown, which is unexpected.

Exception: NewtonSoft.Json
Message: Unexpected character encountered while parsing value: {. Path '', line 1, position 1.

version: 0.19.0-preview

**Comment by MIchaelMainer** [comment]
Duplicate of https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/249.
