### ISSUE TITLE
Adding EnrollmentConfigurationAssignment throws error: "No OData route exists that match template"

### ISSUE THREAD

**Issue by Yomodo** [microsoftgraph/msgraph-beta-sdk-dotnet#130]
Using Microsoft.Graph.Beta 0.19.0-preview
I am creating an `EnrollmentConfigurationAssignment`:

```
var builder = MSGraph.GraphServiceClient.DeviceManagement.DeviceEnrollmentConfigurations[entity.Id];

var assignment = new Microsoft.Graph.EnrollmentConfigurationAssignment
{
    Target = new Microsoft.Graph.GroupAssignmentTarget{GroupId = group.Id}
};

await builder.Assignments.Request().AddAsync(assignment);
```

This throws the following error:

_No method match route template\r\nMessage: No OData route exists that match template ~/singleton/navigation/key/navigation with http verb POST for request /StatelessOnboardingService/deviceManagement/deviceEnrollmentConfigurations('60b63e69-bce5-4760-98fb-79d9338a46ff_Windows10EnrollmentCompletionPageConfiguration')/assignments.\r\nInner error:\r\n\tAdditionalData:\r\n\tdate: 2020-07-13T14:21:00\r\n\trequest-id: 4c8fed86-34c4-4ecb-beb8-13c58589ee61\r\nClientRequestId: 4c8fed86-34c4-4ecb-beb8-13c58589ee61\r\n"_
 
[AB#7142](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7142)

**Comment by Yomodo** [comment]
When I replace: `await builder.Assignments.Request().AddAsync(newAssignment);`

with: `await builder.Assign(new[] {assignment}).Request().PostAsync();`

it also works!

**Comment by ddyett** [comment]
@PetRich-MSFT

**Comment by ddyett** [comment]
Closing older stale issue.
