### ISSUE TITLE
Can the PublisherName length be increased (> 100) ?

### ISSUE THREAD

**Issue by Yomodo** [microsoftgraph/msgraph-beta-sdk-dotnet#131]
Using Microsoft.Graph.Beta 0.19.0-preview to create a _Windows 10 app protection policy_ 
I receive the following error:

`Message: The request is invalid.\r\nInner error:\r\n\tMessage: policy.ProtectedApps[7].PublisherName : Length should be less than 100`

Which is true, the total length is  131 characters.
Creating the policy manually in the portal does not raise any errors and the input is accepted.

**Comment by MIchaelMainer** [comment]
Can you please post your feature request to [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests)?
