### ISSUE TITLE
Setting of sensitivity labels is not  available with app credentials

### ISSUE THREAD

**Issue by jofleck** [microsoftgraph/msgraph-beta-sdk-dotnet#132]
Hey, 

we noticed that it's not possible to set sensitivity labels to a group while using app credentials. The request fails
 with the error "App-only token is not supported" 

Are there any plans to support this in the future?

**Comment by MIchaelMainer** [comment]
Please post your question to https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests.

**Comment by PieterHeemeryck** [comment]
I'm having the same issue / request.

Opened a feature request on UserVoice: https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/42614317-support-app-permissions-to-set-sensitivity-label-o

**Comment by JeraldLOakley** [comment]
So what happens to these discussions now that uservoice is gone? Does anyone have a workaround for something like this?

**Comment by MIchaelMainer** [comment]
@JeraldLOakley  The new place for this is https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
