### ISSUE TITLE
Enable Sourcelink on Package

### ISSUE THREAD

**Issue by michael-hawker** [microsoftgraph/msgraph-beta-sdk-dotnet#133]
![image](https://user-images.githubusercontent.com/24302614/88344059-a9718900-ccf7-11ea-9393-602855bac802.png)

Package is missing sourcelink/symbols, would be great to be able to more easily debug issues this way.

[AB#5590](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5590)

**Comment by MIchaelMainer** [comment]
https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/

**Comment by zengin** [comment]
Related: https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/51
