### ISSUE TITLE
Question: is convert file with SDK possible?

### ISSUE THREAD

**Issue by sven5** [microsoftgraph/msgraph-beta-sdk-dotnet#135]
Is it currently possible to get a file in another format using this SDK?
[This link](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-beta&tabs=http) describes the graph API usage but I couldn't find it in the SDK.

Any help is greatly appreciated.

Thanks

**Comment by ddyett** [comment]
are you saying this did not work for you?

GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var queryOptions = new List<QueryOption>()
{
	new QueryOption("format", "{format}")
};

var stream = await graphClient.Drive.Items["{item-id}"].Content
	.Request( queryOptions )
	.GetAsync();

**Comment by sven5** [comment]
Hi @ddyett ,
thanks, this should work.
I didn't find that.
