### ISSUE TITLE
Search API: search with beta endpoint not working

### ISSUE THREAD

**Issue by sven5** [microsoftgraph/msgraph-beta-sdk-dotnet#136]
Hi,

the following code:
`_graphClient.Users[_userEmailAddress].Drive.Root.ItemWithPath(_defaultFolder).Search(term).Request().GetAsync(ct);`

translates to API call:
`https://graph.microsoft.com:443/beta/users/xxx@yourtenant.onmicrosoft.com/drive/root:/someFolder:/microsoft.graph.search(q='searchTerm')`

and returns error:
```
BadRequest
Message: The type 'microsoft.graph.search' specified in the URI is neither a base type nor a sub-type of the previously-specified type 'microsoft.graph.driveItem'.
```

However, when using v1.0 endpoint with the current SDK v0.20 there is no error but the result is empty. Instead, when using graph explorer there are results.

**Comment by nmoreau** [comment]
This issue has been resolved. Please upgrade to the latest version of the SDK.
