### ISSUE TITLE
How to set zoom level in file preview 

### ISSUE THREAD

**Issue by sven5** [microsoftgraph/msgraph-beta-sdk-dotnet#138]
Hi graph team,

I'd like to get an embeddable link with the zoom level "full-page width".

`_graphClient.Users[_userEmailAddress].Drive.Items[id].Preview(zoom: 1).Request().PostAsync();`

How would it be possible with the SDK?
Thanks
 
[AB#7135](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7135)

**Comment by MIchaelMainer** [comment]
Can you share with us what you have tried and any error information you received? Please provide a sanitized http capture of your request and response.

**Comment by sven5** [comment]
Hi @MIchaelMainer 

Currently, I haven't tried so much. I only realized that the SDK's method [`Preview()`](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/01fbb691aa26ee4d4477983dacf64a02da1afe9c/src/Microsoft.Graph/Requests/Generated/DriveItemRequestBuilder.cs#L301) allows only a `double` value for the `zoom` parameter. I assume this could be any value between 0.1 and 1.

When using the embeddable preview link, we see some zoom levels inside the preview controls pane:
![image](https://user-images.githubusercontent.com/8734624/89618169-e444f680-d88b-11ea-8df6-884052c3d674.png)


However now I wonder how to set the value "window size" and "window width" with the SDK?

**Comment by ddyett** [comment]
Closing older issue.

**Comment by Herz3h** [comment]
Is there an answer about what value to pass for "window width" ??

**Comment by sven5** [comment]
Unfortunately, not. This is still not clear.

**Comment by Herz3h** [comment]
Ok I have found the solution. In the get url there is an `embed` query parameter with the zoom value you have set (check first image)

I just replaced 1.5 zoom, by `"width"` and it automatically sets to Window Width


<img width="543" alt="image" src="https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/1900696/fa682848-f340-424d-9b4f-2a952a7a8c03">
 

<img width="560" alt="image" src="https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/1900696/51333bac-3d4f-42e9-8130-18bfe543ed05">
