### ISSUE TITLE
Getting error “AuthenticationError” when accessing user photo using Graph API

### ISSUE THREAD

**Issue by onyxcool** [microsoftgraph/msgraph-beta-sdk-dotnet#141]
Hi,

would you be kind to provide a solution.

We have an application that uses the MS Graph API to access users information along with getting user photo. Application has been working fine until 2 months ago. Now we're seeing an error "Error authenticating with resource" when accessing photo

Tried getting photo via MS Graph explorer using https://graph.microsoft.com/beta/me/photo/$value. All delegated permissions have been granted. Got an error:

```
{
    "error": {
        "code": "AuthenticationError",
        "message": "Error authenticating with resource",
        "innerError": {
            "date": "2020-08-10T20:10:18",
            "request-id": "cf458687-6aa9-49a6-a346-964daafefcc2"
        }
    }
}
```
The same result was using Postman with access_token. Accesss token contains all needed permissions: https://www.screencast.com/t/BNeKELVaYEt

```
{
  "error": {
    "code": "AuthenticationError",
    "message": "Error authenticating with resource",
    "innerError": {
      "date": "2020-08-10T20:22:49",
      "request-id": "704bd253-0953-48e1-857e-ec51f7651ed5"
    }
  }
}
```
Getting user profile works fine in both places.

Could you help me to figure out whether I am doing something wrong, or something does not work properly.

Thank you in advance! 
[AB#7138](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7138)

**Comment by MIchaelMainer** [comment]
Can you verify that your token in Graph Explorer has user.read or other permissions that enable photo access? Can you access other APIs?

**Comment by MIchaelMainer** [comment]
@svpsiva Do you have info photo API not working?

**Comment by MIchaelMainer** [comment]
Is it possible that this is an on-premise Exchange mailbox? Hybrid scenarios where the user's mailbox is on premise is not supported for this API.

**Comment by onyxcool** [comment]
Hi Michael,

thank you for the help.
As for the your question: _Can you access other APIs?_
Yes, I can get user and group information, etc. Only user photo cannot be retrieved.

_Is it possible that this is an on-premise Exchange mailbox? Hybrid scenarios where the user's mailbox is on premise is not supported for this API._
It used to work with my on-premise Exchange couple month ago on "beta" API. Maybe something is changed from that time?

Would you be kind to share an official list of all the needed requirements to be able to get user photo from Microsoft Graph?

Thank you

**Comment by maisarissi** [comment]
Hi @onyxcool .

As pointed out by @MIchaelMainer , unfortunately, we in the Microsoft Graph SDK team do not have any ownership of the APIs that are causing you issues. If this is still an issue, you can report it in the Microsoft Q&A forum, and it will get routed to the appropriate team for them to triage.
https://aka.ms/askgraph

I'm closing this as non-actionable. Thank you!
