### ISSUE TITLE
ToDo API

### ISSUE THREAD

**Issue by Manav-Seth** [microsoftgraph/msgraph-beta-sdk-dotnet#146]
The docs say that ToDo API is available now (as per here: https://docs.microsoft.com/en-us/graph/api/resources/todo-overview?view=graph-rest-beta) but I don't see it in code or in the latest nuget - 0.23.0-preview).  Am I missing something? 
[AB#7137](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7137)

**Comment by MIchaelMainer** [comment]
We are both missing something. It appears that we are missing metadata that we use to generate the client APIs. We are investigating this now.

**Comment by azarc3** [comment]
What is the status of this? I absolutely need this support for an application I'm writing.

**Comment by andrueastman** [comment]
@Manav-Seth @azarc3 
I believe the latest release should now have the the various models and request builders for the ToDo API.
You can find examples [here](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/model/Todo.cs), [here](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/model/TodoTask.cs) and [here](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/model/TodoTaskList.cs)

I am going to close this issue for now. However, feel free to raise an issue if something is amiss.
