### ISSUE TITLE
System.NotSupportedException on BookingBusinesses Resources

### ISSUE THREAD

**Issue by rafaguglielmello** [microsoftgraph/msgraph-beta-sdk-dotnet#156]
Calls that have been working for retrieving **BookingBusinesses** seemingly start to fail after updating to the latest preview **0.27.0.0**. If the request is made via MS Graph Explorer, it returns the data correctly.

**Error Message:**

    The collection type 'Microsoft.Graph.IGraphServiceBookingBusinessesCollectionPage' on 'Microsoft.Graph.GraphServiceBookingBusinessesCollectionResponse.Value' is not supported.

**External Error (by Visual Studio)**:

    BookingsService.Controllers.BookingsController.Get() in BookingsController.cs

**Comment by MIchaelMainer** [comment]
Are you using the preview version of Microsoft.Graph.Core, 2.x?
