### ISSUE TITLE
BookingBusinesses returns only the first 500 records

### ISSUE THREAD

**Issue by rafaguglielmello** [microsoftgraph/msgraph-beta-sdk-dotnet#157]
I identified in tests using **BookingBusinesses** that when using the call below only the first 500 BookingBusinesses records that I have registered are returned. In this scenario there is no pagination (absence of **skip**/**top** as well as **@odata.nextLink**).

    https://graph.microsoft.com/beta/BookingBusinesses

In tests, I currently have approximately 2000 BookingBusinesses created but only the first 500 are listed. 
[AB#7141](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7141)

**Comment by ddyett** [comment]
closing older issue but if still an issue try https://developer.microsoft.com/en-us/graph/support
