### ISSUE TITLE
API to steps in TodoTask

### ISSUE THREAD

**Issue by Oryan-Hassidim** [microsoftgraph/msgraph-beta-sdk-dotnet#180]
Hi.
Do you can to open API to get and update steps in a TodoTask?

![image](https://user-images.githubusercontent.com/44084713/96162231-f6dd4b00-0f20-11eb-9084-21a0cc557be8.png)

Thanks🙃

**Comment by MIchaelMainer** [comment]
This looks like a question about the Todo API. I suggest that you post to StackOverflow and tag it with microsoft-graph and todo. You can post a link to your question in this issue.
