### ISSUE TITLE
Chats.AllMessages() gone

### ISSUE THREAD

**Issue by Arik1337** [microsoftgraph/msgraph-beta-sdk-dotnet#184]
Users[{id}].Chats.AllMessages() is gone on 0.30.0-preview when using 0.29 it's there.. Was it moved?

**Comment by zengin** [comment]
Yes. AllMessages() from user chats is removed in 0.30.0-preview.

Please note that our Beta package does not guarantee backwards compatibility, so types can be removed as the package evolves.

@MIchaelMainer, according to the metadata, allMessages function is defined on `Collection(microsoft.graph.chat)`, so it works on the top level EntitySet `chats`, e.g. `client.Chats.AllMessages()`. Does the broad function definition on "any" collection of chats imply that it should work on all collections of chats (like chats of a specific user) or is our current interpretation, i.e. limiting to the top level EntitySet, correct?

**Comment by MIchaelMainer** [comment]
It looks like the containsTarget was removed and then added back with the recent metadata update. The next release should add this functionality back.

@zengin I don't know if OData spec allows bound functions to reference entities (navigation with containsTarget = false which is the default if not specified). 

I'll need https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/185 reviewed so we can get 0.31.0-preview out with this fix.

**Comment by MIchaelMainer** [comment]
@Arik1337 you should now see this fixed in https://www.nuget.org/packages/Microsoft.Graph.Beta. Let us know otherwise and reopen this issue.
