### ISSUE TITLE
Some hand crafted files are not in sync with msgraph-sdk-dotnet repo

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-beta-sdk-dotnet#187]
Following types/methods are missing in the beta repo because they are implemented in the `msgraph-sdk-dotnet` repo. We should ideally move them to `msgraph-sdk-dotnet-core` repo to keep the functionalities in sync.
```
Enums:
  ClientType
  PagingState
Classes:
  PageIterator
  ReadOnlySubStream
Methods:
  ChunkedUploadProvider::GetChunkRequestResponseAsync
Properties:
  TeamsTab::ODataBind
``` 
[AB#6465](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6465)

**Comment by ddyett** [comment]
no longer valid with move to kiota.
