### ISSUE TITLE
MS Graph & Teams meeting

### ISSUE THREAD

**Issue by RayMa78** [microsoftgraph/msgraph-beta-sdk-dotnet#192]
Hello As i saw in doc 
https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=csharp

We can use this GET method to get a meeting object from Join Url Address !
```HTML
GET https://graph.microsoft.com/beta/me/onlineMeetings?$filter=JoinWebUrl%20eq%20'https%3A%2F%2Fteams.microsoft.com%2Fl%2Fmeetup-join%2F19%253ameeting_MGQ4MDQyNTEtNTQ2NS00YjQxLTlkM2EtZWVkODYxODYzMmY2%2540thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%2522909c6581-5130-43e9-88f3-fcb3582cde37%2522%252c%2522Oid%2522%253a%2522dc17674c-81d9-4adb-bfb2-8f6a442e4622%2522%257d
```
But when i try that i get error like

> "The query specified in the URI is not valid. Could not find a property named 'JoinWebUrl' on type 'Default.<>f__AnonymousType0_1Of<>f__AnonymousType1_2OfString_String 
[AB#7147](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7147)

**Comment by MIchaelMainer** [comment]
Can you try adding the end quote to the JoinMeetinUrl and let us know the result? If you still get an error, please provide the request-id and timestamp as well as the code you used to produce the request.

**Comment by RayMa78** [comment]
Thanks for your response auctully its worked but i faced another problem when i want to fetch with user id it gives the same error 
this is what code i use 
```
string body = string.Format("JoinWebUrl eq '{0}'", joinWeb);
var meetingTest = await graphServiceClient.Users[userId].OnlineMeetings
                .Request()
                .Filter(body)
                .GetAsync();
```
am i doing this wrong too ?

**Comment by RayMa78** [comment]
<a href="https://ibb.co/0Y2MQdm"><img src="https://i.ibb.co/YfQkbqP/Screenshot-482.png" alt="Screenshot-482" border="0"></a>

**Comment by RayMa78** [comment]
Any help ?

**Comment by MIchaelMainer** [comment]
Using Fiddler, can you capture the traffic using Graph Explorer and the SDK and compare the differences? Can you share them here?

**Comment by RayMa78** [comment]
@MIchaelMainer 
Ye finely tnx for your response ye i already did it they are already same i just find out that the graph explorer gives same error with the sdk when ever the link of meeting is unavailable like its no more exists it gives same error as JoinWebUrl not found but when u fix link its fixing but in sdk its not happening 

This is how i used the link and body is there anything wrong ? 

```
var joinWeb = "https://teams.microsoft.com/l/meetup-join/19%3a8d3fba204b91422caef3e783cef8bb7f%40thread.tacv2/1605852484793?context=%7b%22Tid%22%3a%22bc49579f-4ac2-4865-bc16-60f9d5f29188%22%2c%22Oid%22%3a%220621f040-6869-4677-86b0-f570703b6d32%22%7d";
            string body = string.Format("JoinWebUrl%20eq%20'{0}'", joinWeb);

graphServiceClient.BaseUrl = "https://graph.microsoft.com/beta";
            var meetingTeste = graphServiceClient.Users[userId].OnlineMeetings
                .Request()
                .Filter(body);
            var meetingTest = await meetingTeste.GetAsync();
            return meetingTest;

``

Im changing url manualy to valid one each time just for testing the API

> Using Fiddler, can you capture the traffic using Graph Explorer and the SDK and compare the differences? Can you share them here?

**Comment by RayMa78** [comment]
I even copy-paste the URL got from Fidder to graph explorer web it's working! maybe the web doing something that SDK not doing on the string ? or on the URL?

**Comment by MIchaelMainer** [comment]
How did you get that working in Graph Explorer? The API is application permissions only ([per documentation](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=csharp)). Graph Explorer doesn't even give you the option to consent to a scope for that URL. Oh, looks like the documentation is wrong. Still, I don't see the option in Modify Permissions.

The error that where it states it can't find joinweburl looks like an internal error and doesn't come from this client library. One thing I might try is to set `joinweburl` as lowercase just in case. 

I'm unable to get that reproduced.

**Comment by RayMa78** [comment]
ok so I thought I'm doing something wrong ill try a workout with it and if I found a fix for that ill let you know thanks for your support @MIchaelMainer

**Comment by RayMa78** [comment]
@MIchaelMainer 
about how I get working with graph explorer i made a .net teams bot that works with getting Auth key and sending a request to graph API which I provided permissions to my application that's why I can access that

**Comment by ddyett** [comment]
closing older stale issues. please try on version 5 or greater and file a new issue if encountered.
