### ISSUE TITLE
Assign User to Application (AppRoleAssignment)

### ISSUE THREAD

**Issue by miyavidechu** [microsoftgraph/msgraph-beta-sdk-dotnet#2]
Continuing on my issue; https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/406

    public async Task AddUserToApplication(string appId, string roleId, User user)
    {
        try
        {
            var req = _graphClient.Users[user.Id].Request();

            var appRole = new AppRoleAssignment()
            {
                ResourceId = Guid.Parse(appId),
                PrincipalId = Guid.Parse(user.Id),
                AppRoleId = Guid.Parse(roleId)
            };

            user.AppRoleAssignments = new UserAppRoleAssignmentsCollectionWithReferencesPage();
            user.AppRoleAssignments.Add(appRole);

            await req.UpdateAsync(user);
        } catch (Exception e)
        {
            _log.Log(LogLevel.Error, "Error when adding user to application; " + e.Message);
        }
    }

I have assigned a UserAppRoleAssignmentsCollectionWithReferencesPage to AppRoleAssignments, but now I run into a new error, this time on UpdateAsync;

    Inner error

    Microsoft.Graph.ServiceException: Code: Request_BadRequest
    Message: A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.

As I've earlier seen people solve other updating errors by creating a new user with the updated values, like so;

    var u = new User
    {
        AppRoleAssignments = new UserAppRoleAssignmentsCollectionWithReferencesPage()
    };

    u.AppRoleAssignments.Add(appRole);

    await req.UpdateAsync(u);

But that just gives me a new error;

    Inner error

    Microsoft.Graph.ServiceException: Code: Request_BadRequest
    Message: One or more property values specified are invalid.

It looks like I'm either missing a value and/or I have an invalid one and I'm guessing it's either on the appRoleAssignment or the user.AppRoleAssignments.

**Comment by MIchaelMainer** [comment]
I'm not familiar with user.appRoleAssignments. I suggest that you open Fiddler, capture the request and response, and post the sanitized req/response here as well as the link to the documentation that describes the expected behavior.

**Comment by hajekj** [comment]
I suppose you should be using this endpoint https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-beta to update role assignments, but it is missing from the SDK - https://github.com/microsoftgraph/microsoft-graph-docs/issues/4266

**Comment by MIchaelMainer** [comment]
> A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/383

**Comment by hajekj** [comment]
Would this be the correct SDK call? I don't understand why it is going through References though.

```csharp
await microsoftGraph.ServicePrincipals[servicePrincipal.Id].AppRoleAssignments.References.Request().AddAsync(assignment)
```

**Comment by MIchaelMainer** [comment]
No, that isn't the correct call. I'll respond in a bit more with more info.

**Comment by MIchaelMainer** [comment]
@hajekj That is the correct call if we are adding a reference. I'm under the impression that this service API is not fully baked. There is nothing I can do on the client until we have clarification on the state and function of the service API.

**Comment by darrelmiller** [comment]
@hajekj  Could you please report this issue on StackOverflow with the microsoft-graph tag?  Thank you.

**Comment by hajekj** [comment]
Done - https://stackoverflow.com/questions/56786453/how-to-create-an-approleassignment-via-microsoft-graph

**Comment by Zaid-Safadi** [comment]
This finally worked for me but it uses the Beta REST API:
```cs
        const string ROLE_ASSIGNMENT_FORMATTER = "https://graph.microsoft.com/beta/servicePrincipals/{0}/appRoleAssignments";
        
        public static async Task AddApplicationUsers(string enterpriseAppId, string userId, string roleId)
        {
            HttpClient client = new HttpClient();
            string url = string.Format(ROLE_ASSIGNMENT_FORMATTER, enterpriseAppId);

            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await GetAccessToken());

            var roleAssignment = new
            {
                appRoleId = roleId,
                principalId = userId,
                resourceId = enterpriseAppId
            };


            var content = new StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(roleAssignment), Encoding.UTF8, "application/json");
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            var response  = await client.PostAsync(url, content);

            if (response.IsSuccessStatusCode)
            {
                return ;
            }
            else
            {
                throw new HttpRequestException(response.ReasonPhrase);
            }
        }
```
