### ISSUE TITLE
Error: Parameter 'DeltaToken' not supported for this request.

### ISSUE THREAD

**Issue by dviry** [microsoftgraph/msgraph-beta-sdk-dotnet#203]
Using Microsoft.Graph.Beta@0.35.0-preview

Following code:

```c#
var deltaCollection = await graphClient
                    .Teams[teamId]
                    .Channels[channelId]
                    .Messages
                    .Delta()
                    .Request()
                    .GetAsync(cancellationToken);

bool morePagesAvailable = false;
                do
                {
                    // get all chatMessages in this page
                    allMessages.AddRange(deltaCollection.CurrentPage.ToList());
                    // any more pages?
                    morePagesAvailable = deltaCollection.NextPageRequest != null;
                    if (morePagesAvailable)
                    {
                        deltaCollection = await deltaCollection.NextPageRequest.GetAsync(cancellationToken);
                    }
                }
                while (morePagesAvailable);
```

The first page of results is retrieved fine, but on the call to .NextPageRequest.GetAsync() I always receive the following error:

```
Parameter 'DeltaToken' not supported for this request.
```

Manually trying this in GraphApi Explorer (following [the documentation](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&tabs=csharp#initial-request)) works fine - I cannot figure out why the SDK is throwing this (and I do not want to resort to direct HTTP calls) - what am I missing?

Here the full error with request-ids - maybe these can help you further analyse the error logs on the GraphApi side:

```
[2021-01-01T22:20:18.072Z] ... failed with an error. Reason: Status Code: BadRequest
[2021-01-01T22:20:18.075Z] Microsoft.Graph.ServiceException: Code: BadRequest
[2021-01-01T22:20:18.077Z] Message: Parameter 'DeltaToken' not supported for this request.
[2021-01-01T22:20:18.079Z] Inner error:
[2021-01-01T22:20:18.080Z]      AdditionalData:
[2021-01-01T22:20:18.081Z]      date: 2021-01-01T22:20:17
[2021-01-01T22:20:18.083Z]      request-id: fdfdd5a9-f3d8-4786-bb1d-ad96b5d24fb1
[2021-01-01T22:20:18.086Z]      client-request-id: fdfdd5a9-f3d8-4786-bb1d-ad96b5d24fb1
[2021-01-01T22:20:18.088Z] ClientRequestId: fdfdd5a9-f3d8-4786-bb1d-ad96b5d24fb1
```

Thanks in advance 
[AB#7149](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7149)

**Comment by andrueastman** [comment]
@dviry This might be related to https://github.com/microsoftgraph/microsoft-graph-docs/issues/7382 which seems to be an issue with the service.
Are you able to confirm that if you call the same link on graph explorer, you will not get the same error? You can get the link like this.
```cs
var nexLink = deltaCollection.NextPageRequest.GetHttpRequestMessage().RequestUri.AbsoluteUri;
```

Also, is there a reason not call the `v1.0` endpoint for this request?
