### ISSUE TITLE
Additional properties for IdentitySet

### ISSUE THREAD

**Issue by JensTrier** [microsoftgraph/msgraph-beta-sdk-dotnet#208]
The documentation page for the beta version of IdentitySet https://docs.microsoft.com/en-us/graph/api/resources/identityset?view=graph-rest-beta shows a set of additional properties like applicationInstance and phone.

In Graph Beta version 0.35.0.0. I'm not able to see these additional properties in C# in VS 2019. I would like to use Graph Call to PSTN, so need to set the Phone property. Is there a way to set it? 
[AB#7558](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7558)

**Comment by andrueastman** [comment]
@JensTrier It seems that the documentation has properties that are not present in the metadata that is used to generate the sdk. You can always check out the metadata [here](https://graph.microsoft.com/beta/$metadata)

We will have to investigate if this is simply an issue of the documentation bug or maybe something up with the metadata itself

**Comment by andrueastman** [comment]
@JensTrier 
The code sample here provides a way to set the property through the additional data. It results to the SDK making a request as the example shows in the docs. It also involves doing a Call transfer to PSTN number. 
https://docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-beta&tabs=csharp#request-2

Are you able to confirm if this works out for you?

**Comment by JensTrier** [comment]
Thanks for the reference. Yes, this works.
