### ISSUE TITLE
synchronizationJob: validateCredentials returns Message: Requested value was not found

### ISSUE THREAD

**Issue by lhartje** [microsoftgraph/msgraph-beta-sdk-dotnet#214]
I am trying to automate AAD Application Provisioning using the Microsfot.Graph.Beta nuget package. I'm following the steps outlined here: https://docs.microsoft.com/en-us/graph/application-provisioning-configure-api.

Specifically, I'm trying to configure an application (DataBricks) that relies on a BaseAddress and a SecretToken as secrets for the synchronization job and I'm running into an issue when attempting to validate the credentials. When the following code executes:
```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

// Validate the credentials for the job
var credentials = new List<SynchronizationSecretKeyStringValuePair>()
{
	new SynchronizationSecretKeyStringValuePair
	{
		Key = SynchronizationSecret.BaseAddress,
		Value = "mybaseaddress"
	},
	new SynchronizationSecretKeyStringValuePair
	{
		Key = SynchronizationSecret.SecretToken,
		Value = "mysecret"
	}
};

await graphClient.ServicePrincipals["{spnid}"].Synchronization.Jobs["{jobid}"]
	.ValidateCredentials(null, "dataBricks", null, credentials)
	.Request()
	.PostAsync();

```
Note, this is similar code to the C# example provided in the Graph Beta API docs at https://docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-validatecredentials?view=graph-rest-beta&tabs=csharp#example, with the templateId of 'dataBricks' being supplied.

The exception returned from the beta graph API is:
```
Message: Requested value 'baseAddress' was not found.
Inner error:
	Code: InternalError
Message: Requested value 'baseAddress' was not found.
Inner error:
	Code: UnSpecified
Message: Message:Requested value 'baseAddress' was not found.
```

I attached fiddler to the process, and when making the call to /servicePrincipals/{id}/synchronization/jobs/{id}/validateCredentials the following JSON payload is POSTed:
```
{"templateId":"dataBricks","useSavedCredentials":false,"credentials":[{"key":"baseAddress","value":"mybaseaddress","@odata.type":"microsoft.graph.synchronizationSecretKeyStringValuePair"},{"key":"secretToken","value":"mysecret","@odata.type":"microsoft.graph.synchronizationSecretKeyStringValuePair"}]}
```

I tried posting this JSON payload to the REST endpoint via PowerShell and received the same error:
```
Invoke-RestMethod: {
  "error": {
    "code": "InternalError",
    "message": "Requested value 'baseAddress' was not found.",
    "innerError": {
      "code": "InternalError",
      "details": [],
      "message": "Requested value 'baseAddress' was not found.",
      "target": null,
      "innerError": {
        "code": "UnSpecified",
        "details": [],
        "message": "Message:Requested value 'baseAddress' was not found.",
        "target": null
      },
      "date": "2021-01-28T19:14:23",
      "request-id": "<removed request-id>",
      "client-request-id": "<removed client-request-id>"
    }
  }
}
```

If I modify the JSON payload to capitalize the b in baseAddress, the error changes - to "Requested value 'secretToken' was not found". Capitalizing the S in secretToken results in the call being performed correctly. 

The working JSON payload is below:
```
{"templateId":"dataBricks","useSavedCredentials":false,"credentials":[{"key":"BaseAddress","value":"mybaseaddress","@odata.type":"microsoft.graph.synchronizationSecretKeyStringValuePair"},{"key":"SecretToken","value":"mysecret","@odata.type":"microsoft.graph.synchronizationSecretKeyStringValuePair"}]}
```

I'm not sure if this is a change/issue in the Azure Graph Beta API or the client (or possibly both? - the error message from the API includes the incorrect capitalization, while the .Net client is submitting the request with incorrect capitalization).

One thing I did notice, is that in the Azure Graph Beta API REST examples the capitalization appears to be documented correctly:
https://docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-validatecredentials?view=graph-rest-beta&tabs=http#request - The example uses UserName and Password and they both have their first letter capitalized.
 
[AB#7855](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7855)

**Comment by MIchaelMainer** [comment]
This is a bug. The workaround is to specify the properties via the AdditionalData property bag.

```csharp
new SynchronizationSecretKeyStringValuePair
{
    AdditionalData = new Dictionary<string, object>()
    {
        {"Key", SynchronizationSecret.SecretToken.ToString()},
        {"Value", "mysecret"}
    }
}
```

Note to team:
The EnumConverter camelcases the enum name. I haven't determined whether OData requires case-sensitivity here or not. First time I can recall this has become an issue.

**Comment by lhartje** [comment]
@MIchaelMainer When I tried adding the AdditionalProperties I get the following exception when calling validateCredentials:

```
Microsoft.Graph.Core: Code: RequestParameterInvalid
Message: parameters : The property 'Key' does not exist on type 'microsoft.synchronization.synchronizationSecretKeyStringValuePair'. Make sure to only use property names that are defined by the type.
```
I modified your code snipped to the following and was able to call the endpoint successfully:
```
new SynchronizationSecretKeyStringValuePair
{   
	AdditionalData = new Dictionary<string, object>()
	{
		{"key", SynchronizationSecret.BaseAddress.ToString() },
		{"value", "mysecret" }
	}
}
```

Note the lower case "key" and "value" as the dictionary keys.

Today's theme of the day is clearly capitalization issues! :)

**Comment by MIchaelMainer** [comment]
@lhartje It sure is! Thank you for sharing the correction.

**Comment by ddyett** [comment]
closing ass this is an older SDK version at this point.
