### ISSUE TITLE
Implement DELETE microsoftAuthenticatorAuthenticationMethod

### ISSUE THREAD

**Issue by colinhqgit** [microsoftgraph/msgraph-beta-sdk-dotnet#218]
Is it possible to implement the DELETE of a microsoftAuthenticatorAuthenticationMethod?

As documented [here](https://docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta).

Just as it is implemented for PhoneAuthenticationMethod [here](https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-beta&tabs=csharp).

Thanks! 
[AB#7959](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7959)

**Comment by andrueastman** [comment]
This is now available in the latest release of the beta sdk.

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/a09d8ff04187461ae29d2ce2fa08797d7ede4e3e/src/Microsoft.Graph/Generated/requests/MicrosoftAuthenticatorAuthenticationMethodRequest.cs#L77
