### ISSUE TITLE
Getting runtime error after upgrading to Microsoft.Graph.Beta sdk dotnet 0.37.0 -preview

### ISSUE THREAD

**Issue by nilakhan** [microsoftgraph/msgraph-beta-sdk-dotnet#224]
Getting the following runtime error after upgrading to Microsoft.Graph.Beta sdk dotnet 0.37.0 -preview: 

System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Graph.Core, Version=1.23.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Previously, I was using 0.35.0 -preview, which was working fine. 
[AB#8121](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8121)

**Comment by nikithauc** [comment]
[3:39 PM] Nikitha Udaykumar Chettiar
    Have you upgraded to 1.24? 
​[3:39 PM] Nikitha Udaykumar Chettiar
    1.24 of the Microsoft Graph Core? 
[3:41 PM] Nishant Lakhanpal
    Yes. I explicitly added 1.24 Microsoft Graph Core dependency

**Comment by zengin** [comment]
@nilakhan we can't locally reproduce this issue. Can you please clean your bin/ obj/ folders and run a clean build? Please let us know if it fixes the issue.

See SO thread on similar errors: https://stackoverflow.com/questions/93879/hresult-0x80131040-the-located-assemblys-manifest-definition-does-not-match-t

**Comment by nilakhan** [comment]
This issue happens only when called from Tests ([TestMethod]), looks like there is some compatibility issue with "Microsoft.VisualStudio.TestTools.UnitTesting".

Steps to repro: 

	1. Create a Unit test project in visual studio
	2. Try adding a sample code using GraphClientFactory

**Comment by zengin** [comment]
In case anyone else hits the same issue:
This has been resolved by adding an app.config file to the project with the following content.
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Graph.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.24.0.0" newVersion="1.24.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
