### ISSUE TITLE
Can't use AddAsync to create a new TodoTaskList

### ISSUE THREAD

**Issue by michael-hawker** [microsoftgraph/msgraph-beta-sdk-dotnet#226]
Using Microsoft.Graph.Beta NuGet 0.37.0-preview

Trying to follow the code in the [docs here](https://docs.microsoft.com/en-us/graph/api/todo-post-lists?view=graph-rest-1.0&tabs=csharp#request):

```cs
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var todoTaskList = new TodoTaskList
{
	DisplayName = "Travel items"
};

await graphClient.Me.Todo.Lists
	.Request()
	.AddAsync(todoTaskList);
```

Causes a `ServiceException` about at type mismatch for `microsoft.toDo.todoTaskList`.

This seems to be a mismatch between what the server is expecting and the type listed in the C# code:

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/6f8fb693583d75d13bd52162f75e25092d8c4e19/src/Microsoft.Graph/Generated/model/TodoTaskList.cs#L30

Is there a reason the outgoing request is sending the type? Do the types on the service change often? This seems problematic.

Error info:
```
Microsoft.Graph.ServiceException
HResult=0x80131500
Message=Code: invalidRequest
Message: A type named 'microsoft.toDo.todoTaskList' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.
Inner error:
Code: InvalidModel
AdditionalData:
date: 2021-02-12T22:26:16
request-id: fec75446-7078-4091-9e91-0ad3f7a93c27
client-request-id: fec75446-7078-4091-9e91-0ad3f7a93c27
ClientRequestId: fec75446-7078-4091-9e91-0ad3f7a93c27 Source=Microsoft.Graph.Core
StackTrace:
at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
``` 
[AB#8137](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8137)

**Comment by michael-hawker** [comment]
This same error occurs with creating tasks as well:

```
Me.Todo.Lists[id].Tasks.Request.AddAsync(todoTask)
```

FYI @darrelmiller

**Comment by andrueastman** [comment]
This looks to be related to this https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/312. 

At the moment, you can workaround the error by doing this.

```cs
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var todoTaskList = new TodoTaskList
{
        ODataType = null, // unset this value
	DisplayName = "Travel items"
};

await graphClient.Me.Todo.Lists
	.Request()
	.AddAsync(todoTaskList);
```

**Comment by michael-hawker** [comment]
@andrueastman @MIchaelMainer @Darrelmiller this is broken for update requests as well like:

```cs
graphClient.Me.Todo.Lists[listid].Tasks[taskid].Request().UpdateAsync(task)
```

When is this going to be fixed? It seems like the whole SDK is a non-started with this issue. Is there an older version before this issue was introduced that we can revert to?

This is super painful, like it's almost easier to go back to making manual HTTP requests (which is what we did for our hackathon initially). ☹

Are there automated tests to ensure that the SDK can work with the live service? If so, is there a reason they didn't catch this?

Thanks!

**Comment by MIchaelMainer** [comment]
@michael-hawker I agree, this is super painful. 

We originally generated with odata.type instance annotation when there were a few services that had a few scenarios that required it. It was fine at that point. Services that didn't expect the odata.type instance annotation gracefully ignored the annotation. As new APIs onboarded, some of them didn't gracefully ignore the unexpected instance annotations. The service API owners don't test the .NET client with their service. We don't have the resources to test every API (not yet, it will happen). There is no way from the metadata for us to determine which APIs do not ignore the unexpected instance annotation or to know which ones do expect it. 

The only place where information exists about the requirement (or not) for odata.type is in the documentation. There are [over 8000 occurrences of "odata.type" in the documentation](https://github.com/microsoftgraph/microsoft-graph-docs/search?p=1&q=odata.type). @andrueastman For FHL, I was planning on taking a look at our tools that ingest the documentation request code blocks to see if we can determine when odata.type is expected and then add an annotation to CSDL to indicate whether we need to generate the setting of odata.type for specific entity.

**Comment by andrueastman** [comment]
This is resolved via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/296 and https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534 and should now be available through https://www.nuget.org/packages/Microsoft.Graph.Beta/4.4.0-preview

**Comment by michael-hawker** [comment]
FYI @shweaver-MSFT

**Comment by shweaver-MSFT** [comment]
Oh yah, I encountered this a few times while building the contoso notes app. Glad to see things are resolved now 😊
