### ISSUE TITLE
The value 'Microsoft.Graph.Contact' is not of type 'Microsoft.Graph.DirectoryObject'

### ISSUE THREAD

**Issue by schwarzie2478** [microsoftgraph/msgraph-beta-sdk-dotnet#23]
In the api specification, you can request the members of a group. 
This returns Directory objects in the api version 1.0.

But in the beta api, this now also can return  Contacts ( guest accounts or external emails ).
But the SDK always tries to deserialize to DirectoryObjects.

Can we get support for groups with Contacts in the SDK? 
[AB#7151](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7151)

**Comment by MIchaelMainer** [comment]
This may be an issue where odata.type is not being returned so we can determine whether the object is an orgContact.

https://developer.microsoft.com/en-us/graph/graph-explorer?request=contacts%2Fe63333f5-3d11-4026-8fe3-c0f7b044dd3a&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com

**Comment by colinhqgit** [comment]
I am having similar issues with Groups when I expand to retrive its owners:

The value 'Microsoft.Graph.User' is not of type 'Microsoft.Graph.DirectoryObject' and cannot be used in this generic collection.

Was this already fixed in a later beta sdk version? Why is it no longer in the backlog? Thanks.

**Comment by ddyett** [comment]
@andrueastman did we address this with V5?

**Comment by andrueastman** [comment]
Closing this for now. The correct `@odata.type` is returned from the API as seen in below and the SDK appropriately deserializes this. 
![image](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/6464005/a25eeb01-55bd-4a2a-afee-46c0da62f334)
