### ISSUE TITLE
Add auto-update of minor version to new generation template

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-beta-sdk-dotnet#241]
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/beta/pipelinebuild/42274/scripts/bumpVersion.ps1 
[AB#8407](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8407)

**Comment by ddyett** [comment]
closing older issue
