### ISSUE TITLE
Why is the PageIterator class not available in beta ?

### ISSUE THREAD

**Issue by kalyankrishna1** [microsoftgraph/msgraph-beta-sdk-dotnet#242]
Its forcing me to use both GA and Beta SDKs in the same code base and all kinds of compilation issues like "System.MissingMethodException: 'Method not found" when i updated the libs 
[AB#8469](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8469)

**Comment by andrueastman** [comment]
@kalyankrishna1 Thank you for the feedback. We are planning to move the pageIterator to the core library. This is tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/179

I will close this issue for now so that it may be tracked there.
