### ISSUE TITLE
Delta Query fails for MS Teams Channel with no conversation

### ISSUE THREAD

**Issue by ajeetbansal** [microsoftgraph/msgraph-beta-sdk-dotnet#243]
Steps to reproduce: 
1. Create a Channel in MS Teams and do not post any conversations in the channel. 
2. Invoke the following query to get the channel messages using delta query: https://graph.microsoft.com/beta/teams/{{TeamId}}/channels/{{ChannelId}}/messages/delta 
3. An empty response will be returned with a next link. eg { "@odata.context": "https://graph.microsoft.com/beta/$metadata#Collection(chatMessage)", "@odata.nextLink": "https://graph.microsoft.com/beta/teams/75535b14-113e-4bee-a63f-e8562ebfd3de/channels/19:321abe1548dc46478ba1b78dc4c66675@thread.tacv2/messages/delta?$skiptoken=jvWS65BoVoenP3WxgWWn7GBbw6mKx5XoXEMTn-EZK8RT8GiUI61wa69WI0VENdibFgje60HReF0J7-3vG9Gyiw.ki2OFDgCrgacx17owZ8f_fPiBv8PfNLtGWOA9fhgJ7s", "value": [] } 

4. Try to query again by using the nextLink from the above response. This time it returns HTTP Response Code 400 with the following payload: { "error": { "code": "BadRequest", "message": "Parameter 'DeltaToken' not supported for this request.", "innerError": { "date": "2021-02-26T02:49:36", "request-id": "1ddb3b02-185c-40f9-a873-434b76ee2a16", "client-request-id": "1ddb3b02-185c-40f9-a873-434b76ee2a16" } } } 
[AB#8520](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8520)

**Comment by andrueastman** [comment]
@ajeetbansal Are you performing these calls with the sdk? Or are you using graph explorer?

**Comment by ajeetbansal** [comment]
I am making the api call using postman.

**Comment by sumanac** [comment]
We are looking at the delta query failure

**Comment by ddyett** [comment]
closing as was handed off to service team.
