### ISSUE TITLE
Can Beta endpoint be used with B2C?

### ISSUE THREAD

**Issue by tmarkovski** [microsoftgraph/msgraph-beta-sdk-dotnet#25]
Apologies for opening an issue to just ask a question. It isn't clear to me if we can use Beta endpoint to manage users in Azure B2C? Can Microsoft Graph at all be used for this? We'd like to integrate B2C management in a NET Core project and older Azure Graph seems to be phasing out and only supports NET Framework.
Thank you.

**Comment by darrelmiller** [comment]
Hey @tmarkovski this is a tricky subject.  I have been informed that some parts of the Graph can be accessed via a B2C user, however other parts cannot.  If you stick with information coming from AAD, then you should be ok, but as soon as you try and request any information that comes from O365, it will currently fail.

**Comment by tmarkovski** [comment]
Thanks @darrelmiller. We're really only interested in AAD data, specifically listing, inviting, disabling users. Is it possible that this can be setup using a service principal scenario?

**Comment by darrelmiller** [comment]
If you can create an app registration in the B2C tenant and setup a client secret, then you should be able to make "application-only" calls to Microsoft Graph to manage that set of users.  You will need to assign the application "Application Permissions" and not "Delegated Permissions".

**Comment by MIchaelMainer** [comment]
Closing since there is no more follow up in 20+ days.
