### ISSUE TITLE
Sample in V2 upgrade guide is misleading...

### ISSUE THREAD

**Issue by mahage-msft** [microsoftgraph/msgraph-beta-sdk-dotnet#256]
The authentication sample in [https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v2.md] suggests that InteractiveBrowerCredential has an overload that accepts a string called clientId.  However, there is no such overload.  Would be good to include the correct datatype in the sample...

InteractiveBrowserCredentialOptions interactiveBrowserCredentialOptions = new InteractiveBrowserCredentialOptions()
                                                                                {
                                                                                    ClientId = clientId
                                                                                };
InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredential(interactiveBrowserCredentialOptions);
 
[AB#8713](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8713)

**Comment by andrueastman** [comment]
Thanks for the feedback @mahage-msft.

The overload exists in the code [here](https://github.com/Azure/azure-sdk-for-net/blob/0559b55be417d1d706d3a329f82214a1afc44972/sdk/identity/Azure.Identity/src/InteractiveBrowserCredential.cs#L53) but seems not be present in the docs.

We will update the sample to use your suggestion to avoid any confusion going forward.

**Comment by mahage-msft** [comment]
Hmmmm, interesting it shows up in the code there.  It doesn't show up in intellisense either.  Is that code part of the preview bits for Azure.Identity?  I installed 1.3.0 and didn't see any such constructors.

**Comment by andrueastman** [comment]
I had built a sample app earlier and it works well with the constructor. You can check out the sample app here
https://github.com/andrueastman/GraphResponseSample

I believe the `EditorBrowsable` attribute in [the source](https://github.com/Azure/azure-sdk-for-net/blob/0559b55be417d1d706d3a329f82214a1afc44972/sdk/identity/Azure.Identity/src/InteractiveBrowserCredential.cs#L52) is what makes it not discoverable by IntelliSense.

**Comment by andrueastman** [comment]
This has been updated through https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/942

You can find the updated guide at this link https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md

More TokenCrediential samples have also been provided as well here
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/tokencredentials.md
