### ISSUE TITLE
Graph client SDK is missing 'external' in the URL when trying to create ExternalItem

### ISSUE THREAD

**Issue by kotpal** [microsoftgraph/msgraph-beta-sdk-dotnet#260]
I am able to create an external item using a PowerShell script and also by sending requests using PostMan - but unable to create it using the C# SDK.

Doing a fiddler trace, I notice that the request is not going over the wire at all when I am calling:

`await graphClient.Connections[connectionId].Items[item.Id].Request().PutAsync(item);
`
So I dumped the URL the graph client is using and it is missing 'external' in it in between beta and connections.

`https://graph.microsoft.com:443/beta/connections/MyConnector/items/ABCD12345
`
I am using the full URL (https://graph.microsoft.com/beta/**external**/connections/MyConnector/items/ABCD1234) in my PowerShell script (I am not using PowerShell SDK) and I am able to create the external item - and I could see the traffic in fiddler.

So there seems to be an issue with the C# Graph Client SDK - in that it is missing the "external" in the URL it is using to PUT the item. 
[AB#8725](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8725)

**Comment by kotpal** [comment]
I can confirm with 100% certainty that "external" is missing from the URL.

I put a breakpoint and changed the externalItemRequest.RequestUrl to include "external" between beta and connections, and I am able to create the external item.

Looks like you need to change the code at https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/abf705e2dd1b0b0e4bec13dde7c4d39f4628b881/src/Microsoft.Graph/Generated/externalconnectors/requests/ExternalRequestBuilder.cs#L61 from:
`return new ExternalConnectionsCollectionRequestBuilder(this.AppendSegmentToRequestUrl("connections"), this.Client);
`to:
`return new ExternalConnectionsCollectionRequestBuilder(this.AppendSegmentToRequestUrl("external/connections"), this.Client);`

(or something similar).

I will see if I can update the code and do a PR.

Aaaaargh

**Comment by MIchaelMainer** [comment]
@kotpal 

It looks like the documentation is missing an example for this scenario. 

Please use the following (note the External property after client):

`await client.External.Connections[""].Items[""].Request().PutAsync(new ExternalItem());`

Please let us know if this works.
