### ISSUE TITLE
Graph SDK (C#) PrivilegedAccess for governanceRoleAssignmentRequest documentation does not work 

### ISSUE THREAD

**Issue by stevelange17** [microsoftgraph/msgraph-beta-sdk-dotnet#266]
When trying leverage the C# sample code in this documentation: https://docs.microsoft.com/en-us/graph/api/governanceroleassignmentrequest-post?view=graph-rest-beta&tabs=csharp#response there seem to be issues specifically with this call:
```
await graphClient.PrivilegedAccess["{privilegedAccess-id}"].RoleAssignmentRequests
            .Request()
    .AddAsync(governanceRoleAssignmentRequest);
```

The documentation doesn’t explain where to get the value for privilegedAccess-id in this call. The HTTP sample on this page works fine, but not the C# sample.  
[AB#8788](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8788)

**Comment by MIchaelMainer** [comment]
@stevelange17 The metadata used to generate the client library and SDK code examples doesn't match the documented API, or the documentation needs to be clearer on the identifiers for the entityset. There is information about the identifiers here: https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-resources?view=graph-rest-beta. . Here is how to use the client library in the current state for this API:

```csharp
var governanceRoleAssignmentRequest = new GovernanceRoleAssignmentRequestObject()
{
    ResourceId = "",
    RoleDefinitionId = "",
    SubjectId = "",
    AssignmentState = "",
    Type = ""
};

await graphClient.PrivilegedAccess["azureResources"].RoleAssignmentRequests
                 .Request()
                 .AddAsync(governanceRoleAssignmentRequest);
```

** Note to self **

      <EntitySet Name="privilegedAccess" EntityType="microsoft.graph.privilegedAccess" />

      <EntityType Name="privilegedAccess" BaseType="graph.entity">
        <Property Name="displayName" Type="Edm.String" />
        <NavigationProperty Name="resources" Type="Collection(graph.governanceResource)" ContainsTarget="true" />
        <NavigationProperty Name="roleAssignmentRequests" Type="Collection(graph.governanceRoleAssignmentRequest)" ContainsTarget="true" />
        <NavigationProperty Name="roleAssignments" Type="Collection(graph.governanceRoleAssignment)" ContainsTarget="true" />
        <NavigationProperty Name="roleDefinitions" Type="Collection(graph.governanceRoleDefinition)" ContainsTarget="true" />
        <NavigationProperty Name="roleSettings" Type="Collection(graph.governanceRoleSetting)" ContainsTarget="true" />
      </EntityType>

**Comment by dja24030** [comment]
With proper authorization when i try following code, to create Eligible type of role assignment, I get InvalidRoleAssignmentRequest error.

Code snippet:

			var governanceRoleAssignmentRequest = new GovernanceRoleAssignmentRequestObject
			{
				RoleDefinitionId = "12bdb772-19bb-4910-957a-751da2473cc4",
				ResourceId = "XXXXXX-XXXX-XXXX-a102-0f77576da83f",
				SubjectId = "XXXXXXXXXX",
				AssignmentState = "Eligible",
				Type = "AdminAdd",
				Reason = "DG testing with MSFT",
				Schedule = new GovernanceSchedule
				{
					Type = "Once",
					StartDateTime = DateTimeOffset.Parse("2021-03-31T23:28:43.537Z"),
					Duration = null
				},
			};

			GraphSvcClient
			   .PrivilegedAccess["azureResources"].RoleAssignmentRequests
				.Request()
				.AddAsync(governanceRoleAssignmentRequest).Wait();

Error:
Inner Exception 1:
ServiceException: Code: InvalidRoleAssignmentRequest
Message: The role assignment request is invalid.
Inner error:
	AdditionalData:
	date: 2021-03-31T03:43:56
	request-id: a02b7f9a-2425-4bae-b8c8-bd4670347130
	client-request-id: a02b7f9a-2425-4bae-b8c8-bd4670347130
ClientRequestId: a02b7f9a-2425-4bae-b8c8-bd4670347130

**Comment by MIchaelMainer** [comment]
@dja24030 I'm not familiar enough with this API to be able to help here. @shauliu wrote the referenced documentation. Can you provide guidance here?

**Comment by stevelange17** [comment]
@dja24030 Can you validate that you had/have a valid access token? Getting the access token is outside the scope of the Microsoft Graph client library. That involves the identity API and the identity client library, like MSAL. Microsoft Graph client library will consume the results of an identity call and fix the bearer token to the authorization header. Assuming that you’re using MSAL, there is guidance here https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-error-handling-dotnet for fall backs when MFA is enabled.

**Comment by stevelange17** [comment]
That said, I to am curious about the error "InvalidRoleAssignmentRequest" - it's not listed in the error codes section of the docs..

https://docs.microsoft.com/en-us/graph/api/governanceroleassignmentrequest-post?view=graph-rest-beta&tabs=http#error-codes

**Comment by dja24030** [comment]
@stevelange17  I believe I have correct Access token. When I didnt pass correct credential / didnt have right permission, I did get authentication / Authorization / Permission error back instead of "InvalidRoleAssignmentRequest" 
Let me know if there is a way to explicitly validate access token on call made using Graph SDK.

**Comment by dja24030** [comment]
@stevelange17  I believe I have correct Access token. When I didnt pass correct credential / didnt have right permission, I did get authentication / Authorization / Permission error back instead of "InvalidRoleAssignmentRequest" 
Let me know if there is a way to explicitly validate access token on call made using Graph SDK.

**Comment by MIchaelMainer** [comment]
@stevelange17 I created an incident so that this is raised to the service owner. Can you provide information in this incident: https://portal.microsofticm.com/imp/v3/incidents/details/234382069/home

**Comment by gauravmishra119** [comment]
We do not support the APP only token call. The above call is made through app only token.

I was just trying to create a small c# app to call graph directly without graph client. Can you try something like this ?

Also can you share the fiddler trace, I want to check exact request sent by graph client.

**Comment by MIchaelMainer** [comment]
@gauravmishra119 

The following GraphServiceClient code:

```csharp
var governanceRoleAssignmentRequest = new GovernanceRoleAssignmentRequestObject()
{
    ResourceId = "",
    RoleDefinitionId = "",
    SubjectId = "",
    AssignmentState = "",
    Type = ""
};

await graphClient.PrivilegedAccess["azureResources"].RoleAssignmentRequests
                 .Request()
                 .AddAsync(governanceRoleAssignmentRequest);
```

emits the following:

```http
POST https://graph.microsoft.com/beta/privilegedAccess/azureResources/roleAssignmentRequests HTTP/1.1

{
  "assignmentState": "",
  "resourceId": "",
  "roleDefinitionId": "",
  "subjectId": "",
  "type": "",
  "@odata.type": "microsoft.graph.governanceRoleAssignmentRequest"
}
```

**Comment by ddyett** [comment]
closing this older issue.
