### ISSUE TITLE
Problem regarding Mircodoft.Graph.Beta 4.0.0 preview

### ISSUE THREAD

**Issue by ChristianWolber** [microsoftgraph/msgraph-beta-sdk-dotnet#268]
Problem regarding Mircodoft.Graph.Beta 4.0.0 preview
 
Issue: 
Dependencies can be added but property AutoInstall = true not set
 
Method: 
MobileLobAppRequestBuilder. UpdateRelationships
 
Exceptions:
 
none
 
Workflow (condensed):
var requestBuilder = new MobileLobAppRequestBuilder(_graphClient.RetrieveGraphServiceClient().DeviceAppManagement.MobileApps[sourceApp.Id].RequestUrl, _graphClient.RetrieveGraphServiceClient());
List<MobileAppRelationship> dependenciesTo;
dependenciesTo = (await _graphClient.RetrieveGraphServiceClient().DeviceAppManagement.MobileApps[sourceApp.Id].Relationships.Request().GetAsync()).ToList();
 
dependenciesTo.Add(new MobileAppDependency()
                {
                    TargetId = targetApp.Id,
                    TargetDisplayName = targetApp.DisplayName,
                    DependencyType = MobileAppDependencyType.AutoInstall
                });
var req = requestBuilder.UpdateRelationships(dependenciesTo).Request();
await req.PostAsync();
 
Kind Regards
Christian Wolber
 
[AB#8807](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8807)

**Comment by andrueastman** [comment]
@ChristianWolber Thanks for raising this issue. Any chance you can confirm if the issue is reproduced in the later version? (https://www.nuget.org/packages/Microsoft.Graph.Beta/4.0.1-preview)

Also just to confirm when you say
> Dependencies can be added but property AutoInstall = true not set

Do you mean this [property](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/feature/2.0/src/Microsoft.Graph/Generated/model/MobileAppDependency.cs#L36)?

**Comment by ChristianWolber** [comment]
@andrueastman 

I tested with the new 4.0l1-preview. The mentioned property is now set to AutoInstall as desired.

The issue can be closed.

Thank You and kin regards,
Christian Wolber

**Comment by andrueastman** [comment]
@ChristianWolber Thank you for the feedback and for trying out the new preview package.
