### ISSUE TITLE
Adding an Entitlement Management Catalog Owner with Microsoft.Graph.Beta

### ISSUE THREAD

**Issue by cgontario** [microsoftgraph/msgraph-beta-sdk-dotnet#283]
**Describe the bug**
Unable to add an Entitlement Management Catalog Owner via Microsoft.Graph.Beta v4.0.1-preview.

**To Reproduce**
```
var assignment = new UnifiedRoleAssignment
{
    RoleDefinitionId = role.Id,
    PrincipalId = catalogRole.PrincipalId.ToString(),
    AppScopeId = $"/AccessPackageCatalog/{catalogId}"
};

await graphClient.RoleManagement.EntitlementManagement.RoleAssignments
    .Request()
    .AddAsync(assignment);
```

RoleDefinitionId, PrincipalId and AppScopeId were all pulled from an existing assignment on the Catalog, so I think they're correct:

[![Existing Entitlement Management Role Assignment][1]][1]

  [1]: https://i.stack.imgur.com/UWzL7.png

**Expected behavior**
Expected the given user to be assigned to the Catalog Owner role for the given Catalog.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Edge 89
 - Version: Microsoft.Graph.Beta v4.0.1-preview in a .NET Core 3.1 Console App host

**Additional context**
I'm not finding any documentation for Microsoft.Graph.Beta.GraphServiceClient.RoleManagement.EntitlementManagement.RoleAssignments.

I'm able to use it to pull the current assignments, and the filter clause supports roleDefinitionId and principalId, but refuses to filter on appScopeId. This makes me suspicious: am I calling the wrong part of the API for this?
 
[AB#9025](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9025)

**Comment by cgontario** [comment]
Thanks for responding so quickly @andrueastman :) I tried 0.43.0-preview and unfortunately I received the same InvalidModel error. Here are the error details:

```
Code: InvalidModel
Message: Model is not valid.
Inner error:
	AdditionalData:
	date: 2021-04-16T13:26:54
	request-id: 59a17e45-6282-4e5a-80dd-e55efa788089
	client-request-id: 59a17e45-6282-4e5a-80dd-e55efa788089
ClientRequestId: 59a17e45-6282-4e5a-80dd-e55efa788089
```

**Comment by cgontario** [comment]
I confirmed that this isn't a bug in Graph API itself by [setting up Postman as detailed here](https://docs.microsoft.com/en-us/graph/use-postman) and adding a new Catalog Owner.

**Comment by cgontario** [comment]
A little more information and a work-around:

If I serialize a Beta.UnifiedRoleAssignment and send a POST to Graph I also get an InvalidModel error. All of the uninitialized properties are included in the JSON:

```
{
    "appScopeId": "/AccessPackageCatalog/603b69ff-283e-4fa3-a7aa-99d51aa4040d",
    "condition": null,
    "directoryScopeId": null,
    "principalId": "d8f2b33d-fca2-43c9-991c-a45ae674532f",
    "resourceScope": null,
    "roleDefinitionId": "e2182095-804a-4656-ae11-64734e9b7ae5",
    "appScope": null,
    "directoryScope": null,
    "principal": null,
    "roleDefinition": null,
    "id": null,
    "oDataType": "microsoft.graph.unifiedRoleAssignment",
    "additionalData": null
}
```

If I instead serialize a work-around object that only contains the properties I'm setting I'm able to create the Role Assignment:

```
{
    "roleDefinitionId": "e2182095-804a-4656-ae11-64734e9b7ae5",
    "principalId": "c251d039-15aa-4104-8d5b-f91d95da61d9",
    "appScopeId": "/AccessPackageCatalog/603b69ff-283e-4fa3-a7aa-99d51aa4040d"
}
```

Here's the C#:

```
public class UnifiedRoleAssignmentWorkaround
{
	public string AppScopeId { get; set; }

	public string PrincipalId { get; set; }

	public string RoleDefinitionId { get; set; }
}

...

var assignment = new UnifiedRoleAssignmentWorkaround()
{
	RoleDefinitionId = role.Id,
	PrincipalId = catalogRole.PrincipalId.ToString(),
	AppScopeId = $"/AccessPackageCatalog/{catalogId}"
};

var message = new HttpRequestMessage(HttpMethod.Post, "https://graph.microsoft.com/beta/roleManagement/entitlementManagement/roleAssignments");
var jsonOptions = new JsonSerializerOptions(JsonSerializerDefaults.Web);
var assignmentJson = JsonSerializer.Serialize(assignment, typeof(UnifiedRoleAssignmentWorkaround), jsonOptions);
message.Content = new StringContent(assignmentJson, Encoding.UTF8, "application/json");

await graphClient.HttpProvider.SendAsync(message);
```

**Comment by andrueastman** [comment]
@cgontario Can you try this out and let me know if it works out for you?

```cs
var assignment = new UnifiedRoleAssignment
{
    RoleDefinitionId = role.Id,
    PrincipalId = catalogRole.PrincipalId.ToString(),
    AppScopeId = $"/AccessPackageCatalog/{catalogId}",
    "oDataType": null // Add this
};

await graphClient.RoleManagement.EntitlementManagement.RoleAssignments
    .Request()
    .AddAsync(assignment);
```

**Comment by andrueastman** [comment]
Thanks for the feedback. That issue is related to https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/312. We will close this issue once that is resolved/closed.

**Comment by andrueastman** [comment]
This is resolved via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/296 and https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534 and should now be available through https://www.nuget.org/packages/Microsoft.Graph.Beta/4.4.0-preview
