### ISSUE TITLE
Error reading profile of the current logged in user

### ISSUE THREAD

**Issue by mprattinger** [microsoftgraph/msgraph-beta-sdk-dotnet#284]
I'm using the graph client beta sdk in an asp.net core application with aad authentication against an organizational azure active directory.
Calling me/ works as expected but calling me/profile throws the following exception:

Code: Request_ResourceNotFound
Message: Resource 'profile' does not exist or one of its queried reference-property objects are not present.
Inner error:
	AdditionalData:
	date: 2021-04-18T21:04:46
	request-id: 80224395-e342-4b35-9996-aa071f2140d1
	client-request-id: 80224395-e342-4b35-9996-aa071f2140d1
ClientRequestId: 80224395-e342-4b35-9996-aa071f2140d1

Do i miss permissions? I'm using "user.read", "user.readbasic.all", "user.read.all" currently.

Thanks in advance,
best regards 
[AB#9048](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9048)

**Comment by andrueastman** [comment]
@mprattinger Are you able to share how you are initializing the GraphServiceClient and how you are making the call to the SDK?

**Comment by mprattinger** [comment]
Hi,

thank you for your response.

In Startup of my Asp.net core blazor project i'm using:

services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                .EnableTokenAcquisitionToCallDownstreamApi(new[] { "user.read", "user.readbasic.all", "user.read.all" })
                .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
                .AddInMemoryTokenCaches();

and on an other blazor page i call 

var profile= await GraphServiceClient.Me.Profile.Request().GetAsync()

When i do that, i get the mentioned error message.

Thanks,
Michael

**Comment by mprattinger** [comment]
Hi,

thank you for your response.

In Startup of my Asp.net core blazor project i'm using:

services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                .EnableTokenAcquisitionToCallDownstreamApi(new[] { "user.read", "user.readbasic.all", "user.read.all" })
                .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
                .AddInMemoryTokenCaches();

and on an other blazor page i call 

var p= await GraphServiceClient.Me.Profile.Request().GetAsync()

**Comment by andrueastman** [comment]
@mprattinger 
It looks like you might be using Microsoft.Identity.Web.MicrosoftGraph or the Microsoft.Identity.Web.MicrosoftGraphBeta packages. Can you confirm which one?

Also, are you able to confirm that the request url is pointing to the beta endpoint by doing something like this?
```
string url = GraphServiceClient.Me.Profile.Request().RequestUrl;
```

**Comment by mprattinger** [comment]
Hi,

iam using the beta nuget package, but i found out that i havn't changed the config in appsettings.json (idiot me). Therefore, it was using the 1.0 endpoint.

It is working now. Sorry

r Michael

**Comment by andrueastman** [comment]
No worries about that. Closing this now as it resolved.
