### ISSUE TITLE
The app content file data Commit method does not work as expected

### ISSUE THREAD

**Issue by bdhainsw** [microsoftgraph/msgraph-beta-sdk-dotnet#295]
**Describe the bug**
After careful testing, I have found that the mobileApp commit call does not work.
Here is the code we are calling: var lobType = application?.ODataType.Substring(1); var baseUrl = GraphServiceClient.DeviceAppManagement.MobileApps[application.Id].AppendSegmentToRequestUrl(lobType); var lobRequestBuilder = new ManagedMobileLobAppRequestBuilder(baseUrl, GraphServiceClient); lobRequestBuilder.ContentVersions[contentVersion].Files[mobileAppContentFile.Id].Commit(fileEncryptionInfo);
aka: https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/a97a6f34-52e3-429e-8991-15141656a3df/microsoft.graph.win32LobApp/contentVersions/1/files/1bee5b71-fbb1-4ea4-8acb-ca8c259af6f5/commit
The fileEncryptionInfo contains the Base64 decoded .intunewin file detection.xml encryption info. As fileEncryptoinInfo uses byte[] instead of string to store the data in.
The call doesn't fail, but all subsequent calls to get the app content file data, return an UploadState of AzureStorageUriRequestSuccess rather than, checking if the UploadState is CommitFilePending and then loop until it changes to CommitFileSuccess. And not only does the UploadState return the wrong data, the IsCommitted property never changes to true.
If I make the same Commit call via the Graph Api Explorer in a browser or an HttpClient call in code, the call (and subsequent calls) performs as expected.  Only by calling the Commit through the Graph Api Client library does the process fail to work as expected.

**To Reproduce**
There are quite a few steps to go through to reproduce the issue.  I can list them all if needed.
But basically, it's going through all the steps necessary to upload a win32 app into Azure File\Blob Storage.
And then calling the commit method as described above.

**Expected behavior**
The commit call should succeed, and then the subsequent calls to get the the app content file data should return an UploadState of CommitFilePending and\or CommitFileSuccess.  And once CommitFileSuccess is confirmed, the data property IsCommitted should be set to true by Azure.

**Screenshots**
I can provide a dozen screenshots if necessary.  But here is one that shows the app content file data after after uploading the file and calling Commit.
![aftercommit](https://user-images.githubusercontent.com/27227761/116893305-0d61a000-abee-11eb-94eb-0dfdb9baaae0.png)

**Client version**
0.44 and earlier

**Desktop (please complete the following information):**
 - OS: Windows 10 202H
 - Browser n/a
 - Version ?

**Additional context**
I've verified the data I'm passing is the same as Intune and various powershell scripts found on the web are doing, albeit, the Graph Api Client library uses byte[] rather than strings to pass the encryption data in the Commit call.  I do a Base64 decode call on the encryption strings (read from the detection.xml file found in the .intunewin file) to get them into the byte[] format.
 
[AB#9243](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9243)

**Comment by andrueastman** [comment]
Hey @bdhainsw,
Any chance you could try out to send the byte array without doing the base64 decoding?
Also, could you provide the code sample on how you are setting the `fileEncryptionInfo` properties?

**Comment by bdhainsw** [comment]
![FileEncryptionInfo](https://user-images.githubusercontent.com/27227761/117348948-12318880-ae68-11eb-86d7-5f230393ccd6.png)

I don't understand how I can send the byte array without doing the base64 decoding?  Do you mean I should covert the Base64 encoded string I read from the Detection.xml file to a byte[] rather then Base64 decode it?  And then Azure will covert it back to the Base64 encoded string once it receives it?  I can try that.  But if that's what's happening, why not just make the FileEncryptionInfo model take strings instead of byte[]'s?

**Comment by andrueastman** [comment]
> Do you mean I should covert the Base64 encoded string I read from the Detection.xml file to a byte[] rather then Base64 decode it?And then Azure will covert it back to the Base64 encoded string once it receives it?

Yes I do.

>But if that's what's happening, why not just make the FileEncryptionInfo model take strings instead of byte[]'s?
If that is the case, we shall investigate fixing that in a future sdk version.

**Comment by bdhainsw** [comment]
I tried converting the EncryptionInfo strings to byte[] using Encoding.UTF8.GetBytes() and then again using Encoding.UTF8.GetBytes() before calling the Commit call via the Graph Api Library, and both of them failed the same way.  Meaning the Commit call succeeded, but the subsequent call to get the App Content File Data only returns with an UploadState of AzureStorageUriRequestSuccess, rather than CommitFilePending or CommitFileSuccess, and the property IsCommitted is never set to true.

**Comment by bdhainsw** [comment]
Any update on this?

**Comment by ddyett** [comment]
Please try on the new version 5 and if an issue is encountered please open a new issue,
