### ISSUE TITLE
IGraphServiceClient missing in 4.x branches - or is it intentional?

### ISSUE THREAD

**Issue by DerGuru** [microsoftgraph/msgraph-beta-sdk-dotnet#302]
In the 4.x branches of Graph Beta SDK, there is no Interface `IGraphServiceClient` anymore.
I have a lot of unit tests using that interface and I would really like to keep them.

Are there any plans of putting it back or is there a "guide" on how to migrate such unit tests?
 
[AB#9648](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9648)

**Comment by andrueastman** [comment]
@DerGuru This is indeed intentional and discussed [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935#issuecomment-811180925). 

You can also check out changes coming up in the v4 [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md).
