### ISSUE TITLE
Issue while creating hidden folder in outlook

### ISSUE THREAD

**Issue by 3xpl01tc0d3r** [microsoftgraph/msgraph-beta-sdk-dotnet#31]
Hi,

I am trying to create hidden folder in outlook using graph API in C# but I keep getting the below error. 

> **Object reference not set to an instance of an object.**

Code Snippet

	SingleValueLegacyExtendedProperty svlep = new SingleValueLegacyExtendedProperty()
	{
		Id = "Boolean 0x10f4",
		Value = "true"
	};

	MailFolder CreatemailFolder = new MailFolder()
	{
		DisplayName = "HiddenFolder"
	};
	CreatemailFolder.SingleValueExtendedProperties.Add(svlep);

	await graphClient.Users["{id}"].MailFolders
		.Request()
		.AddAsync(CreatemailFolder);

I am using the [Exchange Server Protocols Master Property List](https://interoperability.blob.core.windows.net/files/MS-OXPROPS/%5bMS-OXPROPS%5d.pdf) guide and **PidTagAttributeHidden** property id value as ID parameter. Can someone help me with some reference or solution if I am doing something wrong.

**Comment by MIchaelMainer** [comment]
You'll need to initialize CreatemailFolder.SingleValueExtendedProperties. Let us know if creating a hidden folder works this way via Graph.
