### ISSUE TITLE
setPresence and clearPresence not working

### ISSUE THREAD

**Issue by devpijnenburg** [microsoftgraph/msgraph-beta-sdk-dotnet#316]
Hi,

I'm trying the new public beta endpoint for clearing and setting the presence for a graph user. I'm running into some issues and like to share them with you guys. Of course it's a beta endpoint and that is also the reason I like to share my feedback.

Tried to call the API using multiple tenants and multiple applications. All applications did have the option to enable the application permission: `Presence.ReadWrite.All` for graph.

After authenticating in postman (as well as with a console application) when I post the information below I get two different results for both my tenants.
`POST  https://graph.microsoft.com/beta/users/[userid_concealed]/presence/setPresence`

Body:
```
{
    "sessionId": "[appid_concealed]",
    "availability": "Away",
    "activity": "Away",
    "expirationDuration": "PT5M"
}
```

Result tenant 1:
- 200 OK
- Availability not changing
- Activity not changing

Result tenant 2:
- 401 Unauthorized
- body: 
```
{
    "error": {
        "code": "ServiceError",
        "message": "An error has occurred.",
        "innerError": {
            "request-id": "61cce29a-b91d-474d-beb9-09a19afc3341",
            "date": "2021-07-01T12:01:56",
            "client-request-id": "61cce29a-b91d-474d-beb9-09a19afc3341"
        }
    }
}
```
- Availability not changing
- Activity not changing

We checked presences in teams and by getting the me from graph in the graph explorer.

It is strange that both tenants result in another thing. The first is a production tenant, the second a development. 
[AB#10104](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10104)

**Comment by Josverl** [comment]
Also hitting the 401 on my dev tenant.

**Comment by kwaazaar** [comment]
Can you please provide some feedback on this issue? Could you confirm it maybe?

**Comment by onyas** [comment]
we also encountered this error, any feedback about this issue?
```
{
    "error":  {
        "code": "ServiceError",
        "message": "An error has occurred.",
        "innerError": {
            "request-id": "0c71d12f-1c09-461e-a2d8-7449f8ed487b",
            "date": "2023-06-13T08:52:31",
            "client-request-id": "0c71d12f-1c09-461e-a2d8-7449f8ed487b"
        }
   }
}
```

**Comment by ddyett** [comment]
this appears to be an issue with the service.  I'd suggest trying here https://developer.microsoft.com/en-us/graph/support.  Closing this one as we can't action.
