### ISSUE TITLE
content method is missing for request builders of child entity types

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-beta-sdk-dotnet#319]
if an entity type inherits from another entity type which has steam = true, the request builder for the child entity type should have the "content" method.
Such example is this request builder https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/requests/ChatMessageHostedContentRequestBuilder.cs

more details https://github.com/microsoftgraph/msgraph-beta-sdk-java/issues/128#issuecomment-876389108 
[AB#10150](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10150)

**Comment by andrueastman** [comment]
Related to https://github.com/microsoft/OpenAPI.NET.OData/issues/314

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/640

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/93795377258a87e6f1a0e616d2053772b9167f98/src/Microsoft.Graph/Generated/Users/Item/Chats/Item/Messages/Item/HostedContents/Item/ChatMessageHostedContentItemRequestBuilder.cs#L18
