### ISSUE TITLE
Issue while reading the messages from teams channel

### ISSUE THREAD

**Issue by 3xpl01tc0d3r** [microsoftgraph/msgraph-beta-sdk-dotnet#32]
Hi,

While trying to read the message from teams channel I keep getting timeout message. 

> **Code: timeout
Message: The request timed out.**

Code Snippet

	IChannelMessagesCollectionPage messages = await graphClient.Teams["{id}"].Channels["{id}"].Messages
		.Request()
		.Top(1)
		.GetAsync();

Can someone help me to resolve this issue or guide me on how can I fix this issue.

**Comment by MIchaelMainer** [comment]
Thank you for your question about the Microsoft Graph. Please post your questions to StackOverflow with the microsoftgraph tag. After you've posted your question on StackOverflow, please provide a link here back to your post. That way, the question will be found by more people -- plus it gives back to the dev community on StackOverflow. 

Make sure you include the following information in your post on StackOverflow:
* What you've tried, your repro steps
* A trace of both the request and response
* Any error messages
* Any settings
