### ISSUE TITLE
Unable to create mobileAppInstallStatus records via DeviceStatuses

### ISSUE THREAD

**Issue by bdhainsw** [microsoftgraph/msgraph-beta-sdk-dotnet#332]
I'm trying to create mobileAppInstallStatus records.  See docs here:  https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-apps-mobileappinstallstatus-create.md

The preferred method is via the msgraph beta sdk, but nothing I've tried works.  The obvious implementation being:

var createdMobileAppInstallStatus = Task.Run(async () => await GraphServiceClient.DeviceAppManagement.MobileApps[mobileAppId].DeviceStatuses.Request().AddAsync(mobileAppInstallStatus).ConfigureAwait(false)).Result;

The call returns the exception:
Message: No OData route exists that match template ~/singleton/navigation/key/navigation with http verb POST for request /AppLifecycle_2107/StatelessAppMetadataFEService/deviceAppManagement/mobileApps('aefeca9e-fc0f-44b6-ae06-61faef2e6e1a')/deviceStatuses

I've also tried various alternatives in the Graph API Explorer and making direct http REST calls to the graph API in code.  None of them worked, and most gave a similar error as above.

How can I create a mobileAppInstallStatus record using the msgraph-beta-sdk?
 
[AB#10611](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10611)

**Comment by ddyett** [comment]
closing as this is an older service issue.
