### ISSUE TITLE
Missing AddAsync method in some scenarios

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-beta-sdk-dotnet#336]
It looks like for some reason the generator is not emitting the AddAsync method in some scenarios. 
For example, we can't use it in the scenario below:

```c#
var userSource = GraphServiceClient .Compliance.Ediscovery
                                                .Cases[eDiscoveryCase.Id]
                                                .SourceCollections[sourceCollection.Id]
                                                .CustodianSources
                                                .References
                                                .Request()
                                                .AddAsync(userSourceData);
```

**Expected behavior**
It's expected to have AddAsync method

**Client version**
Microsoft.Graph version 4.6+

**Comment by andrueastman** [comment]
According to [this](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/aa09c93658b984377a646ba046c9f63fd8a6a6e6/src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs#L227), for the method to be generated, one of the following rules needs to apply,

```cs
  /// 1. If a navigation property specifies "ContainsTarget='true'", it is self-contained. 
  ///    Generate a direct path to the item (ie "parent/child").
  /// 2. If a navigation property does not specify ContainsTarget but there is a defined EntitySet 
  ///    of the given type, it is a reference relationship. Generate a reference path to the item (ie "item/$ref").
  /// 3. If a navigation property does not have a defined EntitySet but there is a Singleton which has 
  ///    a self-contained reference to the given type, we can make a relationship to the implied EntitySet of 
  ///    the singleton. Generate a reference path to the item (ie "singleton/item/$ref").
  /// 4. If none of the above pertain to the navigation property, it should be treated as a metadata error.
```

Metadata also currently does not specify `ContainsTarget` as `true` and there is no Singleton/EntitySet in the service class for the `CustodianSource` type. 

In this specific scenario, it looks like this could potentially be metadata error.

**Comment by MIchaelMainer** [comment]
The fifth condition, let's call it 3.5, is: 

If a navigation property does not specify ContainsTarget==true, and does not have a defined top-level EntitySet/Singleton of the type for the navigation property, but there is a Singleton or EntitySet which has a ContainsTarget chain of navigation properties that result in containing the type of the initial navigation property, then generate a reference path to the item (ie "singleton/item/$ref").

This is a generator issue -- missing support for this scenario.

**Comment by mahage-msft** [comment]
Is there any work on the workload side here or is this in fact an issue with the SDK generator?  If just on the SDK side, would like to understand when we can expect this to be completed. I haven't had any customers report the issue yet, but I think it's just a matter of time and when the request comes it, it will likely come in very hot.

**Comment by andrueastman** [comment]
Hey @mahage-msft,
It seems the generator has an incorrect assumption as outlined [here](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/336#issuecomment-904406820), so we still need finish up on some investigation on whether allowing this will have unintended side effects. We will update on this further in the coming week.
