### ISSUE TITLE
Presence subscription fails

### ISSUE THREAD

**Issue by nikita-rostovskiy** [microsoftgraph/msgraph-beta-sdk-dotnet#352]
I'm not sure I should post it here but I don't know where it supposed to be.
I'm not using SDK to access beta endpoint but I send requests directly using HttpClient.SendAsync(). It worked perfectly but recently I started receive 500 Internal server error when try to create subscription on users presence. I send 1 request for all users I have (it's about 40-50 users) and I get such response like that. Previously I could receive such response when some user's account was deleted and it caused failure. And I updated my code to make it be able to handle such case.
But now I'm getting all users I have in such list. On the screen you can see that there are a lot of them. I can say that those list is exactly the same I send, so MS Graph API returns all users I try subscribe on as problematic users. 

Is there something I can do or there were some breaking changes that I missed?

![image](https://user-images.githubusercontent.com/62286781/137329118-e1880846-512e-44c6-9c0c-243054e5a089.png)

**Comment by nikita-rostovskiy** [comment]
Also I noticed that I get this error message if I send such request immediately after I deleted subscription. Even if I wait for a while I have to send that POST request several times to get 201 - Created response.

**Comment by ddyett** [comment]
Closing this older issue out.
