### ISSUE TITLE
Obsolete graphClient.Users.Request().GetAsync()

### ISSUE THREAD

**Issue by isKUL** [microsoftgraph/msgraph-beta-sdk-dotnet#353]
```
[Obsolete("")]
public virtual IGraphServiceUsersCollectionRequestBuilder Users { get; }
```
And
```
[Obsolete("")]
public virtual IUserRequestBuilder Me { get; }
```
Hi! What is suggested to use?

**Comment by andrueastman** [comment]
Hey @isKUL,

Thanks for raising this.

I suspect that there something up with the annotations applied to the metadata which we use to generate the SDK. 
We shall investigate this further and update you on the findings we make.
