### ISSUE TITLE
The requested operation requires an element of type 'Object', but the target element has type 'Array'

### ISSUE THREAD

**Issue by rubens-farias** [microsoftgraph/msgraph-beta-sdk-dotnet#369]
This exception is happening since Saturday (?):

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The requested operation requires an element of type 'Object', but the target element has type 'Array'.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.JsonDocument.TryGetNamedPropertyValue(Int32 index, ReadOnlySpan`1 propertyName, JsonElement& value)
```

 in these two code pieces (both of them are paging related, but I'm unsure is this is the root cause):

```
var assignments = await ropcContext
      .ServicePrincipals[config["AzurePrincipalId"]]
      .AppRoleAssignedTo
      .Request()
      .GetAsync();
```

and

```
var cases = await ropcContext
      .Compliance
      .Ediscovery
      .Cases
      .Request()
      .GetAsync();
```

Running Fiddler, I can see both HTTP requests coming through as 200 and with the relevant data:
![image](https://user-images.githubusercontent.com/2456804/140728715-e773c5b8-690a-4b7e-a78a-907178362483.png)

Both requests also run without issues on Graph Explorer:
![image](https://user-images.githubusercontent.com/2456804/140728898-ef84feee-edb2-4abd-abf3-ccca6ad20558.png)

This code runs fine using the same Graph package version, but this specific endpoint isn't paginated:
```
var appRoles = (await ropcContext
        .Applications[config["AzureApplicationId"]]
        .Request()
        .GetAsync())
    .AppRoles
    .ToList()
```

I'm using *Microsoft.Graph.Beta 4.19.0-preview*

**Comment by andrueastman** [comment]
Hey @rubens-farias, 

Thanks for raising this. 

To help us understand the issue better, are you also able to provide more information on the dotnet runtime and other changes made to the project?
Someone else reported a similar issue recently [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1158#issuecomment-958789462) and resolved it through reinstalling Visual Studio and any more information on your experience would be helpful for us to understand this better.

**Comment by rubens-farias** [comment]
* Created a brand new solution (Console, .Net Core 3.1)
* Added Microsoft.Graph.Beta 4.19.0-preview
* Added Newtonsoft.Json 13.0.1
* Copied that `RawAuthProvider` implementation from previous project

```
static async Task Main(string[] args)
{
    var ropcContext = new GraphServiceClient(
        new RawAuthProvider(
            tenantId        : "bbdff856-...", 
            clientId        : "f7121fa2-...", 
            clientSecret    : "...",
            userName        : "account@....onmicrosoft.com",
            password        : "...."));

    var assignments = await ropcContext
        .ServicePrincipals["a2ce8ef8-..."]
        .AppRoleAssignedTo
        .Request()
        .GetAsync();

    Console.WriteLine("Hello World!");
}
```

and now it is working; I've tried to run the old project but the problem still happening.

Lemme poke around a bit more

**Comment by rubens-farias** [comment]
More findings:
* Original application doesn't have a reference to Newtonsoft.Json, so I removed it and added the other ones:
  * Azure.Identity 1.5.0
  * Microsoft.EntityFrameworkCore.Cosmos 5.0.11
  * Microsoft.Extensions.Configuration.Json 5.0.0
  * Microsoft.Extensions.Logging.Console 5.0.0
  * Microsoft.Graph.Beta 4.19.0-preview
* Application takes a few seconds loading "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.20\System.Console.dll" but it continues.
* Looking at the debug output window: `Exception thrown: 'System.InvalidOperationException' in System.Text.Json.dll` but it continues

Was it there since the first execution?
* Reverted some changes back:
  * removed Azure.Identity 1.5.0
  * removed Microsoft.EntityFrameworkCore.Cosmos 5.0.11
  * removed Microsoft.Extensions.Configuration.Json 5.0.0
  * removed Microsoft.Extensions.Logging.Console 5.0.0
  * added Newtonsoft.Json 13.0.1
* `System.InvalidOperationException` still there;

As the exception was happening since the beginning, maybe it is just a matter of ignoring it. So:
* Visual Studio 2019, Exceptions Settings, "restore the list to the default settings"
* Original application runs ok

Well, it seems like we can like with it for now. Should I close this one?

**Comment by andrueastman** [comment]
Thanks @rubens-farias,

Closing this for now.  Feel free to create a new issue in case of anything else.

**Comment by rubens-farias** [comment]
About the long time loading assemblies, that could be fixed by checking Visual Studio 2019, Options, Debugging, General, Enable Just My Code
