### ISSUE TITLE
Is there a way to identify which permissions a Graph call requires except RTFM?

### ISSUE THREAD

**Issue by rubens-farias** [microsoftgraph/msgraph-beta-sdk-dotnet#377]
We're trying to ensure our current code have the all required Graph permissions.
Except for reading the documentation, is there a way to collect which permissions a particular endpoint requires?

Example: How can I "automagically" tell the `appRoleAssignments` endpoint requires `Application.Read.All`, `Directory.Read.All`, `Application.ReadWrite.All`, `Directory.ReadWrite.All` permissions, without reading [List appRoleAssignments granted to a service principal](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignments)?

Is this information publicly exposed in a standard format?

Thanks!

**Comment by Yomodo** [comment]
You should play around with the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer), it'll show the permissions needed:

![image](https://user-images.githubusercontent.com/10358198/184867157-5a2b43a4-c459-42cc-9798-a77877cf17c6.png)

**Comment by rubens-farias** [comment]
> You should play around with the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer), it'll show the permissions needed:
> 
Which is a kind of documentation ;)

My point is to quickly answer things like "what permissions do you need on your code?" and we somehow enlist all used Graph endpoints and, based on reflection or some other regular metadata, output what permissions they need.

**Comment by ddyett** [comment]
we are investigating ways to make permissions clearer but closing this particular issue now.
