### ISSUE TITLE
Got error when call to set photo for given user

### ISSUE THREAD

**Issue by fhlbdvt** [microsoftgraph/msgraph-beta-sdk-dotnet#388]
When using Microsoft.Graph.Beta version 4.14.0-preview to update a user photo, got the following error:

```
var result = await betaClient.Users[objectId].Photo.Content.Request().PutAsync(memoryStream);
// got error below
```
```
Microsoft.Graph.ServiceException : Code: UnknownError
Message: {
  "errorCode": "ErrorUserResolutionFailedUserDoesNotExist",
  "message": "Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileNotFoundException' was thrown.",
  "target": null,
  "details": null,
  "innerError": null,
  "instanceAnnotations": []
}
Inner error:
	AdditionalData:
	date: 2021-11-08T17:39:56
	request-id: 0f09b6c8-1149-4a68-9127-8dff4fe693a3
	client-request-id: 0f09b6c8-1149-4a68-9127-8dff4fe693a3
ClientRequestId: 0f09b6c8-1149-4a68-9127-8dff4fe693a3
```
and call to get user is successful:

```
var result = await betaClient.Users[objectId].Request().GetAsync();
// got result back
```

**Comment by zengin** [comment]
Hi @fhlbdvt,

Thanks for raising the issue and sorry for the late response.

This doesn't seem to be specific to the SDK. Please follow up in the Q&A here if the suggestions listed there don't work:

https://docs.microsoft.com/en-us/answers/questions/739192/errorprofilenotfound-exception-from-graph-api.html?msclkid=3426ee27bb8011eca9a8ee044442ea93

Other related threads:
https://stackoverflow.com/questions/67890426/microsoft-graph-user-photo-microsoft-fast-profile-core-exception-imagenotfou?msclkid=34264f0cbb8011ecb877bd7bc9e9244d

https://stackoverflow.com/questions/69726744/cannot-update-an-b2c-local-user-profile-photo-on-azure-portal-using-graph-with?msclkid=34268fbabb8011ec9c5b4f6b0a608ad1
