### ISSUE TITLE
Graph API ResetPassword doesn't work from Application

### ISSUE THREAD

**Issue by rmencia-isv** [microsoftgraph/msgraph-beta-sdk-dotnet#398]
Calling Graph API Beta from C# doesn't work. 
From C# using the code example I get the error below.
From Graph API Explorer I get Internal server error (See image below)

```
            var passwordResetResponse = await userService._graphServiceUsers["44444444-4444-4444-4444-4444444444"].Authentication
                .PasswordMethods["28c10230-6103-485e-b985-444c60001490"]
                .ResetPassword("@Password123!", null)
                .Request()
                .PostAsync();
```  

    Microsoft.Graph.ServiceException: Code: badRequest
    Message: {"error":{"code":"BadRequest","message":"UserPrincipalName value  in token was missing or invalid","innerError":{"request-id":"0a257088-1bf4-41f0-8774-9cf891bde3f4","date":"2022-02-11T00:06:02.409236Z"}}}
    Inner error:
    	Message: {"error":{"code":"BadRequest","message":"UserPrincipalName value  in token was missing or invalid","innerError":{"request-id":"0a257088-1bf4-41f0-8774-9cf891bde3f4","date":"2022-02-11T00:06:02.409236Z"}}}
    AdditionalData:
    	date: 2022-02-11T00:06:02
    	request-id: 0a257088-1bf4-41f0-8774-9cf891bde3f4
    	client-request-id: 0a257088-1bf4-41f0-8774-9cf891bde3f4
    ClientRequestId: 0a257088-1bf4-41f0-8774-9cf891bde3f4

  Stack Trace: 
    HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
    BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
    BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
    UserGraphServiceTest.ChangePasswordAsyncTest() line 34
    ThreadOperations.ExecuteWithAbortSafety(Action action)

FROM Graph Explorer
![image](https://user-images.githubusercontent.com/82075665/153521335-49ba105a-03de-4128-825e-856edef3e385.png)

**Comment by andrueastman** [comment]
Hey @rmencia-isv,

Thanks for raising this issue. 

I think the error below from the api might be suggesting that you should use the "UserPrincipalName" as the identifier for the user rather than the Id. This is usually in the form of an email address like `user@contoso.com`

```
Message: {"error":{"code":"BadRequest","message":"UserPrincipalName value  in token was missing or invalid","innerError":{"request-id":"0a257088-1bf4-41f0-8774-9cf891bde3f4","date":"2022-02-11T00:06:02.409236Z"}}}
```

Could you try changing the code to something like below to verify if it works out for you?

```cs
var passwordResetResponse = await userService._graphServiceUsers["user@contoso.com"].Authentication  // use the UPN of the user
                .PasswordMethods["28c10230-6103-485e-b985-444c60001490"]
                .ResetPassword("@Password123!", null)
                .Request()
                .PostAsync();
```

**Comment by rmencia-isv** [comment]
Hi @andrueastman,
I have already tried that and I get an error. It can't find the user. Anyhow, if seems strange that for some methods you would use the Id and the email for others. It would be inconsistent.

My Steps:

1. Go to B2C and I find my user
2. I copy the username (email)
3. I call that code with the email as suggested
4. User can't be found


**I find my user in B2C:**
![image](https://user-images.githubusercontent.com/82075665/153780442-e3d63f4a-e34c-4440-be40-c3941f711792.png)


**I use the same email:**
![image](https://user-images.githubusercontent.com/82075665/153780950-c5120926-fadf-4d23-8b80-9883cbb9f1ca.png)

![image](https://user-images.githubusercontent.com/82075665/153780505-bc563443-2576-4eea-a47c-fc3190f6c780.png)

**Comment by andrueastman** [comment]
Hey @rmencia-isv,

Thanks for the extra information.

Just to clarify, what authentication mechanism are you using to authenticate with Graph when making call? 
According to the docs [here](https://docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&tabs=http#permissions-acting-on-other-users), you would need to authenticate as the admin of the tenant when making the request and have the following delegated permissions:

- Directory.AccessAsUser.All - Required for changePassword
- UserAuthenticationMethod.ReadWrite.All - Required for resetPassword
