### ISSUE TITLE
key_ops is missing when adding a new policy key to the trustframework keysets

### ISSUE THREAD

**Issue by DaKevinH** [microsoftgraph/msgraph-beta-sdk-dotnet#412]
While using the graph api to add a new policy key to Azure AD B2C i noticed that the property key_ops is missing.

The following piece of code was used to add a key:
`var newKeySet = new TrustFrameworkKeySet
{
    Id = storageKeyId,
    Keys = new List<TrustFrameworkKey>()
    {
        new TrustFrameworkKey
        {
            K = ValueHere,
            Use = "sig",
            Kty = "oct",  
        }
    },
};
await _graphServiceClient.TrustFramework.KeySets.Request().AddAsync(newKeySet, cancellationToken);`
There is no property related to key_ops in the TrustFrameworkKey class so i tried to use the property called AdditionalData on the TrustFrameworkKeySet and TrustFrameworkKey classes.
When using the property like below on the TrustFrameworkKeySet the key is added to B2C but the property value is not in the json. While setting the property on the TrustFrameworkKey an exception occurs when calling AddAsync saying that the json isn't valid.
`AdditionalData = new Dictionary<string, object>()
{
    { "key_ops", new string[] {"sign" } }
}`

This is the output of the key added using the api:
`{
	"metadata": {
		"storageKeyId": "B2C_1A_Test",
		"updatedUtc": "3/9/2022 12:00:00 AM",
		"tenantID": "tenant.onmicrosoft.com"
	},
	"keys": [
		{
			"kid": "ValueHere",
			"use": "sig",
			"kty": "oct"
		}
	]
}`
When you add a policy key manually via the interface in Azure the property key_ops is added to the json.
This is the output of a manually added key:
`{
	"metadata": {
		"updatedUtc": "3/9/2022 12:00:00 AM",
		"tenantID": "tenant.onmicrosoft.com",
		"storageKeyId": "B2C_1A_Test"
	},
	"keys": [
		{
			"kid": "ValueHere",
			"use": "sig",
			"key_ops": [
				"sign"
			],
			"kty": "oct"
		}
	]
}`

**Comment by ddyett** [comment]
this appears to be a service issue we cannot assist with here. Closing since this issue is older
