### ISSUE TITLE
Inactive Custodian Not Adding Correctly

### ISSUE THREAD

**Issue by JoshuaSchmidt-Epiq** [microsoftgraph/msgraph-beta-sdk-dotnet#418]
I have been working with Microsoft on the AeD APIs for over a year.  Originally the API required placing a "." before an email address to signify it was an inactive user.  A change was made in the API to check passed email addresses so the "." was no longer required.  This worked and I have been able to add inactive custodians without issue.  About a month or two ago, inactive custodians began experiencing issues.  In some situations the custodian would be added as an Active user where other times the same user (different AeD case) would be added as Inactive.  In either case once the custodian is created, I am no longer able to add data sources to the custodian.

A couple weeks ago the AeD API was updated to include some OneAPI changes.   This further broke inactive custodians that they now displayed with a blank name.  This issue was fixed by the API team but I am still having the previous issues where Inactive custodians are not being added correctly.  The API team has come to the conclusion the issue is in the SDK not the API.

I am using VB.Net 2019 and my MSGraph library (Standard 2.0) is using the Beta 4.29 version.  I have a WinForm program (4.6.2) that references my MSGraph library.

The process I use to add custodians is as follows:

Pass 1:   I attempt to add a custodian
-If this returns successful I move to adding sources
Pass 2:   If Pass1 reports an I try to add the custodian again.  Basically I just re-try the call.  This was due to some custodians not correctly adding during the first attempt which I believe are due to buffer issues in the Graph API.
-If this returns successful I move on to adding sources
Pass 3:   If the previous to attempts failed I insert a “.” at the start of the email address.  This covers custodians which are actually inactive but were not identified as such by GSK.  Previously, I believe Microsoft had made a change to check for this so it should be caught by the first pass but my code still makes this last attempt.
-If this returns successful I move on to adding sources.  If this still returns an error, then I assume the custodian can’t be added and mark it as such.  No further work is done with this custodian.

The error reported is either:

MSGraph.AddCustodian : Code: NotFound
Message: Custodian not found
Inner error:
	AdditionalData:
	date: 2022-03-10T19:13:49
        ......

or

MSGraph.AddCustodian : Code: Conflict
Message: Custodian creation failed {"BatchResponses":[{"Id":"####","ErrorMessage":"Failed to create","ErrorCode":"BadRequest"}]}
Inner error:
	AdditionalData:
	date: 2022-03-10T19:14:01
        .....

The API team looked into the logs at Microsoft and found the following:

'https://substrate.office.com:444/complianceworkbench/compliance/ediscovery/cases('####')/custodians('userSources')'."
URI 'https://substrate.office.com:444/complianceworkbench/compliance/ediscovery/cases('####')/custodians('siteSources')'

Above request URI should be in format :  /custodians('id’)/userSources or /custodians('id’)/siteSources

This indicates the call begin made is not passing the correct CustodianID when adding sources.  We have verified my code IS passing the IDs in the correct manner but the actual web call is not being made correctly by the SDK.

It was suggested by the API team to update my SDK version.  I updated from 4.29 to 4.34.  In doing so I now get the following error when making any Graph Calls:

{"Only HTTP/1.0 and HTTP/1.1 version requests are currently supported." "Parameter name: value"

When I downgraded back to 4.29 the code works as normal.

**Comment by andrueastman** [comment]
> {"Only HTTP/1.0 and HTTP/1.1 version requests are currently supported." "Parameter name: value"

Hey @StefanieBier, @JoshuaSchmidt-Epiq.

Thanks for raising this. With regards to this error, are you able to share the runtime info of your environment (OS/Dotnet runtime version)? 
Also are you able to share how you are creating the `GraphServiceClient`?

**Comment by JoshuaSchmidt-Epiq** [comment]
I am a little confused by your question as it seems you did not read the entire message as this information is already in there.

I am using VB.Net 2019 and my MSGraph library (Standard 2.0) is using the Beta 4.29 version. I have a WinForm program (4.6.2) that references my MSGraph library.  All running on Windows 10 19041.1415

The "Only HTTP/1.0..." issue was something that popped up when I updated from SDK v4.29 but this is a minor issue compared with my larger issue related to adding inactive custodians which is the bulk of my message.

I need some people from Microsoft to look into this asap as this is part of a large ongoing project that I have been working directly with the AeD API team on for over a year.

**Comment by andrueastman** [comment]
Hey @JoshuaSchmidt-Epiq,

Apologies for this. I was hoping to first unblock you while using the latest SDK version to eliminate the possibility of it being an outdated version issue. 

However, with regards to the issue, are you able to share the code example you are using for this? Is it consistent with the examples provided [here](https://docs.microsoft.com/en-us/graph/api/ediscovery-custodian-post-sitesources?view=graph-rest-beta&tabs=csharp#request)? It would also be great if you could share the "client-request-id" from the failed request so that we can see if anything is amiss.

**Comment by andrueastman** [comment]
Thanks for this @JoshuaSchmidt-Epiq,

When I look up the request Id, the logs show that 404 response is returned. 
Furthermore, The URI generated seems to be consistent as seen below.

**Comment by andrueastman** [comment]
Hey @mahage-msft,

Any chance you could help figure out what could be going wrong with this request? The client error received seems to be inconsistent with the graph logs. 

> AdditionalData:
date: 2022-03-30T18:23:57
request-id: 4ac1ef84-4e2b-421e-8fed-2f90f167be28
client-request-id: 4ac1ef84-4e2b-421e-8fed-2f90f167be28

> Your logs should show something similar to the following which appears as though I am adding the site source to the Custodians collection not a specific custodian object:

> MSGraph.AddCustodianSiteSource : An Error Occured: PNDB_Sync_16//https://epiqsandbox-my.sharepoint.com/personal/MDrone_epiqsandbox_onmicrosoft_com

> MSGraph.AddCustodianSiteSource : Code: UnknownError
Message: {"Message":"No HTTP resource was found that matches the request URI '[https://substrate.office.com:444/complianceworkbench/compliance/ediscovery/cases('5d4c9c87-fbdc-4883-b971-16f14b710815')/custodians('siteSources')'.","MessageDetail":"No](https://substrate.office.com:444/complianceworkbench/compliance/ediscovery/cases('5d4c9c87-fbdc-4883-b971-16f14b710815')/custodians('siteSources')'.%22,%22MessageDetail%22:%22No) type was found that matches the controller named 'cases'."}

**Comment by StefanieBier** [comment]
@andrueastman MaHa's team has already triaged.

**Comment by mahage-msft** [comment]
@SeunginLyu - Can you follow up on this?

**Comment by SeunginLyu** [comment]
Previously we did below experiments to find that C# SDK and graph explorer both are working fine for our Apis for adding sitesources to custodian.

**We suspect it is VB.net SDK generation issue.** Can you check if your SDK version is greater than or equal to our SDK experiment version.

Also if you can use C# SDK and see if it works.

Experiments:
1.	We tried from graph explorer for test tenant in same region and it is working. Public Documentation [https://docs.microsoft.com/en-us/graph/api/ediscovery-custodian-post-sitesources?view=graph-rest-beta&tabs=http](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fgraph%2Fapi%2Fediscovery-custodian-post-sitesources%3Fview%3Dgraph-rest-beta%26tabs%3Dhttp&data=04%7C01%7CSeungin.Lyu%40microsoft.com%7C9ea201ff27894177e65708da08979764%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637831744519214676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZZ5CHTrvkP75nrXjfS8wJb5VQ%2BTvxA2CleUT%2B21Drp4%3D&reserved=0)
2.	We tried to add siteSource in custodian using below C# code and it is working.

Graph SDK Nuget Version: 4.32.0-preview
Newtonsoft.Json: 13.0.1
Azure.Identity: 14.0

var siteSource = new SiteSource
            {
                AdditionalData = Utils.GetSiteAdditionalData(siteUrl),
            };

GraphServiceClient.Compliance.Ediscovery
                            .Cases[eCase.Id]
                            .Custodians[custodian.Id]
                            .SiteSources.Request()
                            .AddAsync(siteSource).Result;

public class Utils
    {
        public static Dictionary<string, object> GetSiteAdditionalData(string siteUrl)
        {
            Dictionary<string, object> additionalData = new Dictionary<string, object>();
            additionalData.Add("site", new { webUrl = $"{siteUrl}" });
            return additionalData;
        }
}

**Comment by JoshuaSchmidt-Epiq** [comment]
I am currently using 4.36 and still having the issue.

I believe this is expected behavior, but I have noticed the Custodian ID for all active users is an alphanumeric sequence, but the inactive custodians appear to just be numeric only.  This appears to be true when adding the inactive custodians through either the SDK or UX.  I point it out only as it may pertain to some sort of validation checking that may be occurring in the SDK perhaps?


Joshua Schmidt

Epiq | Forensic Senior Consultant

Office: +1 213 892 9000

Mobile: +1 530 209 6979
***@***.******@***.***>

________________________________

**Comment by andrueastman** [comment]
> I point it out only as it may pertain to some sort of validation checking that may be occurring in the SDK perhaps?

The SDK doesn't perform this validation. But builds the requests based on input parameters and makes the call to the API. 

> AdditionalData:
date: 2022-03-30T18:23:57
request-id: 4ac1ef84-4e2b-421e-8fed-2f90f167be28
client-request-id: 4ac1ef84-4e2b-421e-8fed-2f90f167be28

@SeunginLyu Any chance you are able to look up the requestId provided by @JoshuaSchmidt-Epiq from your end to confirm that the error is indeed a 404 and not an incorrect URI being built as the error returned to the client suggests?

**Comment by SeunginLyu** [comment]
> > I point it out only as it may pertain to some sort of validation checking that may be occurring in the SDK perhaps?
> 
> The SDK doesn't perform this validation. But builds the requests based on input parameters and makes the call to the API.
> 
> > AdditionalData:
> > date: 2022-03-30T18:23:57
> > request-id: 4ac1ef84-4e2b-421e-8fed-2f90f167be28
> > client-request-id: 4ac1ef84-4e2b-421e-8fed-2f90f167be28
> 
> @SeunginLyu Any chance you are able to look up the requestId provided by @JoshuaSchmidt-Epiq from your end to confirm that the error is indeed a 404 and not an incorrect URI being built as the error returned to the client suggests?

Regarding this 404, Advanced eDiscovery logs are indicating that the site source 
"epiqsandbox-my.sharepoint.com:/personal/adelev_epiqsandbox_onmicrosoft_com" doesn't exist.
@JoshuaSchmidt-Epiq could you double check the above finding is correct? Could it be an error in your code constructing the site URL?

**Comment by JoshuaSchmidt-Epiq** [comment]
That is fine if the OneDrive does not exist.  That is certainly possible given this is an inactive custodian, but I am not able to add the mailbox either.  This is true for all the inactive custodians in my tenant.


Joshua Schmidt
Epiq | Forensic Senior Consultant
Mobile: +1 530 209 6979
***@***.******@***.***>

**Comment by SeunginLyu** [comment]
Summarizing the discussion & issues so far : 

- SDK v4.29 : SDK not passing the correct CustodianID for inactive custodians
      - 'https://substrate.office.com:444/complianceworkbench/compliance/ediscovery/cases('####')/custodians('userSources')'."
     URI 'https://substrate.office.com:444/complianceworkbench/compliance/ediscovery/cases('####')/custodians('siteSources')'
       - Above request URI should be in format : /custodians('id’)/userSources or /custodians('id’)/siteSources
        - This indicates the call begin made is not passing the correct CustodianID when adding sources.
- SDK v4.34 : {"Only HTTP/1.0 and HTTP/1.1 version requests are currently supported." "Parameter name: value"
- SDK v4.36: Http error from 4.34 gone, but still not able to mailboxes/site sources to inactive custodians.
    -  @andrueastman @JoshuaSchmidt-Epiq eDiscovery team is investigating and looking into the logs for this issue as of 4/5
    - @maisarissi for FYI

**Comment by SeunginLyu** [comment]
@JoshuaSchmidt-Epiq, meanwhile I see v.4.37 has just been released, could you update the SDK to this version and try again?

SDK v4.37: [NuGet Gallery | Microsoft.Graph.Beta 4.37.0-preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/4.37.0-preview)

**Comment by maisarissi** [comment]
@JoshuaSchmidt-Epiq version 4.40 was released 2 days ago. Can you validate?

Also, there is a new version of the SDK out, 5.x. You can check for information [here](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/421).

**Comment by maisarissi** [comment]
Per my last conversation with @SeunginLyu , the eDiscovery team has fixed this.

Closing this.
