### ISSUE TITLE
Try out the v5 preview 📢 📢 

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-beta-sdk-dotnet#421]
The Microsoft Graph .NET SDK v5.0.0 is now available for [preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.0.0-preview)!

This updated version features many changes as the SDK is generated with [Kiota](https://microsoft.github.io/kiota/):

You can go to the [upgrade guide](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md) for more detailed information on the changes. 
 
Alongside all the changes mentioned in the upgrade guide above, for the beta SDK, everything was moved from Microsoft.Graph namespace to Microsoft.Graph.Beta.

**Comment by andrueastman** [comment]
Hey @MichelZ,

We're planning to target netstandard 2.0. Progress on this will be tracked via https://github.com/microsoft/kiota-abstractions-dotnet/issues/12

**Comment by thomas-illiet** [comment]
Hello @andrueastman,  this new implementation is good news i think :)
do you know if kiota will implement interfaces in order to create more flexibility and generic classes ? because currently all the classes are independent...

**Comment by thomas-illiet** [comment]
Hello @andrueastman, do you have an idea to help you to provide up-to-date microsoft documentation.
( Process / Pull Request / etc....)

> Because all Microsoft documentation is based on the V4.

**Comment by andrueastman** [comment]
Thanks for the feedback and trying out the preview everyone.
We'll close this issue and track any new issues raised by creating new issues on the repo.

Thanks again!
