### ISSUE TITLE
When  a columnDefinition is created or updated, the displayname is not visible in SharePoint

### ISSUE THREAD

**Issue by MartienJacobs1960** [microsoftgraph/msgraph-beta-sdk-dotnet#432]
Hi

I'm using msGraph version 4.38

When I create a ColumnDefinition with:
Name: EOL_FiscalYear
DisplayName: **Year**

The name displayed in SharePoint is **EOL_FiscalYear**.
If you change this in SharePoint to **Years** and then check this in msGraph, the DisplayName is **Years.**
If you change this in msGraph to **Year** it is still displayed as **Years** in Sharepoint 

How can we get this to work, or what are we doing wrong

**Comment by andrueastman** [comment]
Hey @MartienJacobs1960,

Thanks for raising this. 
Are you able to share code samples of how you are making the call to MSGraph to update the columnDefinition? Also, if you query the columnDefinition with MSGraph after updating is the value still the same?

**Comment by MartienJacobs1960** [comment]
[MsGraph_Columns.zip](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/files/8588778/MsGraph_Columns.zip)
Hereby a small extract of my code. If you fill in the 
- clientid
- tenantid
- clientsecret
- an existing site-id
you can execute and follow what I 'm doing.

A small notice.
For this small extract I used anonther site-id and was wondered because here all works fine.
Filled in the 'original' test site-id and still it goes wrong on this site.

I have no clue where to look.

Best regards
Martien Jacobs

**Comment by MartienJacobs1960** [comment]
I mentioned Description but most of all it is the DispalyName

**Comment by andrueastman** [comment]
Hey @MartienJacobs1960,

I believe the response should have the updated values of the column definition. 

are you able to change this line of code 

```cs
                await graphClient
                    .Sites[clientSpSiteDriveId]
                    .Lists[rootList.Id]
                    .Columns
                    .Request()
                    .AddAsync(column);
```

to 

```cs
                Console.WriteLine("Display name sent : "+column.DisplayName);
                var columnDef = await graphClient
                                    .Sites[clientSpSiteDriveId]
                                    .Lists[rootList.Id]
                                    .Columns
                                    .Request()
                                    .AddAsync(column);

                Console.WriteLine("Display name response : " + columnDef.DisplayName);
```

so that we may verify the nature of the response from the API?

**Comment by MartienJacobs1960** [comment]
I created a new site.
Created my columns
Started GraphExplorer and executed the following api
https://graph.microsoft.com/beta/Sites/jacobs60aa.sharepoint.com,90880c21-2d07-4233-87b6-ebf222ab7cae,1006f766-8bec-4c21-a458-01cceefbcd71/lists/589221bc-00b9-48bb-90a5-888040690caa/columns
One of them had the following result:
{
            "columnGroup": "Aangepaste kolommen",
            "description": "",
            "displayName": "Taak",
            "enforceUniqueValues": false,
            "hidden": false,
            "id": "3a86a691-4c3a-4e34-8cae-1a163f4add5e",
            "indexed": false,
            "name": "EOL_TaskName",
            "readOnly": false,
            "required": false,
            "text": {
                "allowMultipleLines": false,
                "appendChangesToExistingText": false,
                "linesForEditing": 0,
                "maxLength": 128
            }
        }

I changed the (display)name in SharePoint to "Taak2"

Started GraphExplorer and executed the api again
I still saw the same result.

I executed the following api
https://graph.microsoft.com/v1.0/Sites/jacobs60aa.sharepoint.com,90880c21-2d07-4233-87b6-ebf222ab7cae,1006f766-8bec-4c21-a458-01cceefbcd71/lists/589221bc-00b9-48bb-90a5-888040690caa/columns
The result is now:
{
            "columnGroup": "Aangepaste kolommen",
            "description": "",
            "displayName": "Taak2",
            "enforceUniqueValues": false,
            "hidden": false,
            "id": "3a86a691-4c3a-4e34-8cae-1a163f4add5e",
            "indexed": false,
            "name": "EOL_TaskName",
            "readOnly": false,
            "required": false,
            "text": {
                "allowMultipleLines": false,
                "appendChangesToExistingText": false,
                "linesForEditing": 0,
                "maxLength": 128
            }
        }

is there a difference between the v1.0 and the beta version.

Best regards
Martien Jacobs

Op wo 4 mei 2022 om 10:23 schreef Eastman ***@***.***>:

**Comment by ddyett** [comment]
closing older issues. please file a new issue if occurs with latest versions.
