### ISSUE TITLE
Property Hidden of ColumnDefinition vs Hide/Unhide in SharePoint

### ISSUE THREAD

**Issue by MartienJacobs1960** [microsoftgraph/msgraph-beta-sdk-dotnet#433]
Hi

I'm using MS Graph version 4.38

When I create a ColumnDefinition in MS Graph and make this column hidden, it doesn't show up when collecting all columns. Because we don't store the id of the field, I can only access it by name. But it doesn't appear in a collection. If you want to create it again it tells you that it already exists. If the column is hidden it isn't shown at all in SharePoint, so you can't hide or unhide this column.
If you have a column which is not hidden. It is visible in SharePoint and you can hide or unhide it. But you don't see any difference in properties in MS Graph. It seems to be a feature which only can be used in the front end of SharePoint.

Our questions is: 
1. do we see this correctly?
2. How can I hide/unhide columns in SharePoint as if it is done from within SharePoint.

**Comment by andrueastman** [comment]
Any chance you tried modifying the `hidden` property of the column like in the http example?

https://learn.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-1.0#request
