### ISSUE TITLE
Passing a `client-request-id` in every Graph API call

### ISSUE THREAD

**Issue by rubens-farias** [microsoftgraph/msgraph-beta-sdk-dotnet#435]
Per [Best practices for working with Microsoft Graph](https://docs.microsoft.com/en-us/graph/best-practices-concept#reliability-and-support):

> ### Reliability and support
> 
> To ensure reliability and facilitate support for your application:
> (...)
>- Generate a unique GUID and send it on each Microsoft Graph REST request. This will help Microsoft investigate any errors more easily if you need to report an issue with Microsoft Graph.
>   - On every request to Microsoft Graph, generate a unique GUID, send it in the client-request-id HTTP request header, and also log it in your application's logs.
>   - Always log the request-id, timestamp and x-ms-ags-diagnostic from the HTTP response headers. These, together with the client-request-id, are required when reporting issues in [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/m365#microsoft-graph) or to Microsoft Support.

That said, how to inject some behavior in the `GraphServiceClient` instance to always insert the proper request header?
We're using the version 4.38 beta.

**Comment by ddyett** [comment]
closing older issues. please file a new issue if occurs with latest versions.
