### ISSUE TITLE
Cannot run along side the non beta in .Net 6

### ISSUE THREAD

**Issue by fernando-almeida** [microsoftgraph/msgraph-beta-sdk-dotnet#451]
Hi all,
I believe this may not be the most suited place to ask this but since this is somewhat partially documented in the main README I was going to ask for some concrete minimal sample C# project that is able to compile with both Microsoft.Graph and Microsoft.Graph.Beta packages.
I've followed what I could understand from the **extern alias strategy** mentioned in the main README to no avail.
I can't get the project to compile. I keep getting the errors transcribed below which I'd expect not to occur given that the explicit usage of the extern alias is required whenever I want to reference Microsoft.Graph.Beta types.

error CS7069: Reference to type 'ICollectionPage<>' claims it is defined in 'Microsoft.Graph.Core', but it could not be found
error CS7069: Reference to type 'IBaseRequest' claims it is defined in 'Microsoft.Graph.Core', but it could not be found
error CS7069: Reference to type 'IBaseRequestBuilder' claims it is defined in 'Microsoft.Graph.Core', but it could not be found 

Thanks in advance for any help.

**Comment by zengin** [comment]
Hi @fernando-almeida,

Thanks for raising this issue. We are using the approach described in the README in another project with .NET 6.

Relevant lines:

csproj:
https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/f0122f76dcd6e61f404517495ab4e7250af10ead/TestsCommon/TestsCommon.csproj#L44-L48

extern alias:
https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/f0122f76dcd6e61f404517495ab4e7250af10ead/TestsCommon/MicrosoftGraphCSharpCompiler.cs#L1

line where beta package is consumed:
https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/f0122f76dcd6e61f404517495ab4e7250af10ead/TestsCommon/MicrosoftGraphCSharpCompiler.cs#L87

Please let us know if this solves your problem. If not, I can work on extracting it to a minimal sample.

Thanks!

**Comment by zengin** [comment]
@fernando-almeida Since you have raised another issue (#452) regarding the beta package generated by Kiota, this issue might be due to the different core dependencies coming from v1 and beta. Could you share which v1 and beta package versions you want to work with?

cc: @andrueastman

**Comment by fernando-almeida** [comment]
Hi @zengin,
thanks for the quick reply.
I can confirm the issue is circumscribed to versions 5.*.*.
I've successfully downgraded to latest major (4.41.0) and I'm now able to compile and execute the code.
I'm seeing other errors atm with some weird messages (eg. Resource not found and Bad requests) when pushing application extension properties and custom security attributes but most likely those are permissions-related and/or related with something I'm missing when setting the payload via the provided model.
Since this graph beta SDK version now more properly exposes exception messages I'll address these individually.

**Comment by zengin** [comment]
@fernando-almeida Glad to hear that your issue is resolved.

It looks like we won't need aliasing with kiota because Beta types are already under `Microsoft.Graph.Beta` namespace.
