### ISSUE TITLE
Provide accurate samples and eventually fix buggy resource patch requests 

### ISSUE THREAD

**Issue by fernando-almeida** [microsoftgraph/msgraph-beta-sdk-dotnet#452]
Hi all,

The current documentation in Microsoft Graph API official pages seems out of sync with the current generated code at least with respect to patch/update operations (eg. [update users](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&tabs=csharp)).

The code for updating a user in v1.0 which is "copied" to beta docs is incorrect as the Request() method does not seem exist.
```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var user = new User {
	BusinessPhones = new List<String>() { "+1 425 555 0109" }, 
        OfficeLocation = "18/2111"
};

await graphClient.Users["{user-id}"]
	.Request()
	.UpdateAsync(user);
```

From what I was able to understand from the current Graph SDK beta code as generated from Kiota it seems like the following "pattern" should be used instead.
```
GraphServiceClient graphClient = new GraphServiceClient( ... );

var userUpdateData = new User {
	BusinessPhones = new List<String>() { "+1 425 555 0109" }, 
        OfficeLocation = "18/2111"
};

var updateRequest = graphClient.Users["{user-id}"]
	.CreatePatchRequestInformation(userUpdateData);

await _graphServiceClient.RequestAdapter.SendNoContentAsync(updateRequest);
``` 

The above code does not only work but the exception triggered does not expose any meaningful information about the error returned by the API. After creating a custom response handler I was able to infer that I was getting an error message that loosely resembles the below.

The @odata.context URL "https://graph.microsoft.com/beta/$metadata#users/$entiy was not found
 
Once again it would be very helpful to get proper guidance/documentation for this.
At the moment, I find myself having to push some custom security attributes to users in AAD and it looks like I'll need to craft a JSON payload manually using a separate HTTP client. 

Thanks in advance for any help on this.

**Comment by andrueastman** [comment]
Hey @fernando-almeida,

Thanks for raising this issue. 

At the moment, Kiota generated SDKs are still in preview and have the version pattern of "5.x.x". You can find information about the Kiota based SDK [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md) and we are taking feedback on the pinned issues [here ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1290)and [here](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/421).

At the moment samples in the documentation provide samples for the current stable version of the SDKs (with version pattern 4.x.x) and we are working towards adding the new version samples as well. 

In your scenario, you should be able to update a user as below, any chance this works out?

```cs
var user = new User {
	BusinessPhones = new List<String>() { "+1 425 555 0109" }, 
        OfficeLocation = "18/2111"
};

await graphClient.Users["{user-id}"]
	.PatchAsync(user);
```

**Comment by fernando-almeida** [comment]
Hi @andrueastman,

Thanks for the quick reply.
For some reason I can't explain atm the PatchAsync was not showing up in IntelliSense but I've confirmed it's present in the latest 5.3.0-preview. Regardless I'm still unable to use this version along with Microsoft.Graph latest.

After some digging, I believe this is related with the PageIterator abstraction which seems to rely on different versions of Microsoft.Graph.Core (2.0.8 and 3.0.0) respectively.

**Comment by andrueastman** [comment]
Hey @fernando-almeida,

Just to confirm when you say `Microsoft.Graph` latest do you mean version `4.x.x`? 
If you wish to use the v1.0 and beta libraries together, you will need to make sure they are both of the same version pattern (i.e. 4.x.x for the current stable versions and 5.x.x for the kiota versions).

**Comment by fernando-almeida** [comment]
Hi @andrueastman,

Ok, I did not make that connection so thanks for making that explicit. Ultimately, it makes sense and I should have looked up Nuget preview versions for Microsoft.Graph.
So if were to target the pair [Microsoft.Graph 5.0.0-preview.4](https://www.nuget.org/packages/Microsoft.Graph/5.0.0-preview.4) with [Microsoft.Graph.Beta/5.3.0](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.3.0-preview) using the external alias that should work. Thanks for making that explicit. Regardless, I'd suggest making an explicit reference to that in the README just in case. Perhaps a non-advanced programmer may struggle to find the implicit connection with regards to the Semver conventions being followed across projects.
Once again, thanks again for all your quick and insightful help.
