### ISSUE TITLE
Remove aliasing instructions from README once SDK is released from kiota

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-beta-sdk-dotnet#453]
> It looks like we won't need aliasing with kiota because Beta types are already under `Microsoft.Graph.Beta` namespace.

_Originally posted by @zengin in https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/451#issuecomment-1127979204_

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/511
