### ISSUE TITLE
The SDK does not provide an interface/solution to create a generic repository/class

### ISSUE THREAD

**Issue by thomas-illiet** [microsoftgraph/msgraph-beta-sdk-dotnet#456]
``Hello Guys,

Currently I'm using v4 to retrieve information from microsoft azure, and I'm using reflection heavily to minimize code smelt/deduplication ( is not the best solution I think).

In V5 the reflection is much harder, because each class now has even less generic method.

Exemple to retrieve first collection page of teams element:

```csharp
// => var teamCollection = await graphClient.Teams
var clientType = typeof(GraphServiceClient);
var clientProperty = clientType.GetProperty("Teams");
var clientValue = clientProperty.GetValue(MYGRAPHCLIENT);
// => var teamCollection = await graphClient.Teams.GetAsync(null, null, CancelleationToken.None)
var getMethodInfo = clientValue.GetType().GetMethod("GetAsync");
var getTaskResult = (Task)getMethodInfo.Invoke(clientValue, new object[] {null, null, CancellationToken.None});
await getTaskResult.ConfigureAwait(false);
var resultProperty = getTaskResult.GetType().GetProperty("Result");
var getResult = resultProperty.GetValue(getTaskResult);
// => teamsCollection.Value
var valueProperty = getResult.GetType().GetProperty("Value");
var valueResult = valueProperty.GetValue(getResult) as List<Team>;
```

And if i want to add request configuration the process is mush muuush harden..
because the namespace is totaly named... without interface for generic implementation
```csharp
var query = new Microsoft.Graph.Beta.Teams.TeamsRequestBuilder.TeamsRequestBuilderGetRequestconfiguration();
```

Can you add an interface implementation in your project to easily use this SDK for a generic class implementation?

Kind regards
Thomas

**Comment by andrueastman** [comment]
Hey @thomas-illiet,

Thanks for trying out the new preview version.

Any chance you could share a sample of the v4 code as well to help us understand the change in process using the reflection and what duplication is avoided?

For extra context, we have fewer interfaces now to optimize the library binary size in the newer version limited to the base classes and your example is the equivalent of

```cs
        var teamCollection = await graphServiceClient.Teams.GetAsync();
        var valueResult = teamCollection.Value;
```

which can also be done as

```cs
        var requestInformation = graphServiceClient.Teams.CreateGetRequestInformation();
        var teamCollection = await graphServiceClient.RequestAdapter.SendAsync<TeamCollectionResponse>(requestInformation,TeamCollectionResponse.CreateFromDiscriminatorValue);
        var values = teamCollection.Value;
```

**Comment by thomas-illiet** [comment]
Hello @andrueastman

I'm using similar code between v4 and v5, major change is in queryable methods ( Select / Filter / Expand / etc.. )
in V4 the reflection is relatively easy because the methods are in the base of each entity class.

> Simple exemple :
```csharp 
var message = await graphClient.UnknowEntity
    .Request()
    .Filter("Id eq 4b87594d-b3e4-4e78-b756-5b4f06875482 )
    .Select("displayName,givenName,postalCode,identities")
    .Expand("extensions($filter=id%20eq%20'Microsoft.OutlookServices.OpenTypeExtension.Com.Contoso.Referral')")
    .GetAsync();
```

In V5 all the query methods should be sended to the `GetAsync`  method with `IAction` implementation.
This implementation prevents me to use reflexion methods because each entity class have inner query class to set the filters, so I can't make this generic probably due to a lack of experience in [Inception ](https://en.wikipedia.org/wiki/Inception) fonctionnality 😪

I need this to avoid have code-deduplication, because my product use same logic on all target entity ( user/computer/group/teams) to execute full sync or delta sync.
> When I look at `EntityFramework` or another FORM, globally it uses a separate method to add IQueryable order

**Comment by thomas-illiet** [comment]
Hey @andrueastman Do you have any information/help regarding this request ?

**Comment by andrueastman** [comment]
Hey @thomas-illiet,

If I understand correctly, the main issue is around setting the Query parameters in a generic way and you wish to get set them in a way that does not involve duplication of the code setting the Query parameters. Yes?

What are your thoughts regarding doing something like this on V5?

```cs
var requestInfo = graphClient.Teams.CreateGetRequestInformation();
//var requestInfo = graphClient.Users.CreateGetRequestInformation();

SetQueryParameters(requestInfo);
var teamCollection = await graphClient.RequestAdapter.SendAsync<TeamCollectionResponse>(requestInfo,TeamCollectionResponse.CreateFromDiscriminatorValue);
var values = teamCollection.Value;
```

Where `SetQueryParameters` is defined as

```cs
private void SetQueryParameters(RequestInformation requestInformation)
{
    requestInformation.QueryParameters.Add("$filter","Id eq 4b87594d-b3e4-4e78-b756-5b4f06875482");
    requestInformation.QueryParameters.Add("$select","displayName,givenName,postalCode,identities");
    requestInformation.QueryParameters.Add("$expand","extensions($filter=id%20eq%20'Microsoft.OutlookServices.OpenTypeExtension.Com.Contoso.Referral')");
}
```

Also, any chance you could also share how the reflection code looks like in V4?

**Comment by thomas-illiet** [comment]
Hooo thanks for this example, yes I will share my reflection code when I have my work computer :)
