### ISSUE TITLE
[Client bug]: ConnectedOrganizationMembers and SingleUser types missing from Microsoft.Graph.Beta 5.5.0-preview7

### ISSUE THREAD

**Issue by cgontario** [microsoftgraph/msgraph-beta-sdk-dotnet#469]
**Describe the bug**
The ConnectedOrganizationMembers and SingleUser types are missing from Microsoft.Graph.Beta 5.5.0-preview7. Both of these types are present in 4.x preview libraries and are required when interacting with Entitlement Management.

The summary on the AccessPackageAssignmentPolicy.RequestorSettings.AllowedRequestors property even refers to these types:

```
/// <summary>The users who are allowed to request on this policy, which can be singleUser, groupMembers, and connectedOrganizationMembers.</summary>
```

After poking around a bit more it seems that there are even more missing types. See Microsoft.Graph.Beta.Models.ApprovalStage.EscalationApprovers and .PrimaryApprovers:

```
/// <summary>The users who will be asked to approve requests. A collection of singleUser, groupMembers, requestorManager, internalSponsors and externalSponsors. When creating or updating a policy, include at least one userSet in this collection.</summary>
```

Missing types for the milk carton:

- SingleUser
- GroupMembers
- RequestorManager
- InternalSponsors
- ExternalSponsors

**Client version**
- Microsoft.Graph.Core 3.0.0-preview7
- Microsoft.Graph.Beta 5.5.0-preview

**Desktop (please complete the following information):**
- OS: Windows 10
- Version 21H2
- Visual Studio 17.2.3

**Comment by andrueastman** [comment]
Thanks for your patience on this one and trying out the new preview version.

With the changes made in the conversion library via https://github.com/microsoft/OpenAPI.NET.OData/pull/238, the latest update of [5.8.0-preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.8.0-preview) should now contain the missing types listed.

> - SingleUser
> - GroupMembers
> - RequestorManager
> - InternalSponsors
> - ExternalSponsors
