### ISSUE TITLE
Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by Vevish** [microsoftgraph/msgraph-beta-sdk-dotnet#470]
Unable to authenticate with certificate Microsoft.Graph.Beta, The code is working perfectly with the Microsoft.Graph but not with beta, 
problem is we are trying to use  below which is not available in the non beta version. Tried removing the Microsoft.Graph also does not 
help. Is there a different way to authenticate using the certificate with Graph beta, seems changed in Beta

await graphServiceClient.Reports.CredentialUserRegistrationDetails.GetAsync();

```
<package id="Microsoft.Graph" version="5.0.0-preview.6" targetFramework="net472" />
  <package id="Microsoft.Graph.Beta" version="5.5.0-preview" targetFramework="net472" />
  <package id="Microsoft.Graph.Core" version="3.0.0-preview.8" targetFramework="net472" />
  <package id="Microsoft.Identity.Client" version="4.44.0" targetFramework="net472" />
```

```
==============================================================
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.Kiota.Abstractions.ApiClientBuilder.EnableBackingStoreForParseNodeRegistry(ParseNodeFactoryRegistry registry)
   at Microsoft.Kiota.Abstractions.ApiClientBuilder.EnableBackingStoreForParseNodeFactory(IParseNodeFactory original)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.EnableBackingStore(IBackingStoreFactory backingStoreFactory)
   at Microsoft.Graph.Beta.BaseGraphServiceClient..ctor(IRequestAdapter requestAdapter, IBackingStoreFactory backingStore)
   at Microsoft.Graph.Beta.GraphServiceClient..ctor(TokenCredential tokenCredential, IEnumerable`1 scopes)
==============================================================
```

```cs
using Azure.Identity;
using Azure.Core;
using Microsoft.Graph.Core;
using m365library.Models;
using m365library.Worker;
using Microsoft.Graph.Beta;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.Graph.Beta.Models;


     certificate = certs[0];

            var credential = new ClientCertificateCredential(tenantId, clientId, certificate);

            string[] scopes = { "https://graph.microsoft.com/beta" };
                      


            try
            {

                GraphServiceClient graphServiceClient = new GraphServiceClient(credential, scopes);

            }
            
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                Console.ReadLine();
            }

```

**Comment by andrueastman** [comment]
Hey @Vevish,

Thanks for raising this.

Any chance you can confirm this is still replicable in [5.6.0-preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.6.0-preview) package?

**Comment by Vevish** [comment]
> 

Thanks same issue with 5.6.0

**Comment by andrueastman** [comment]
This is replicable in client running versions before .Net 5. https://github.com/dotnet/runtime/pull/34667

https://github.com/microsoft/kiota-abstractions-dotnet/pull/24 has been authored to address this from the abstractions library

**Comment by Vevish** [comment]
Hi 

> This is replicable in client running versions before .Net 5. [dotnet/runtime#34667](https://github.com/dotnet/runtime/pull/34667)
> 
> [microsoft/kiota-abstractions-dotnet#24](https://github.com/microsoft/kiota-abstractions-dotnet/pull/24) has been authored to address this from the abstractions library

Hi Andru
What is the fix ?

**Comment by andrueastman** [comment]
Hey @Vevish,
Fow now you can add the [latest](https://www.nuget.org/packages/Microsoft.Kiota.Abstractions/1.0.0-preview.9) version of abstractions library as a direct reference to your project file. 
The next update of the beta package should have this dependency included. 

```xml
<PackageReference Include="Microsoft.Kiota.Abstractions" Version="1.0.0-preview.9" />
```
