### ISSUE TITLE
[Client bug]: QueryParameters are not taken into account when constructing raw request in v5

### ISSUE THREAD

**Issue by gaspik** [microsoftgraph/msgraph-beta-sdk-dotnet#471]
**Describe the bug**
When constructing raw requests using CreateGetRequestInformation, added QueryParameters are ignored when requet is issued. Raw request is needed for example for batch operations.

Example code constructed based on comments in https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/456

**To Reproduce**
Construct GET query on Message, add QueryParameters for expand and select. Example code:

```
var request = GraphServiceClient.Me
  .Messages[message.Id]
  .CreateGetRequestInformation();

request.QueryParameters.Add("$expand", attachments($select=microsoft.graph.fileAttachment/contentId,microsoft.graph.fileAttachment/contentLocation,id,isInline,contentType,name,size),singleValueExtendedProperties($filter=id eq 'Integer 0x1081' or id eq 'SystemTime 0x1082' or id eq 'Boolean {64d160e0-0111-4da7-9e7c-9f148707552c} Name WatchForReplyNotifyWhenReplied' or id eq 'SystemTime {64d160e0-0111-4da7-9e7c-9f148707552c} Name WatchForReplyNotifyWhenNotReplied' or id eq 'SystemTime {64d160e0-0111-4da7-9e7c-9f148707552c} Name Snooze' or id eq 'String {64d160e0-0111-4da7-9e7c-9f148707552c} Name Notes')");
request.QueryParameters.Add("$select", "*,singleValueExtendedProperties,internetMessageHeaders");

var msg = await GraphServiceClient.RequestAdapter.SendAsync<Message>(request, Message.CreateFromDiscriminatorValue, cancellationToken: cancellationToken);
```

This issues following GET request (captured via fiddler):
```
GET https://graph.microsoft.com/beta/me/messages/AQMkADAwATM3ZmYAZS0yYTAwAC00ZTAxLTAwAi0wMAoARgAAA7sYNSO4MmVGvv0O5md362YHACqfHCJhb1FMk6LAHCC2JdwAAAIBDAAAACqfHCJhb1FMk6LAHCC2JdwAAiZDIREAAAA%3D HTTP/1.1
Host: graph.microsoft.com
Accept: application/json
User-Agent: eMClient/9.2.120.0
Authorization: Bearer ValidOAuthToken
FeatureFlag: 00000056
Accept-Encoding: gzip, deflate
```

**Expected behavior**
$select and $expand parameters are passed in constructed query

**Client version**
5.6.0-preview

**Desktop (please complete the following information):**
- OS: Win 10 x64
- Browser: N/A, WinForms application using standard HttpClient
- Version: N/A

**Comment by kroonwijk** [comment]
@gaspik I got the example to work specifying %24expand and %24select instead of $expand and $select (with the dollar sign). I think this is going "wrong" because the UrlTemplate used to specify the possible query parameters to be put in the url looks like:

`{+baseurl}/auditLogs/signIns{?%24top,%24skip,%24search,%24filter,%24count,%24orderby,%24select,%24expand}`

So as Kiota tries to simply match $expand on %24expand (literally) in the RequestAdapter it does not include it in the url because of the mismatch.

Still a bug in the UrlTemplate though :-)

**Comment by thomas-illiet** [comment]
Hello guys,

Thank you for this thread, to solve my implementation with following example:

```csharp
var request = graphclient.Devices.Delta().CreateGetRequestInformation();
request.UrlTemplate = "{+baseurl}/devices/microsoft.graph.delta()?$deltaToken=latest}"
```

> Because delta link is not in the template.


@andrueastman do you have any new regarding this issue ?

**Comment by andrueastman** [comment]
Select and expand parameters are available in latest SDK version. https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/443a79b572902cf081daf3857123e3931a2f4747/src/Microsoft.Graph/Generated/Me/Messages/Item/MessageItemRequestBuilder.cs#L282

> Because delta link is not in the template

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#skiptoken-and-deltatoken-query-parameters-in-delta-requests
