### ISSUE TITLE
Delta feature requests - v5.6-beta

### ISSUE THREAD

**Issue by gaspik** [microsoftgraph/msgraph-beta-sdk-dotnet#474]
**Is your feature request related to a problem? Please describe.**
We are developing a fully-featured email client. Recently, we have started to implement MSGraph in order to replace our existing AirSync/EWS implementations.

The only reasonable way for us to fetch data (due to amount) is delta requests, where we limit the selection only to id, and then fetch all updated items separately (via a lot of custom selectors/expansions)

When upgrading from v4 to v5 beta, we noticed major changes to API. These changes make working with delta queries very inefficient/hard for us, with currently 2 major problems

**Describe the solution you'd like**

- Easy passing of $deltaToken - while we can get delta token from PageIterator, there is no easy way to pass it back to delta request. The only possible way we found is similar to this:

```
var request = mailDeltaRequest.CreateGetRequestInformation();
request.QueryParameters.Add("$deltaToken", "deltaToken");
request.QueryParameters.Add("$select", "id");
request.Headers.Add("Prefer", "odata.maxpagesize=20");

var deltaResponse = await GraphServiceClient.RequestAdapter.SendAsync<Microsoft.Graph.Beta.Me.MailFolders.Delta.DeltaResponse>
				(request, Microsoft.Graph.Beta.Me.MailFolders.Delta.DeltaResponse.CreateFromDiscriminatorValue, cancellationToken: cancellationToken);
```

Which is rather cumbersome for such a basic feature, and it also does not work, probably due to https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/471 .

- Allow passing async lambda to PageIterator: As explained earlier, due to lot of expand/select we are unable to specify all details in main deltaQuery. Thus we request only IDs and then fetch individual items via batchQuery. However, the lambda in the new PageIterator does NOT support async lambda, so we have to revert to non-async method. Example

```
var iterator = PageIterator<Message, Microsoft.Graph.Beta.Me.MailFolders.Item.Messages.Delta.DeltaResponse>.
					CreatePageIterator(GraphServiceClient, firstPage, (m) =>
					{
						msgCache.Add(m);

						if (msgCache.Count > 19)
						{
							Synchronize(msgCache, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
							msgCache.Clear();
						}

						return true;
					});

				await iterator.IterateAsync(cancellationToken);
```

It would help if the lambda could work natively with await

**Comment by andrueastman** [comment]
Apologies @gaspik, Re-opening for now as I had missed that that. 

The descriptions for the metadata would most likely need fixing so that the `$deltaToken` show up in the generated requestConfiguration.

**Comment by andrueastman** [comment]
Closing this for now given the guidance added via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2087
