### ISSUE TITLE
Patch request in v5 beta should return updated object

### ISSUE THREAD

**Issue by gaspik** [microsoftgraph/msgraph-beta-sdk-dotnet#478]
**Is your feature request related to a problem? Please describe.**
In v4 of the client library, updating an item (via PATCH) causes server to return the updated item. This was also understood by clien library and object was returned.

We use etag to track version changes, so after PATCH we just stored new etag. In v5.6 beta preview, the PatchAsync method returns Task without the underlying type, not parsing the response

**Describe the solution you'd like**
PatchAsync should return Task<T> where T is the object you are updating. This would save us one request trip to server. The data is already in the response, it just needs to be processed/parsed properly by the client library

Sample code now:
```
var request = GraphServiceClient.Me.Events[uniqueId];				
await request.PatchAsync(graphItem, rc =>
				{
					if (versionId != null)
						rc.Headers.Add("If-Match", versionId);
				},
				cancellationToken: cancellationToken);
storedEvent = await GraphServiceClient.RequestAdapter.SendAsync<Event>(
					GetSingleItemRequest(folder, uniqueId),
					Event.CreateFromDiscriminatorValue,
					cancellationToken: cancellationToken);
```
					
Expectation is to be able to execute:

```
var request = GraphServiceClient.Me.Events[uniqueId];				
var storedEvent = await request.PatchAsync(graphItem, rc =>
				{
					if (item.DataObject.VersionId != null)
						rc.Headers.Add("If-Match", versionId);
				},
				cancellationToken: cancellationToken);
```

**Comment by andrueastman** [comment]
Thanks for trying out the new preview @gaspik.

The generator is currently generating void methods due to the schema provided in the openApi reference document. This is currently being tracked via https://github.com/microsoft/kiota/issues/1699 to allow for range responses in the schema.

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/545
