### ISSUE TITLE
[ClientBug] FileAttachment is not serialized with @odata.type

### ISSUE THREAD

**Issue by gaspik** [microsoftgraph/msgraph-beta-sdk-dotnet#479]
**Describe the bug**
When uploading event attachment, the request is refused with error
{"error":{"code":"UnprocessableType","message":"Cannot process input of abstract type 'microsoft.graph.attachment'"}}

**To Reproduce**
Try to upload FileAttachment object to existing event. Sample code;

```
FileAttachment fileAttachment = ToMSGraphCommonConversion.ConvertAttachment(attachment);
					await GraphServiceClient.Me.Events[validId]
						.Attachments
						.PostAsync(fileAttachment, cancellationToken: cancellationToken);
```

This serializes the object as:
{"isInline":false,"name":"empty.txt","size":5,"contentBytes":"ZW1wdHk="}

i.e. without FileAttachment type specification.

In v4, the object is serialized as
{"contentBytes":"ZW1wdHk=","isInline":false,"name":"empty.txt","size":5,"@odata.type":"microsoft.graph.fileAttachment"}

**Expected behavior**
Specify correct odata.type during serialization

**Client version**
5.6.0-preview

**Desktop (please complete the following information):**
 - OS: Win 10 x64
 - Browser: N/A, WinForms application using standard HttpClient
 - Version: N/A

**Comment by andrueastman** [comment]
Thanks for raising this @gaspik and trying out the new preview.

This is related to https://github.com/microsoft/OpenAPI.NET.OData/issues/243 which is not emitting the `@odata.type` property in the object's reference schema. We'll close this once the openApi conversion library fixes this and make a release with the corresponding schema update. 

For now you should be able to work around this by placing adding the property in the additionalData bag.

```cs
            var fileAttachment = ToMSGraphCommonConversion.ConvertAttachment(attachment);
            fileAttachment.AdditionalData["@odata.type"] = "microsoft.graph.fileAttachment";
```

**Comment by gaspik** [comment]
@andrueastman It looks like the fix broke something else, see

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/495
