### ISSUE TITLE
I'm getting Service_InternalServerError when trying to create SchemaExtension

### ISSUE THREAD

**Issue by alvipeo** [microsoftgraph/msgraph-beta-sdk-dotnet#48]
Basically, here it goes - https://stackoverflow.com/q/59395423/2896495.

I'm stuck with it. Is there anything I'm doing wrong?

**Comment by peombwa** [comment]
MS Graph doesn't support Azure B2C. This was answered here https://stackoverflow.com/q/59395423/2896495.
