### ISSUE TITLE
Missing Request() method on GraphServiceClient endpoints

### ISSUE THREAD

**Issue by MarcoBuess** [microsoftgraph/msgraph-beta-sdk-dotnet#488]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
Im creating a GraphServiceClient following the [Microsoft documentation](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS#client-credentials-provider). This should give me a client where I can specify `QueryParameters` after supplying the `Request()` builder.

### Actual behavior
I'm using F# and this snippet, which gives me a usable client:

```fsharp
let scope = [ "https://graph.microsoft.com/.default" ]

let clientCredential =
    ClientSecretCredential(config.TenantId, config.ClientId, config.ClientSecret)

let graphClient = GraphServiceClient(clientCredential, scope)
```

I can query endpoints fine in general, but the `Request()` method to modify the request e.g. filter options is not available on any endpoints. I don't have the ability to page the requests either. I'm getting a `Nextlink` back but have no ability to use that to perform additional querys through `graphClient`.

### Steps to reproduce the behavior
Packages used are:
1. `Azure.Identity`
2. `Microsoft.Graph.Beta`

F# code snipped to setup the client:
```fsharp
let scope = [ "https://graph.microsoft.com/.default" ]

let clientCredential =
    ClientSecretCredential(config.TenantId, config.ClientId, config.ClientSecret)

let graphClient = GraphServiceClient(clientCredential, scope)
```

For my szenario I used the `Groups` endpoint like so:
```fsharp
    let groups =
        async {
            return
                graphClient
                    .Groups
                    .GetAsync()
                    .Result
        }
```
`Request()` should be available after supplying `graphClient.Groups` but it isn't.

Any help to direct me in the right direction is highly appreciated.

Cheers.

**Comment by andrueastman** [comment]
Hey @MarcoBuess, 

Thanks for raising this issue. 

At the moment, the documentation points to using the stable Microsoft graph packages that have the version pattern of `4.x.x` .  Any chance you could confirm from your project definition that package in use has the version number matching that pattern?

We are currently working on a new version (with the version pattern `5.x.x`) that is in preview with breaking changes (this includes the dropping of the `.Request()` segment from the fluent API path as outlined in the upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#removal-of-request-from-the-fluent-api)). If you're willing to try it out, you can always follow the guide and give us feedback on it.

**Comment by MarcoBuess** [comment]
Thank you for the quick reply @andrueastman. I can confirm I'm currently using `v5.8.0-preview`. Which was pulled in automatically by my package manager. Is there any documented way, as of right now on how to supply query parameters in the `5.x.x` versions, or is this just not implemented yet? I will move forward swapping out the `v5.x.x` versus the latest `v4.x.x` and see how I can go from there.

Cheers

**Comment by andrueastman** [comment]
Hey @MarcoBuess,

Yes, you can. The same information is provided in the guide as well at the link below. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#query-options

**Comment by MarcoBuess** [comment]
Thank you very much 👍
