### ISSUE TITLE
InvalidModel when calling GraphServiceClient.IdentityGovernance.EntitlementManagement.AccessPackageAssignmentPolicies.PostAsync(accessPackageAssignmentPolicy)

### ISSUE THREAD

**Issue by cgontario** [microsoftgraph/msgraph-beta-sdk-dotnet#489]
**Describe the bug**
GraphServiceClient.IdentityGovernance.EntitlementManagement.AccessPackageAssignmentPolicies.PostAsync(accessPackageAssignmentPolicy) getting an InvalidModel error from Graph API with the same C# model that succeeded using v4 of the SDK.

I say the same code, but I did need to add some explicit casting for the assignments to AllowedRequestors and PrimaryApprovers as there's no longer an automatic cast to List<UserSet> from IEnumerable<ConnectedOrganizationMembers> or IEnumerable<SingleUser> after upgrading to the v5 SDK.

```
var accessPackageAssignmentPolicy = new AccessPackageAssignmentPolicy
{
    AccessPackageId = "{Access Package GUID}",
    DisplayName = "DisplayName",
    Description = "Description",
    RequestorSettings = new RequestorSettings
    {
        ScopeType = "SpecificConnectedOrganizationSubjects",
        AcceptRequests = true,
        AllowedRequestors = definition.RequestorSettings.AllowedRequestors.Select(connectedOrganization =>
            new ConnectedOrganizationMembers()
            {
                Id = "{Connected Organization GUID}"
            } as UserSet).ToList()
    },
    RequestApprovalSettings = new ApprovalSettings
    {
        IsApprovalRequired = true,
        IsApprovalRequiredForExtension = false,
        IsRequestorJustificationRequired = false,
        ApprovalMode = "SingleStage",
        ApprovalStages = definition.RequestApprovalSettings.ApprovalStages.Select(
            d => new ApprovalStage()
            {
                ApprovalStageTimeOutInDays = 14,
                EscalationTimeInMinutes = 0,
                IsApproverJustificationRequired = true,
                IsEscalationEnabled = false,
                PrimaryApprovers = d.PrimaryApprovers.Select(approver =>
                new SingleUser()
                {
                    Id = "{Guest User GUID}"
                } as UserSet).ToList()
            }).ToList()
    }
};

var graphClient = await _graphClientProvider.Get();
var response = await graphClient.IdentityGovernance.EntitlementManagement.AccessPackageAssignmentPolicies
    .PostAsync(accessPackageAssignmentPolicy);

_accessPackageAssignmentCache.AddOrUpdateItem(response);
```

**Client version**
- Microsoft.Graph.Core 3.0.0-preview10
- Microsoft.Graph.Beta 5.9.0-preview

**Desktop (please complete the following information):**
- OS: Windows 10
- Version 21H2
- Visual Studio 17.2.6

**Comment by cgontario** [comment]
This is happening when I try to create a Catalog now as well, which has a very simple model:

```
var graphCatalog = new AccessPackageCatalog()
{
    DisplayName = "DisplayName",
    Description = "Description",
    CatalogType = "UserManaged",
    CatalogStatus = "Published",
    IsExternallyVisible = true
};
```

I'm starting to get that "my computer is haunted" feeling. Did the Clean/Rebuild dance already. The ritualistic reboot comes next, followed by reaching for the "tether to your phone" straw...

**Comment by andrueastman** [comment]
Thanks for raising this @cgontario 

Just to confirm with regards to the issue with creating the `AccessPackageCatalog` model, are you able to create the model with `v5.8.0-preview` package and this is a regression in the `v5.9.0-preview` package?

**Comment by cgontario** [comment]
Thanks, @andrueastman. I should have thought to check that yesterday :) Yes, I can create a Catalog with `v5.8.0-preview` and `Microsoft.Graph.Core 3.0.0-preview9`.

Should I open a separate issue for that regression?

**Comment by andrueastman** [comment]
Thanks for confirming this @cgontario.

> Should I open a separate issue for that regression?

No need for now till we identify the issues are unrelated. 

Any chance you can share the code snippet used to make the call to create the `AccessPackageCatalog` as well to help replicate this scenario?

**Comment by cgontario** [comment]
Sure thing, here's what I'm using to create the Catalog:

```
...
var graphCatalog = new AccessPackageCatalog()
{
    DisplayName = "DisplayName",
    Description = "Description",
    CatalogType = "UserManaged",
    CatalogStatus = "Published",
    IsExternallyVisible = true
};

var graphClient = await _graphClientProvider.Get();
var response = await graphClient.IdentityGovernance.EntitlementManagement.AccessPackageCatalogs
    .PostAsync(graphCatalog);
...
```

**Comment by cgontario** [comment]
Hi @andrueastman, thanks for asking!

With `5.10.0-preview` I can create a Catalog, so that's good.

I still can't create an `AccessPackageAssignmentPolicy`, although the error has changed (no change in my code):

```
Value cannot be null.
Parameter name: input
```

Also, I now get an `InvalidModel` error from Graph when I try to create a `RoleAssignment` (this worked in `5.8.0-preview`):

```
var assignment = new UnifiedRoleAssignment
{
    RoleDefinitionId = "{GUID}",
    PrincipalId = "{GUID}",
    AppScopeId = $"/AccessPackageCatalog/{GUID}"
};

var newAssignment = await graphClient.RoleManagement.EntitlementManagement.RoleAssignments.PostAsync(assignment);
```

**Comment by ddyett** [comment]
closing older issues. please file a new issue if occurs with latest versions.
