### ISSUE TITLE
SDK 5.9.0-Preview Custodians.PostAsync Invalid Json

### ISSUE THREAD

**Issue by Cnevell** [microsoftgraph/msgraph-beta-sdk-dotnet#494]
Using the SDK 5.9.0-Preview the command in C# for the following is failing. This does not happen in earlier 5.x.0-Preview SDK.

EdiscoveryCustodian custodian = new EdiscoveryCustodian()
            {
                Email = email
            };
            try
            {
                custodian = await GraphHelper.GraphServiceClient.Security.Cases.EdiscoveryCases[eCase.Id]
                             .Custodians.PostAsync(custodian);                
           }

Error Message:
"Invalid JSON: Newtonsoft.Json.JsonSerializationException: Required property 'email' not found in JSON. Path '', line 1, position 63.\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type)\r\n   at Microsoft.Compliance.EDiscovery.GraphService.Models.Requests.Graph.GraphRequestModelBinder.BindModelAsync(ModelBindingContext bindingContext) in D:\\dbs\\el\\39f3\\sources\\dev\\Services\\GraphService\\src\\Service\\Models\\Requests\\Graph\\GraphRequestModelBinder.cs:line 31."

**Comment by andrueastman** [comment]
Thanks for raising this @Cnevell 

Any chance you can confirm that you can replicate this issue with the latest preview package `5.10.0-preview` package? We've update the models to fix missing ODataType properties in the latest generation update.

**Comment by Cnevell** [comment]
This appears to have been fixed.

**Comment by andrueastman** [comment]
Thanks for the feedback @Cnevell
