### ISSUE TITLE
SDK 5.10.0-Preview Graph UserSources PostAscyn IncludedSources not adding mailbox

### ISSUE THREAD

**Issue by Cnevell** [microsoftgraph/msgraph-beta-sdk-dotnet#496]
When using the 5.10.0-Preview SDK, the following code will not add the SourceType.Mailbox when adding a UserSource.

public async static Task<UserSource> AddCustodianSourcesAsync(EdiscoveryCase eCase, EdiscoveryCustodian custodian)
        {            
                    
            var userSource = await GraphHelper.GraphServiceClient.Security.Cases
                                .EdiscoveryCases[eCase.Id]
                                .Custodians[custodian.Id]
                                .UserSources
                                .PostAsync(new UserSource()
                                {
                                    Email = custodian.Email,
                                    IncludedSources = SourceType.Mailbox | SourceType.Site
                                });            

            return userSource;
        }

This will only add the mailbox if I do not include SourceType.Site. If I include Site, it will only include Site and ignore Mailbox. This does not present itself in the 4.x SDK or in GE. This does not work in any of the 5.x generation SDKs.

**Comment by ddyett** [comment]
closing older issues. please file a new issue if occurs with latest versions.
