### ISSUE TITLE
IDriveItemRequestBuilder.Checkout() returns unknown error

### ISSUE THREAD

**Issue by rjhaines** [microsoftgraph/msgraph-beta-sdk-dotnet#5]
I've successfully called `IDriveItemRequestBuilder.Checkout()` to check out a file on SharePoint. However, in testing, I first manually checked out the file and re-ran the same code. This resulted in a `Microsoft.SharePoint.Client.UnknownError` instead of something like `Microsoft.SharePoint.SPFileCheckOutException` as in this documentation: https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee542611%28v%3doffice.15%29

Is it feasible to provide a similar error with more descript message? Thank you. 
[AB#7164](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7164)

**Comment by rjhaines** [comment]
Even better would be to mimic `File.CheckedOutByUser` as documented here: https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee538952%28v%3doffice.15%29

**Comment by darrelmiller** [comment]
Is this error coming back from Graph SDK?  This repo is specifically for issues related to the Microsoft Graph SDKs.
