### ISSUE TITLE
SDK 5.10-preview size

### ISSUE THREAD

**Issue by sierrodc** [microsoftgraph/msgraph-beta-sdk-dotnet#500]
Hi,

 about assembly size:
- Microsoft.Graph.dll is a 10Mb assembly.
- Microsoft.Graph.Beta.dll v4.5: 22.5Mb
- Microsoft.Graph.Beta.dd v5.10:  **66.6Mb**

Are you going to shrink the assembly file or ~60Mb will be the default size?

**Comment by andrueastman** [comment]
Thanks for raising this @sierrodc 

Taking a look at the NuGet package sizes files at [v5.10.0 ](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.10.0-preview)is at ~18.53 MB while [v4.51.0](https://www.nuget.org/packages/Microsoft.Graph.Beta/4.51.0-preview) is at ~16.25 MB.

Any chance you can clarify how you get the sizes to help us investigate?

**Comment by sierrodc** [comment]
Hi,

I've just created a console application and I've installed the package [Microsoft.Graph.Beta 5.10.0-preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.10.0-preview).
When I compile the output this is what I can see:
![image](https://user-images.githubusercontent.com/2039745/182330297-fe908b5b-d1ac-4b3f-bc8d-1697cd6a8e4a.png)

The previous version, [Microsoft.Graph.Beta 4.52.0-preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/4.52.0-preview), install an assembly of 23Mb:
![image](https://user-images.githubusercontent.com/2039745/182331572-18960312-77fc-4c36-86a1-171bd960e46f.png)

It is not a huge problem even if the file is quite big. If it's not possible to reduce the size, maybe it is possible to split it in different funcionalities (calendars, events, mails, tasks in different assemblies).

**Comment by Dean-NC** [comment]
Wowsers! This concerns me too. I really hope this is a mistake. If we include the .xml file with the app, that's almost 200 MB!

@andrueastman You're looking at the size of the .nuget package itself, which is compressed like a .zip. Download the package manually and extract the files, and you'll see the real file sizes.

![image](https://user-images.githubusercontent.com/12361341/183270497-6b32a758-e78d-4ffd-a0f8-bd15e787e623.png)

**Comment by andrueastman** [comment]
Thanks for the clarification @Dean-NC. 

This indeed needs to be better and we'll be looking to improve this as we investigate this further.

**Comment by thomas-illiet** [comment]
Hello @sierrodc ,

The difference between the two packages is that we now use kiota....

In V4 there are a lot of interfaces / abstractions and in V5 each class has a single implementation because it uses a code generator. The code generator is not the best solution for me because it adds a lot of code deduplication and makes it difficult to debug

Kind regards
Thomas

**Comment by ddyett** [comment]
closing older issues. please file a new issue if occurs with latest versions.
