### ISSUE TITLE
Impossible to get the phone from the phone when it is added from B2C

### ISSUE THREAD

**Issue by antoinelifeworks** [microsoftgraph/msgraph-beta-sdk-dotnet#506]
Hi there, 

I'm having an issue where the graphAPI returns an empty array when I call this endpoint

/users/{id}/authentication/phoneMethods

Here is the query
`https://graph.microsoft.com/beta/users/da07b4a6-****-****-****-*********1d0/authentication/phoneMethods`

The result
```json
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('da07b4a6-****-****-****-*********1d0')/authentication/phoneMethods",
    "value": []
}
```

Of course, the user has a phone attached to his MFA.
![image](https://user-images.githubusercontent.com/107499974/182946554-42e51420-059e-4b79-9a69-c6a1e0b46c37.png)

There is also this thread on StackOverflow that says that the issue is the phone format.

[https://stackoverflow.com/questions/65200556/bug-identified-in-azure-b2c-mfa-phone-number-format-missing-spaces](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F65200556%2Fbug-identified-in-azure-b2c-mfa-phone-number-format-missing-spaces&data=05%7C01%7Ca.chagnon.michaud%40lifeworks.com%7C7345b046306a460f0b5d08da76583d28%7C7565b51c5e8748ebbc80252b20bc1ade%7C1%7C0%7C637952418639770899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hQFvdbRUgMh0bxboPLAf4kYXWfvRZvu%2FWrEs%2B1wxCGU%3D&reserved=0)

So I tried to add the space 
![image](https://user-images.githubusercontent.com/107499974/182947023-6068d990-e08b-4132-8c0c-dc8ef96b315b.png)

And now it works.

```json
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('da07b4a6-****-****-****-*********1d0')/authentication/phoneMethods",
    "value": [
        {
            "id": "----",
            "phoneNumber": "+1 4************",
            "phoneType": "mobile",
            "smsSignInState": "notAllowedByPolicy"
        }
    ]
}
```

Is it possible to fix this issue?

Thanks!

**Comment by andrueastman** [comment]
Thanks for raising this @antoinelifeworks 

As this repo is intended for requests/issues related to the dotnet client library, any chance you can post this request at the link below so that the relevant owners of the API can pick it up and give guidance? 
(If you can, please also post back the link to the issue created back in this issue so anyone who comes across this can follow it and potentially upvote it and/or know the status of the request.)

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by antoinelifeworks** [comment]
Here is the link
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/impossible-to-get-the-phone-from-the-phone-when-it-is-added-from/idi-p/3593762
