### ISSUE TITLE
Unable to add group member with preview package

### ISSUE THREAD

**Issue by thomas-illiet** [microsoftgraph/msgraph-beta-sdk-dotnet#510]
Hello @andrueastman,

After spending an hour looking for a method to add and remove members of a group, I open this problem for help.

I use currently the following package version: 5.10.0-preview

Can you help me to find the method to add a user member in a group?

Kind regards
Thomas

**Comment by andrueastman** [comment]
Thanks for trying out the new preview @thomas-illiet 

Any chance you can try out the following snippets to add a group member.

```cs
var requestBody = new ReferenceCreate
{
    OdataId = "https://graph.microsoft.com/v1.0/directoryObjects/{id}"
};

await graphClient.Groups["{group-id}"].Members.Ref
    .PostAsync(requestBody);
```

And this to delete the group member

```cs
await graphClient.Groups["{group-id}"].Members["{member-id}"].Ref
    .DeleteAsync();
```

We'll use the feedback to enhance the upgrade guide to cover the changes made when using `Odata Reference segments` as we await to update the docs snippets.

**Comment by thomas-illiet** [comment]
Whaaaa you are my hero @andrueastman  :)
