### ISSUE TITLE
Removing a ManagedDeviceMobileAppConfigurationAssignment throws ServiceException

### ISSUE THREAD

**Issue by Yomodo** [microsoftgraph/msgraph-beta-sdk-dotnet#512]
Using MS Graph 4.54.0-preview, the following code throws a `ServiceException` when removing a/all `ManagedDeviceMobileAppConfigurationAssignment`:

```csharp
var builder = MSGraphBeta.DeviceAppManagement.MobileAppConfigurations[policy.Id];
using var task = builder.Assign(Array.Empty<ManagedDeviceMobileAppConfigurationAssignment>())
    .Request()
    .PostAsync(cancellationToken);
await task;
```

Which results in: `ServiceException Code: No method match route template\r\nMessage: No OData route exists that match template ~/singleton/navigation/key/action with http verb POST ...`

When doing it without the SDK, the assignment is removed as expected:
```csharp
// URL obtained from Azure portal.
var uri = new Uri($"{MSGraphBeta.DeviceAppManagement.MobileAppConfigurations[policyId].RequestUrl}/{typeof(ManagedDeviceMobileAppConfiguration).FullName}/assign");
var jsonData = $"{{\"assignments\":[]}}";

var oboAppAuth = await _tokenService.GetOboAuthHeaderAsync(...);

var result = await _httpService.SendHttpAsync(HttpMethod.Post, uri, oboAppAuth, jsonData, cancellationToken);
```

**Comment by andrueastman** [comment]
Hey @Yomodo,

Any chance you can confirm that this is still the case? According to the API documentation at the link below it looks like there shouldn't be a need to add the `{typeof(ManagedDeviceMobileAppConfiguration).FullName}` to the url segment.

https://learn.microsoft.com/en-us/graph/api/intune-apps-manageddevicemobileappconfiguration-assign?view=graph-rest-beta#request

**Comment by Yomodo** [comment]
Currently we get timeouts when working with `#microsoft.graph.iosMobileAppConfiguration` instances, which we opened a ticket for. I'll will test this asap.
