### ISSUE TITLE
How to get Ediscovery case Id with case displayName

### ISSUE THREAD

**Issue by karthikd70** [microsoftgraph/msgraph-beta-sdk-dotnet#521]
I am trying to get aed case id by filtering with display name in graph.beta 4.54. The filter is not working. But same filter working in new security/cases endpoint. Is there any workaround in 4.53 preview?

This is not working:
https://graph.microsoft.com/beta/compliance/ediscovery/cases?$filter=displayName eq 'ex case 1'

This is working:
https://graph.microsoft.com/beta/security/cases/ediscoveryCases?$filter=displayName eq 'ex case 1'

**Comment by andrueastman** [comment]
APIs under the `ediscovery` namespace are being deprecated according to [this](https://learn.microsoft.com/en-us/graph/api/resources/ediscovery-ediscoveryapioverview?view=graph-rest-beta). 

The appropriate way should therefore be 
```cs
var cases = await graphServiceClient.Security.Cases.EdiscoveryCases.Request().Filter("displayName eq 'ex case 1'").GetAsync();
```
