### ISSUE TITLE
Retrieving friendly (localized) name for resources

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-beta-sdk-dotnet#53]
#### Question

When I retrieve the SubscribedSku data from Graph, it includes a [SkuPartNumber](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/e35b348a6f84d45554418ff029df840b161ed315/src/Microsoft.Graph/Models/Generated/SubscribedSku.cs#L73) property that identifies the SKU that is subscribed to. How can I programmatically get a friendly name for that SKU?

#### Example

If the `SkuPartNumber` is "STANDARDPACK", I want a programmatic way to retrieve something like "Enterprise Plan E1". I know I could hard-code a table, but that would then require keeping the table up to date, and Microsoft must have this relationship already set up internally somwhere, so I just want to know how I can pull that information from the Microsoft Graph Beta API.

#### Rationale

Friendly/localized text is necessary for tools that integrate with Graph to properly identify resources in user interfaces.

**Comment by darrelmiller** [comment]
I looked and couldn't find those names in Graph.  That would definitely be valuable.  Any chance you could add that in the https://microsoftgraph.uservoice.com ?  Thanks.

**Comment by KirkMunro** [comment]
Thanks @darrelmiller, I wasn't aware of that Uservoice site. I searched, and it turns out someone already logged a similar issue, to which I added comments that pull a bunch of similar requests from various locations together in one shot (this isn't just about SKU display names). You can find my comment here:

https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/34661174-add-skudisplayname-in-subscribedskus#comments

**Comment by darrelmiller** [comment]
Thanks @KirkMunro   The Microsoft Graph specific UserVoice is fairly new (within the last year) and Jeremy has worked hard to ensure that we have commitment from service teams to actually work on the user voice items.  This one seems like low hanging fruit.
