### ISSUE TITLE
How to use GraphServiceClient.cs in Dogfood in msgraph-beta-sdk-dotnet?

### ISSUE THREAD

**Issue by NaraVen** [microsoftgraph/msgraph-beta-sdk-dotnet#559]
I see this "https://graph.microsoft.com/beta" hardcoded in the GraphServiceClient.cs . How can we use beta for dogfood?

**Comment by NaraVen** [comment]
@andrueastman , I saw your example dated Sep 2021 by passing the CUSTOM_URL. How can we get the same feature working in beta. I mean I want to pass the CUSTOM_URL while creating the GraphServiceClient.

**Comment by andrueastman** [comment]
Thanks for raising this @NaraVen,

Any chance you could share which version of the SDK you would like to achieve this?

**Comment by NaraVen** [comment]
@andrueastman , we are using 5.13.0-preview

**Comment by NaraVen** [comment]
Thank you @andrueastman

**Comment by BrianTJackett** [comment]
Thank you @andrueastman for sharing example on setting custom BaseUrl.  I was struggling with this between the Beta and V1 NuGet packages.  Unblocks me on a separate project.

**Comment by andrueastman** [comment]
Closing this one for now as the latest [preview version](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.14.0-preview) makes it easier to update the baseUrl through the constructor as below,

```cs
var interactiveBrowserCredentialOptions = new InteractiveBrowserCredentialOptions
{
    ClientId = "CLIENT_ID"
};
var interactiveBrowserCredential = new InteractiveBrowserCredential(interactiveBrowserCredentialOptions);
var graphClient = new GraphServiceClient(interactiveBrowserCredential, scopes, "https://graph.microsoft.com/beta");
```
