### ISSUE TITLE
GraphServiceClient.IdentityGovernance.EntitlementManagement.AccessPackageAssignmentPolicies.PostAsync(accessPackageAssignmentPolicy) 

### ISSUE THREAD

**Issue by WayneAASPLLC** [microsoftgraph/msgraph-beta-sdk-dotnet#582]
Using preview 5.14 of Microsoft.Graph.Beta
Unable to Post Policy update

```
using Azure.Core;
using Azure.Identity;
using Microsoft.Graph.Beta;
using Microsoft.Graph.Beta.Models;

TokenCredential tokencreds = new InteractiveBrowserCredential();

Microsoft.Graph.Beta.GraphServiceClient graphClient = new Microsoft.Graph.Beta.GraphServiceClient(tokencreds);

var accessPackageAssignmentPolicy = new AccessPackageAssignmentPolicy()
{
    AccessPackageId = "",
    DisplayName = "Initial Policy",
    Description = "Initial Policy",
    AccessReviewSettings = null,
    RequestorSettings = new RequestorSettings()
    {
        ScopeType = "SpecificDirectorySubjects",
        AcceptRequests = true,
        AllowedRequestors = new List<UserSet>()
           {
               new GroupMembers()
               {
                    IsBackup = false,
                     Id = "",
                      Description = "Authorized requestors"
               } as UserSet,
           }
    },
    Questions = new List<AccessPackageQuestion>()
     {
         new AccessPackageQuestion()
         {
             IsRequired = true,
              Text = new AccessPackageLocalizedContent()
              {
                   DefaultText = "test"
              }
         }
     },

};

await graphClient.IdentityGovernance.EntitlementManagement.AccessPackageAssignmentPolicies
	.PostAsync(accessPackageAssignmentPolicy);
```

Error:
Microsoft.Graph.Beta.Models.ODataErrors.ODataError
  HResult=0x80131500
  Message=Exception of type 'Microsoft.Graph.Beta.Models.ODataErrors.ODataError' was thrown.
  Source=Microsoft.Kiota.Http.HttpClientLibrary
  StackTrace:
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<ThrowFailedResponse>d__28.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Graph.Beta.IdentityGovernance.EntitlementManagement.AccessPackageAssignmentPolicies.AccessPackageAssignmentPoliciesRequestBuilder.<PostAsync>d__21.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\Administrator\source\repos\GraphStuff\GraphStuff\Program.cs:line 44
   at Program.<Main>(String[] args)

**Comment by andrueastman** [comment]
Thanks for raising this @WayneAASPLLC,

Any chance you can share what the error is from the API when you follow the error handling guidance as below?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#error-handling

```cs
try
{
    await graphClient.IdentityGovernance.EntitlementManagement.AccessPackageAssignmentPolicies
	.PostAsync(accessPackageAssignmentPolicy);
}
catch (ODataError odataError)
{
    Console.WriteLine(odataError.Error.Code);
    Console.WriteLine(odataError.Error.Message);
    throw;
}
```

**Comment by WayneAASPLLC** [comment]
use this instead:

```
catch (ODataError odataError)
{
    Console.WriteLine(odataError.Error.Code);
    Console.WriteLine(odataError.Error.Message);
}

Console.ReadLine();
```

 but it was what i expected:
InvalidModel
The model is invalid.

When trying to do questions in PowerShell i run into the same error even with using odata type

**Comment by WayneAASPLLC** [comment]
This is the site where the information appears to be out of date:
https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&tabs=powershell

**Comment by WayneAASPLLC** [comment]
Example params that should work for powershell but also fails with the same error:

```
$pparams = @{
        AccessPackageId = ""
        DisplayName = "Initial Policy"
        Description = "Initial Policy"
        AccessReviewSettings = $null
        RequestorSettings = @{
            ScopeType = "SpecificDirectorySubjects"
            AcceptRequests = $true
            AllowedRequestors = @(
                @{
                    "@odata.type" = "#microsoft.graph.groupMembers"
                    isBackup = $false
                    id = ""
                    description = "Authorized requestors"
                }
            )
        }
        Questions = @(
            @{
                IsRequired = $false
                Text = @{
				    DefaultText = "Who is your manager?"
                    LocalizedTexts = @(
                    )
                }
                "@odata.type" = "#microsoft.graph.accessPackageTextInputQuestion"
			    IsSingleLineQuestion = $false
            }
        )
    }
```

New-MgEntitlementManagementAccessPackageAssignmentPolicy -BodyParameter $pparams

**Comment by andrueastman** [comment]
Hey @WayneAASPLLC 
Are you by any chance able to replicate this using the [Graph Explorer](https://aka.ms/ge) as well?

**Comment by WayneAASPLLC** [comment]
> 

yes, same error

**Comment by WayneAASPLLC** [comment]
This was resolved in another github so this ended up being a duplicate.
