### ISSUE TITLE
[QUERY] Can use interactive login in PowerShell but not allowed in C#?

### ISSUE THREAD

**Issue by jsquire** [microsoftgraph/msgraph-beta-sdk-dotnet#584]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#33045](https://github.com/Azure/azure-sdk-for-net/issues/33045).

### Library name and version

Microsoft.Graph.Beta Preview 5.14

### Query/Question

In PowerShell you can use:
Connect-MgGraph -Scopes "User.ReadWrite.All", "Group.ReadWrite.All", "EntitlementManagement.ReadWrite.All"

In C# you try to mimic the same thing and it will say you need API access. I cannot do this via API and must use interactive login.
Please explain why PowerShell can do this but Microsoft disables C#???

client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await TokenHandler.GetCustomToken(tokencreds, new string[] { "https://graph.microsoft.com/User.ReadWrite.All", "https://graph.microsoft.com/Group.ReadWrite.All", "https://graph.microsoft.com/EntitlementManagement.ReadWrite.All" }));

I must be able to do it with interactive login since PowerShell can do it? .default will not work in this case.

### Environment

C# .Net 6 and PowerShell 7.3.1

**Comment by andrueastman** [comment]
Hey @WayneAASPLLC,

Any chance you could share how you are initializing the `GraphServiceClient` to make the calls to Microsoft Graph?

I believe this document should also be helpful with regards to the various authentications flows you can use with graph.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/tokencredentials.md

**Comment by WayneAASPLLC** [comment]
> Hey @WayneAASPLLC,
> 
> Any chance you could share how you are initializing the `GraphServiceClient` to make the calls to Microsoft Graph?
> 
> I believe this document should also be helpful with regards to the various authentications flows you can use with graph.
> 
> https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/tokencredentials.md

you'll notice in the link you provided you need a clientid, you don't need one for powershell. why is that?

**Comment by WayneAASPLLC** [comment]
Hmm, it is saying It needs Author feedback, yet I have replied???
Is there something else I need to do?

**Comment by WayneAASPLLC** [comment]
Looks like this is trying to auto closing again with no response.

**Comment by WayneAASPLLC** [comment]
this is pretty much a dup now and has been answer in: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1716#issuecomment-1366057085
