### ISSUE TITLE
BETA URL ??

### ISSUE THREAD

**Issue by kiquenet** [microsoftgraph/msgraph-beta-sdk-dotnet#585]
why  https://graph.microsoft.com/beta ?

I use Nuget version 4.43.0 for microsoft.graph
C:\Users\xxxxxxx\.nuget\packages\microsoft.graph\4.43.0

**Comment by rubens-farias** [comment]
Were you expecting the prod version? You should go with https://github.com/microsoftgraph/msgraph-sdk-dotnet

This repo is for the beta version, so the url.
