### ISSUE TITLE
API is Missing IAuditLogRootDirectoryAuditsCollectionPage

### ISSUE THREAD

**Issue by mjanulaitis** [microsoftgraph/msgraph-beta-sdk-dotnet#596]
**Describe the bug**
Unable to upgrade existing code to use the latest API.

**To Reproduce**

                            IAuditLogRootDirectoryAuditsCollectionPage auditLogRoot = await graphClient
                                .AuditLogs
                                .DirectoryAudits
                                .Request()
                                .Filter(f)
                                .OrderBy("ActivityDateTime asc")
                                .GetAsync();

**Expected behavior**
The API should either be backwards compatible or there should be a documented migration path.

**Desktop (please complete the following information):**
Windows 10
Microsoft.Graph.Beta v5.15.0-preview

**Additional context**

**Comment by andrueastman** [comment]
Hey @mjanulaitis,

Thanks for raising this. As you are using the `5.15.0-preview` package any chance you have taken a look at the guide at the link below?

I believe you should be now be able to do the same as below.

```cs
            var auditLogRoot = await graphServiceClient
                                        .AuditLogs
                                        .DirectoryAudits
                                        .GetAsync(requestConfig =>
                                        {
                                            requestConfig.QueryParameters.Filter = "";
                                            requestConfig.QueryParameters.Orderby = new string[] { "ActivityDateTime asc" };
                                        });
```

**Comment by mjanulaitis** [comment]
I have updated to version 5.19.0.Preview and now I get the following error only when filtering on activityDateTime on directory audit logs:

Exception of type 'Microsoft.Graph.Beta.Models.ODataErrors.ODataError' was thrown

Sign-Ins works as expected.  Here is the code:

```
var f = $"activityDateTime ge {startDT.ToUniversalTime():yyyy-MM-ddTHH:mm:ss.fffZ}'";

var response = await graphClient.AuditLogs.DirectoryAudits.GetAsync(rc =>
{
    rc.QueryParameters.Filter = f;
    rc.QueryParameters.Orderby = new[] { "activityDateTime asc" };
});
```

**Comment by mjanulaitis** [comment]
Is there anybody out there?
