### ISSUE TITLE
Add support for downloading attachments

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-beta-sdk-dotnet#6]
Add custom request builder for downloading attachment.

We added support for MIME format for message and ItemAttachment.
This is designed as streaming API.

Me/messages/{messageId}/$value – will give stream with MIME data.

Me/Messages/{messageId}/Attachments/{AttachmentId}/$value – 
This will have different contract for different type of attachment
•	FileAttachment – it will stream raw file content bytes.
•	ItemAttacment – it will stream mime data for attached message.
•	ReferenceAttachment – it’s error – not supported method.
 
[AB#7150](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7150)

**Comment by darrelmiller** [comment]
Metadata needs to be updated to have hasStream attribute.  /cc @nimeesh-msft

**Comment by ddyett** [comment]
@MIchaelMainer this can be closed, correct?
