### ISSUE TITLE
Missing Organization.tenantType in beta SDK, whereas the API returns it and it's documented in beta doc

### ISSUE THREAD

**Issue by cnotin** [microsoftgraph/msgraph-beta-sdk-dotnet#609]
I discovered this issue in the Java beta SDK, but I came to look here in .NET to double-check, and I noticed the exact same issue: `tenantType` missing in beta whereas it exists in v1.0
See https://github.com/microsoftgraph/msgraph-beta-sdk-java/issues/499 for more details

**Comment by andrueastman** [comment]
This looks to be also missing from the metadata used to generate the SDK available [here](https://graph.microsoft.com/beta/$metadata).

![image](https://user-images.githubusercontent.com/6464005/216248253-f8c4a4ce-0e16-4597-8707-e0956008fb5a.png)

Any chance you can confirm that the beta API accepts or returns this property when using the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)?

**Comment by cnotin** [comment]
> Any chance you can confirm that the beta API accepts or returns this property

Of course I confirm it exists, both on v1.0 and beta:
![image](https://user-images.githubusercontent.com/550823/216779903-d2524d85-b73a-4254-97d6-12d0f66a63b1.png)
![image](https://user-images.githubusercontent.com/550823/216779908-fd0064a6-8775-4f25-90b5-5d28a6b03498.png)

**Comment by baywet** [comment]
@cnotin thanks for your patience with this one.
@andrueastman can you open an ICM on the relevant team so they can fix their metadata please?

**Comment by baywet** [comment]
https://portal.microsofticm.com/imp/v3/incidents/incident/467589599/summary

**Comment by andrueastman** [comment]
Closing as property is available at https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/443a79b572902cf081daf3857123e3931a2f4747/src/Microsoft.Graph/Generated/Models/Organization.cs#L384
