### ISSUE TITLE
How do you set up GraphServiceClient in v5 and up?

### ISSUE THREAD

**Issue by tieje** [microsoftgraph/msgraph-beta-sdk-dotnet#615]
My current method, which works for version 4.71 is
```csharp
using Beta = BetaLib.Microsoft.Graph;
using Graph = Microsoft.Graph;

public static Beta.GraphServiceClient NewBetaGraphClient(string adTenantId, string adClientId, string adClientSecret)
{
    var tokenCredential = new ClientSecretCredential(adTenantId, adClientId, adClientSecret);
    var handlers = Graph.GraphClientFactory.CreateDefaultHandlers(new Graph.TokenCredentialAuthProvider(tokenCredential));
    var httpClient = Graph.GraphClientFactory.Create(handlers);
    return new Beta.GraphServiceClient(httpClient);
}
```

What would work for version 5 and up?
Ultimately, I need access to the `CredentialRegistrationDetails` endpoint, which is a beta feature.

**Comment by andrueastman** [comment]
Thanks for raising this,

As outlined in the note in the[ upgrade guide](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#authentication), authentication is no longer handled in the request middleware but by the client, and the `authprovider` parameter passed to the `GraphServiceClient` contructor.

```cs
        public static GraphServiceClient NewBetaGraphClient(string adTenantId, string adClientId, string adClientSecret)
        {
            var tokenCredential = new ClientSecretCredential(adTenantId, adClientId, adClientSecret);
            var handlers = GraphClientFactory.CreateDefaultHandlers();
            var httpClient = GraphClientFactory.Create(handlers);
            return new GraphServiceClient(httpClient, new Microsoft.Graph.Authentication.AzureIdentityAuthenticationProvider(tokenCredential));
        }
```

**Comment by tieje** [comment]
> Thanks for raising this,
> 
> As outlined in the note in the[ upgrade guide](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#authentication), authentication is no longer handled in the request middleware but by the client, and the `authprovider` parameter passed to the `GraphServiceClient` contructor.
> 
> ```cs
>         public static GraphServiceClient NewBetaGraphClient(string adTenantId, string adClientId, string adClientSecret)
>         {
>             var tokenCredential = new ClientSecretCredential(adTenantId, adClientId, adClientSecret);
>             var handlers = GraphClientFactory.CreateDefaultHandlers();
>             var httpClient = GraphClientFactory.Create(handlers);
>             return new GraphServiceClient(httpClient, new Microsoft.Graph.Authentication.AzureIdentityAuthenticationProvider(tokenCredential));
>         }
> ```

Worked for me! Thanks a bunch!
