### ISSUE TITLE
Incorrect RequestURL used in ManagedDeviceMobileAppConfigurationAssignRequestBuilder

### ISSUE THREAD

**Issue by EyuelDK** [microsoftgraph/msgraph-beta-sdk-dotnet#62]
Cause:

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/b693728aaaa077c5badaebe5e4056961fe013eb4/src/Microsoft.Graph/Requests/Generated/ManagedDeviceMobileAppConfigurationRequestBuilder.cs#L121

Effect:

Exception is thrown "No OData route exists that match template ~/singleton/navigation/key/cast/navigation/key", thus preventing assignment of app configuration

Fix:

`this.AppendSegmentToRequestUrl("microsoft.graph.managedDeviceMobileAppConfiguration/assign")` 
[AB#7154](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7154)

**Comment by MIchaelMainer** [comment]
Does this still work with the following?
`this.AppendSegmentToRequestUrl("assign")`

This may be an issue with using the FQN of the action. This is likely a service issue,

**Comment by EyuelDK** [comment]
> Does this still work with the following?
> `this.AppendSegmentToRequestUrl("assign")`

It does not work - same error. Currently `this.AppendSegmentToRequestUrl("microsoft.graph.managedDeviceMobileAppConfiguration/assign")` seems to be the only fix I've found. Here is my workaround code if you're interested:

**Comment by maisarissi** [comment]
Hi @EyuelDK .

Can you validate whether this is still happening in the latest version of the SDK?
