### ISSUE TITLE
TeamworkTag ListMembers odata.nextlink returning Bad Request

### ISSUE THREAD

**Issue by JJarv04** [microsoftgraph/msgraph-beta-sdk-dotnet#620]
Followup for #526

The endpoint that was fixed (adding the pagination capabilities) in the beforementioned issue is now supplying an odata.nextlink url in its response, **but** the url itself _seems_ to be malformed or otherwise incorrect? Any attempt to follow a page url gives a Bad Request.

Using Graph Explorer we can see the response is now supplying an nextLink parameter:
```
"@odata.nextLink": "https://graph.microsoft.com/beta/teams/cdf25aa2-f21c-4377-87b0-77f1ddacce2e/tags/MzQxZTI5NzMtNGE1Zi00YjFlLWI4OGMtMjhlMmEwN2Y5YmVkIyNjZGYyNWFhMi1mMjFjLTQzNzctODdiMC03N2YxZGRhY2NlMmUjI3RzT2FiTEJXTEQ=/members?$skiptoken=1.ktVizIvGAAAAi%2fIogapQcm9wZXJ0aWVzgbFDb250aW51YXRpb25Ub2tlbtlqK1JJRDp%2bN2FVd0FLWnlySGEtMGhJQQEA8D89PSNSVDoxI1RSQzoxMDAjSVNWOjIjSUVPOjY1NTUxI1FDRjo4I0ZQQzpBZ0ZMVVVzTUFMK1NBc0RmYnkvR01RQWlBRkVFQU9FaEFEOD0%3d"
```

But attempting to follow it:
```
{
    "error": {
        "code": "BadRequest",
        "message": "Value cannot be null. (Parameter 's')",
        "innerError": {
            "date": "2023-02-23T03:48:11",
            "request-id": "a8cb5b89-b90e-43de-bccf-c006edad8fd7",
            "client-request-id": "d3556ac6-efda-1bf0-b0bc-bb5f4c1bef18"
        }
    }
}
```

Also tried switching v1.0/beta API's with no change.

**Comment by andrueastman** [comment]
Thanks for raising this @JJarv04,

We've raised this with the relevant API team to follow up and resolved and will give feedback once resolve. 

https://portal.microsofticm.com/imp/v3/incidents/details/369944530/home

**Comment by ssdevref** [comment]
Hi, I would like to weigh in that we're also seeing this issue when attempting to make a request based on the skipToken value.
```JSON
{
    "error": {
        "code":"BadRequest",
        "message":"Value cannot be null. (Parameter 's')",
        "innerError":{"date":"2023-03-03T16:57:36",
         "request-id":"7221119b-f47e-4832-af7c-be1d08af21ee",
         "client-request-id":"7221119b-f47e-4832-af7c-be1d08af21ee"
        }
    }
}
```

**Comment by andrueastman** [comment]
The feedback from the API team is that the fix has been implemented and we should see the fix deployed in the next release. Hopefully, we should see this in the coming week.

**Comment by andrueastman** [comment]
@ssdevref @JJarv04 

API team confirms that fix has been deployed and available and we'll close this one for now. 

In case of any issues, feel free to re-open/create new issue.
