### ISSUE TITLE
Unable to search DirectoryAudits by ActivityDateTime

### ISSUE THREAD

**Issue by mjanulaitis** [microsoftgraph/msgraph-beta-sdk-dotnet#626]
I have updated to version 5.19.0.Preview and now I get the following error only when filtering on ActivityDateTime on directory audit logs:

Exception of type 'Microsoft.Graph.Beta.Models.ODataErrors.ODataError' was thrown

Sign-Ins works as expected when filtered by CreatedDateTime. Here is the code:

```
var f = $"ActivityDateTime ge {startDT.ToUniversalTime():yyyy-MM-ddTHH:mm:ss.fffZ}";

var response = await graphClient.AuditLogs.DirectoryAudits.GetAsync(rc =>
{
    rc.QueryParameters.Filter = f;
    rc.QueryParameters.Orderby = new[] { "ActivityDateTime asc" };
});
```

**Comment by andrueastman** [comment]
Thanks for raising this @mjanulaitis 

Any chance you can look into the API error and confirm what you get when you follow the guidance on error handling at the link below?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#error-handling

**Comment by mjanulaitis** [comment]
Thanks so much I missed it:

"Specified argument was out of the range of valid values. (Parameter 'Minimum allowed time for activityDateTime is 2/5/2023 12:00:00 AM')"

I already have a fix for this in the older version I just need to port it now.
