### ISSUE TITLE
Client API?

### ISSUE THREAD

**Issue by mhagesfeld** [microsoftgraph/msgraph-beta-sdk-dotnet#63]
Has this been implemented in the Client API as of yet?  I see in the snippets that the UploadSession is in the Files Service snippet, but not the MailService.  Are there plans to implement this?  Or should I write the REST wrapper myself?
Thanks, Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95441aec-d30e-394b-a816-25d1537bfe50
* Version Independent ID: 7f59d2e4-52fa-cd12-6817-13b2ee153b2d
* Content: [attachment: createUploadSession - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/attachment-createuploadsession?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/attachment-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/attachment-createuploadsession.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Transferred this to the Beta SDK repository.

**Comment by MIchaelMainer** [comment]
@andrueastman Have we tested this against mail attachments in beta?

**Comment by darrelmiller** [comment]
The snippet for uploading mail attachments is here https://docs.microsoft.com/en-us/graph/api/attachment-createuploadsession?view=graph-rest-beta&tabs=csharp#request

**Comment by mhagesfeld** [comment]
Yes, I found it and am trying to use it.

I am trying to use the following code, but am getting "Message: The audience claim value is invalid for current resource. Audience claim is 'https://graph.microsoft.com', request url is 'https://outlook.office.com/api/beta/Users..."

I get it on the provider.GetUploadChunkRequests(); call below:

```
AttachmentItem attachmentItem= new AttachmentItem
            { 
                Name = [Name],
                AttachmentType = AttachmentType.File,
Size = [Size]
            };

var session = graphClient.Users[USEREMAIL].Messages[MESSAGEID].Attachments.CreateUploadSession(attachmentItem).Request().PostAsync().Result;
            var stream = new MemoryStream(BYTEARRAY);
            var maxSizeChunk = DEFAULT_CHUNK_SIZE;
            var provider = new ChunkedUploadProvider(session, graphClient, stream, maxSizeChunk);
            var chunkRequests = provider.GetUploadChunkRequests();
```

(I am using the graphClient to send emails successfully, and have also used it to upload large files using the uploadSession method)

**Comment by andrueastman** [comment]
@MIchaelMainer Yes this was tested with the beta api.

**Comment by andrueastman** [comment]
Hi, @mhagesfeld,

You are most likely getting the error because of using the `ChunkedUploadPorvider` instead of using the `FileUploadTask` to upload the attachment which is setting the Auth header to cause the error you are receiving.

To use the file upload task, follow the following steps

First create an upload session and handing it over to the task as illustrated.
```cs
// Create task
var maxSliceSize = 320 * 1024; // 320 KB - Change this to your chunk size. 4MB is the default.
LargeFileUploadTask<FileAttachment> largeFileUploadTask = new LargeFileUploadTask<FileAttachment>(uploadSession, stream, maxSliceSize);
```
 Create an upload monitor (optional)
```cs
// Setup the progress monitoring
IProgress<long> progress = new Progress<long>(progress =>
{
    Console.WriteLine($"Uploaded {progress} bytes of {stream.Length} bytes");
});
```
The service only returns location URI which can be read off from the result object as follows.

```cs
UploadResult<FileAttachment> uploadResult = null;
try
{
    uploadResult = await largeFileUploadTask.UploadAsync(progress);
    if (uploadResult.UploadSucceeded)
    {
        Console.WriteLine(uploadResult.Location);//the location of the object
    }
}
catch (ServiceException e)
{
    Console.WriteLine(e.Message);
}
```
