### ISSUE TITLE
CustomSecurityAttributes null when loaded via /met endpoint

### ISSUE THREAD

**Issue by Jonah-Jordan** [microsoftgraph/msgraph-beta-sdk-dotnet#630]
Hi,

We are trying to load the custom security attributes through the /me endpoint:
https://graph.microsoft.com/beta/me?$select=customSecurityAttributes

This is returning the following response:

```

{
"customSecurityAttributes": null
}
```

When we are querying on the specific user with his ID, the custom security attributes are correctly returned.

**Comment by andrueastman** [comment]
Thanks for raising this @Jonah-Jordan 

As this question is related to the API and this repo is mainly intended for SDK related issues, could you post  the same query at the link below so that the relevant API owners may be able to follow up?

https://docs.microsoft.com/en-us/answers/products/graph

**Comment by andrueastman** [comment]
Followed up by the API team at https://learn.microsoft.com/en-us/answers/questions/1188139/customsecurityattributes-null-when-loaded-via-met
