### ISSUE TITLE
Azure AD B2C local account - occasional error when logging in immediately after creating account

### ISSUE THREAD

**Issue by arek-avanade** [microsoftgraph/msgraph-beta-sdk-dotnet#65]
In our application we recently moved from Azure AD Graph API to Microsoft Graph API for creating local user accounts in Azure AD B2C. The issue I'm reporting was occurring in Azure AD Graph API before, and when moving to Microsoft Graph API we hoped it would disappear, however the API switch didn't help.

**Problem:**
In our app we create a local B2C account with the code below. Then immediately after creating the account we use Azure AD OAuth token endpoint (https://login.microsoftonline.com/masdpdev.onmicrosoft.com/oauth2/v2.0/token) to log in using 'password' grant type (ROPC). 
Sometimes (I would say 1 out of 10 cases) when trying to log in, we get the following error from the token endpoint:
> AADB2C99002: This user does not exist and profile 'AAD-UserReadUsingObjectId' requires the user to have already been created.

The account of course exists and if we wait some time we would be able to sign in with the same credentials. In our 'AddADUser' method below we even get correct objectID. To me it looks like some synchronization issue where the data that is posted to Microsoft Graph API is not immediately available in Azure AD B2C. 

Is there a fix for this? Or a workaround to make sure the request has been fully synchronized?

```
public async Task<string> AddADUser(string email, string displayName, string password)
{
    var userToBeAdded = new User
    {
        AccountEnabled = true,
        Identities = new List<ObjectIdentity>
        {
            new ObjectIdentity
            {
                SignInType = Constants.SignInTypeEmail,
                Issuer = _tenantId,
                IssuerAssignedId = email
            }
        },

        DisplayName = displayName,

        PasswordProfile = new PasswordProfile
        {
            Password = password,
            ForceChangePasswordNextSignIn = false
        },
        PasswordPolicies = Constants.DisablePasswordExpirationPolicy
    };
    var graphServiceClient = new GraphServiceClient(_authProvider);
    var addedUser = await graphServiceClient.Users.Request().AddAsync(userToBeAdded);
    return addedUser.Id;
}
``` 
[AB#7156](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7156)

**Comment by VictorioBerra** [comment]
I get this if I create the user in the UI and then try and run them through a sign in flow. I dont get it if I run them through a register flow first.

**Comment by maisarissi** [comment]
Hi @arek-avanade . We deeply appreciate your feedback and I'm so sorry for the late response.
This appears to be an issue with the service API. This repository is specific to the .NET library. Questions about the service API or configuration should be posted to Microsoft Q&A and tagged with one of [microsoft-graph-*](https://docs.microsoft.com/en-us/answers/search.html?c=&includeChildren=&f=&type=question+OR+idea+OR+kbentry+OR+answer+OR+topic+OR+user&redirect=search%2Fsearch&sort=relevance&q=microsoft-graph-*) tags.

With that said, I want to add that it could be within the normal range if you are seeing it for few seconds. It can take several minutes in some regions, or even longer if the shard hosting the tenant is under heavy write pressure. There are three types of retry strategies available [here](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#retry-strategies), it would be good to investigate which one provides the most benefit in your situation.
