### ISSUE TITLE
GraphServiceClient.DeviceManagement.Reports.CachedreportConfigurations.GetAsync() throws an error with 404 not found when it should return an empty collection

### ISSUE THREAD

**Issue by Chralex** [microsoftgraph/msgraph-beta-sdk-dotnet#659]
When using the referenced API: https://learn.microsoft.com/en-us/graph/api/intune-reporting-devicemanagementcachedreportconfiguration-list?view=graph-rest-beta  It returns a 404 not found.

```JSON
{
        "error": {
          "code": "ResourceNotFound",
          "message": "{  _version: 3,  Message: An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: b7b00caf-df82-4d9e-bc3e-6fb05f89c581 - Url: https://fef.msub06.manage.microsoft.com/ReportingService/StatelessReportingFEService/deviceManagement/reports/cachedReportConfigurations?api-version=5021-09-01,  CustomApiErrorPhrase: ,  RetryAfter: null,  ErrorSourceService: ,  HttpHeaders: {}}",
          "innerError": {
            "date": "2023-05-17T11:08:20",
            "request-id": "e5ae5a27-bf4f-420c-bf29-815c79693118",
            "client-request-id": "b7b00caf-df82-4d9e-bc3e-6fb05f89c581"
          }
      }
 }
```

Here is the code from Graph SDK Beta that I am using to call the API:

```C#
using (GraphServiceClient client = new GraphServiceClient(clientCredentialsAuthProvider))
{
    var collection = await client.DeviceManagement.Reports.CachedReportConfigurations.GetAsync();
}
```
If we look at the API documentation it should return a collection, i.e. the collection should just be empty, and not null.

**Comment by andrueastman** [comment]
Thanks for raising this @Chralex 

As the beta API may change routes, Any chance you can replicate this on the Graph Explorer? Can you also confirm the version of the SDK you are using to make the request?

**Comment by Chralex** [comment]
Hi there @andrueastman, the code uses `Microsoft.Graph.Beta 5.29.0-preview`. I haven't used the Graph Explorer before, so I will try to look into it on Monday and give you a response on that,

**Comment by Chralex** [comment]
Hi again @andrueastman, on the Graph Explorer I get what looks to be the same 404 not found response code and this JSON response body:

```json
{
    "error": {
        "code": "ResourceNotFound",
        "message": "{  \"_version\": 3,  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 686c1c9b-1e04-e1a7-35b8-e22f496b21ff - Url: https://fef.msub06.manage.microsoft.com/ReportingService/StatelessReportingFEService/deviceManagement/reports/cachedReportConfigurations?api-version=5021-09-01\",  \"CustomApiErrorPhrase\": \"\",  \"RetryAfter\": null,  \"ErrorSourceService\": \"\",  \"HttpHeaders\": \"{}\"}",
        "innerError": {
            "date": "2023-06-05T16:18:55",
            "request-id": "caacfee4-f4d1-4870-9528-90b7f779bd15",
            "client-request-id": "686c1c9b-1e04-e1a7-35b8-e22f496b21ff"
        }
    }
}
```
The URL that it uses is: GET `https://graph.microsoft.com/beta/deviceManagement/reports/cachedReportConfigurations`
Just for convenience: 
* Here is the documentation for the type of object that is expected to be returned in the collection: https://learn.microsoft.com/en-us/graph/api/resources/intune-reporting-devicemanagementcachedreportconfiguration?view=graph-rest-beta
* Here is the documentation for the call: https://learn.microsoft.com/en-us/graph/api/intune-reporting-devicemanagementcachedreportconfiguration-list?view=graph-rest-beta

I can see that this API does not exist in v1.0, so maybe it just isn't implemented yet?

Just to inform: This feature requires an Intune license, and the tenant that I am using does have an Intune license. I am using other API calls to successfully generate reports, so I am trying to use this because I want to figure out if reports are being cached when I produce them from the API, and to see if I can use the API for cached reports.

**Comment by andrueastman** [comment]
Thanks for the feedback here @Chralex 

As this looks to be an issue from the API end(and this repo mainly deals with SDK related issues), any chance you can post the issue at the link below so that we may get feedback from the relevant API owner? It would be great if you could post back the link here as well so that anyone else coming across this may also find the information.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by Chralex** [comment]
Hi @andrueastman. 

As you have instructed I have opened a question on the website in the link that you gave:

[https://learn.microsoft.com/en-us/answers/questions/1303433/beta-devicemanagement-reports-cachedreportconfigur](https://learn.microsoft.com/en-us/answers/questions/1303433/beta-devicemanagement-reports-cachedreportconfigur)

I hope they can help me out, and thank you for pointing me to the right place. 

Unless you'd like to keep this post open for tracking that question, you're welcome to close it.

Thank you.
