### ISSUE TITLE
Create TrustFrameworkKeySet fails

### ISSUE THREAD

**Issue by anielii** [microsoftgraph/msgraph-beta-sdk-dotnet#67]
#### Issue description
It is not possible to create a TrustFrameworkKeySet using .NET SDK.

#### Steps to reproduce the issue
1. Try to create a new KeySet using .NET SDK version 0.12-preview
```
await _graphServiceClient
        .TrustFramework
        .KeySets
        .Request()
        .AddAsync(new TrustFrameworkKeySet()
        {
            Id = keySetId
        });

```

#### What's the expected result?
The KeySet with the provided id should be created.

#### What's the actual result?
A 400 response is returned. 
```
{
  "error": {
    "code": "AADB2C",
    "message": "The 'keySet' field is invalid in request. Please check the request body and parameters.",
    "innerError": {
      "correlationId": "9338f5c7-f06b-4543-87fb-95dd56e61a16",
      "date": "2020-02-07T06:36:56",
      "request-id": "76b0c8a4-f82d-4e01-bcf2-8dd391c82945"
    }
  }
}
```
#### Additional information
If I try to create a KeySet using plain REST API it works fine.

.NET SDK adds an additional field to the request body: **"@odata.type":"microsoft.graph.trustFrameworkKeySet"**

If I add the same field to the plain REST API request my request also fails with the same error message.
 
[AB#7158](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7158)

**Comment by MIchaelMainer** [comment]
The service should handle the OData type. As a workaround, please set it to null.

```csharp
await _graphServiceClient
        .TrustFramework
        .KeySets
        .Request()
        .AddAsync(new TrustFrameworkKeySet()
        {
            Id = keySetId,
            ODataType = null
        });
```

**Comment by andrueastman** [comment]
This is resolved via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/296 and https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534 and should now be available through https://www.nuget.org/packages/Microsoft.Graph.Beta/4.4.0-preview
