### ISSUE TITLE
Managed Identity service principal not returned from Graphserviceclient.Servicepricipals[objectId].GetAsync

### ISSUE THREAD

**Issue by NaraVen** [microsoftgraph/msgraph-beta-sdk-dotnet#675]
User managed Identity and System Identity are not returned when their object Id is used to get from Graphserviceclient.Servicepricipals[objectId].GetAsync(). However app registrations are returned.
What should we call to get the managed identity's details.

**Comment by andrueastman** [comment]
Thanks for raising this @NaraVen 

As this sounds to be an API related query as the values returned are determined by the API, any chance you could post the question at the link below so as to get feedback from the relevant API team on how to use the ids for System Identity and User managed Identity. It would also be great if you could post back a link to the same here incase someone with the same question comes across this as well. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
