### ISSUE TITLE
AddAsync(team) returns null even though this is supposed to be the preferred way to create a Team now

### ISSUE THREAD

**Issue by MattEHopkins** [microsoftgraph/msgraph-beta-sdk-dotnet#68]
Creating a Team with the API is supposed to now be a long running operation, and we are told to request status, however the call to AddAsync returns null.

var asyncOp = await graphClient.Teams.Request().WithMaxRetry(maxRetry).AddAsync(team); 

even though the Team is created. 
[AB#7159](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7159)

**Comment by peombwa** [comment]
This is by design, but we are working on making it better.

**Comment by element8763** [comment]
so what is the best process to get the team id after a new team team is requested?

**Comment by markhbrown** [comment]
Hello.

I'm using the nuget package:

Teams.Request().AddAsync still doesn't return the newly created team or at the very least the id.  I can't access the headers via the nugget package either and therefore can't get the teamid as if I was to just use HttpClient.

My only option is to create group then convert that to a team - however the doc state that this will be deprecated soon.

When will Teams.Request().AddAsync return the id / team object?

Thanks

Mark
