### ISSUE TITLE
Efficiently Identifying Real Changes in High-Volume Data Environment

### ISSUE THREAD

**Issue by thomas-illiet** [microsoftgraph/msgraph-beta-sdk-dotnet#680]
Hello @andrueastman,

I'm contacting you today about an issue my client is experiencing with the Microsoft Graph API.

> **Context:** We have a tenant with over 800,000 objects (User / devices / groups), which is quite large (yum yum yum yum yum).
> We frequently need to extract data for purposes such as KPIs, risk analysis, remediation, and more.

To export all Azure AD users, we are currently experiencing long waiting times of over 40 minutes and even more than 30 minutes for certain license groups (without delta feature)

After reading the Microsoft documentation, I found a feature that solves my problem in theory ! The Delta feature (_One feature to rule them all, one feature to find them, One feature to bring them all, and in the darkness bind them_)

I have developed a C# solution using the Hangfire framework to handle delta update events.
To create a cache of Microsoft objects with the smallest possible delta and avoid performing full synchronization, I have implemented a mechanism that efficiently tracks and updates only the changed data.

During the initialization of the delta token, I specifically select only the desired property to minimize the size of the delta response. This approach helps optimize the data transfer and retrieval process. I have encountered a significant issue during the implementation......

I am experiencing a high volume of updates throughout the day, ranging from 10 to 15 million, and it turns out that approximately 90% of these updates do not have any differences compared to my existing cache.

Therefore, the selection of properties does not have any impact on the tracking of changes to obtain a delta. Despite specifying the desired properties, it appears that the majority of updates do not affect the tracked data in our cache.

Do you have a solution to get a real update?

Kind regards
Thomas

**Comment by andrueastman** [comment]
Apologies for the delayed response @thomas-illiet 

Out of curiosity, any chance you are using the page iterator for this? 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#skiptoken-and-deltatoken-query-parameters-in-delta-requests

As you reported similar data, is there a chance that the nextLink being returned is the same as the one made in previous request?
