### ISSUE TITLE
Pagination do not work in DeviceManagement.ManagedDevices.GetAsync

### ISSUE THREAD

**Issue by tkachuk2222** [microsoftgraph/msgraph-beta-sdk-dotnet#681]
I am using Microsoft.Graph.Beta 5.34.0-preview

code:
`var devices = await graphClient.DeviceManagement.ManagedDevices.GetAsync(configuration =>
                        {
                            configuration.Headers.Add("ConsistencyLevel", "eventual");
                            configuration.QueryParameters.Orderby = new[] { "id" };
                            configuration.QueryParameters.Skip = 1000;
                        });`

After skipping 1000 I am expecting to get the next page of devices, but instead, I am getting an empty array of Values. 
So currently it is possible to get only the first 999 items

**Comment by andrueastman** [comment]
Thanks for raising this @tkachuk2222 

Any chance you can confirm if the `devices.OdataNextLink` is null when you make the request? 
Are you able to replicate this on [the Graph explorer](https://aka.ms/ge) and confirm that you have more than 1000 ManagedDevices?

**Comment by tkachuk2222** [comment]
> Thanks for raising this @tkachuk2222
> 
> Any chance you can confirm if the `devices.OdataNextLink` is null when you make the request? Are you able to replicate this on [the Graph explorer](https://aka.ms/ge) and confirm that you have more than 1000 ManagedDevices?

OdataNextLink is not null:
![image](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/20381930/b33ee2a6-6ee6-4b31-abea-13ff36101119)

I know for sure there are more than 1000 devices. BTW I can get total count of devices using the next code:
` var totalDeviceCount = await graphClient.DeviceManagement.ManagedDevices.GetAsync(configuration =>
                {
                    configuration.Headers.Add("ConsistencyLevel", "eventual");
                    configuration.QueryParameters.Count = true;
                });`

I can't try to execute the same request on the Graph Explorer due to security policies. Also old Nuget package (4.xx.x-preview version) could get all devices, regardless of their quantity

**Comment by andrueastman** [comment]
Thanks for the extra information @tkachuk2222 

> Also old Nuget package (4.xx.x-preview version) could get all devices, regardless of their quantity

Just to confirm with the older version did you provide the Top and Skip query options parameters as well?

**Comment by andrueastman** [comment]
I believe you should be using the pageiterator as below.
https://learn.microsoft.com/en-us/graph/sdks/paging?tabs=csharp

Any chance this works for you?
```cs
            var numberOfComputers = 0;
            var computers = new List<ManagedDevice>();
            //get the first page
            var devices = await graphClient.DeviceManagement.ManagedDevices.GetAsync(configuration => 
            { 
                configuration.Headers.Add("ConsistencyLevel", "eventual"); 
                configuration.QueryParameters.Orderby = new[] { "id" };
                configuration.QueryParameters.Skip = 1000; 
            });

            
            var pageIterator = PageIterator<ManagedDevice, ManagedDeviceCollectionResponse>.CreatePageIterator(graphClient, devices, (device) => 
            {
                numberOfComputers++;//increment 
                computers.Add(device);// add devices.
                return true;
            });

            await pageIterator.IterateAsync();// iterate to last page

            Console.WriteLine("Computers number: " + numberOfComputers);
            Console.WriteLine("Computers list number: " + computers. Count);
```

**Comment by tkachuk2222** [comment]
> I believe you should be using the pageiterator as below. https://learn.microsoft.com/en-us/graph/sdks/paging?tabs=csharp
> 
> Any chance this works for you?
> 
> ```cs
>             var numberOfComputers = 0;
>             var computers = new List<ManagedDevice>();
>             //get the first page
>             var devices = await graphClient.DeviceManagement.ManagedDevices.GetAsync(configuration => 
>             { 
>                 configuration.Headers.Add("ConsistencyLevel", "eventual"); 
>                 configuration.QueryParameters.Orderby = new[] { "id" };
>                 configuration.QueryParameters.Skip = 1000; 
>             });
> 
>             
>             var pageIterator = PageIterator<ManagedDevice, ManagedDeviceCollectionResponse>.CreatePageIterator(graphClient, devices, (device) => 
>             {
>                 numberOfComputers++;//increment 
>                 computers.Add(device);// add devices.
>                 return true;
>             });
> 
>             await pageIterator.IterateAsync();// iterate to last page
> 
>             Console.WriteLine("Computers number: " + numberOfComputers);
>             Console.WriteLine("Computers list number: " + computers. Count);
> ```

Yes, it works! Thanks!
