### ISSUE TITLE
Connection activity settings not accepting payload from Graph SDK

### ISSUE THREAD

**Issue by zwright-2** [microsoftgraph/msgraph-beta-sdk-dotnet#694]
**Describe the bug**
When Activity settings properties are in pascal case (upper camel case), the Graph SDK throws an Odatatype error with a status code of 400. If the properties are in lower camel case, they are able to be accepted as properties within a valid payload.

POST https://[graph.microsoft.com/beta/external/connections](https://graph.microsoft.com/beta/external/connections)

**To Reproduce**
Call Graph API with Activity Settings properties formatted in pascal case.

**Expected behavior**
The Activity settings property as well as its associated nested properties should be able to be accepted as valid properties within payload.

**Actual Behavior**
Deserialization/Odatatype error with a status code of 400. "Request is malformed or incorrect".

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Version: "Microsoft.Graph.Beta" Version="5.38.0-preview

**Comment by andrueastman** [comment]
Closing as this is now resolved.
