### ISSUE TITLE
List Transcripts reports Microsoft.Graph.Beta.Models.ODataErrors.ODataError

### ISSUE THREAD

**Issue by opcfoundation-org** [microsoftgraph/msgraph-beta-sdk-dotnet#695]
Have used a number of variations to fetch the transcript but always get an exception.
Same error with delegated and application credentials.
Application has permissions:
OnlineMeetingTranscript.Read.All 
OnlineMeetingArtifact.Read.All 
Can access attendee list and recordings.
Using Microsoft.Graph.Beta 5.39.0-preview

```
var transcripts = await m_graphClient
    .Users[user.Id]
    .OnlineMeetings[transcript.CallId]
    .Transcripts.GetAsync();

foreach (var t in transcripts.Value)
{
    Console.WriteLine($"{t.Id} '{t.CreatedDateTime}'");
}
```

**Comment by andrueastman** [comment]
Thanks for raising this @opcfoundation-org 

Any chance you are able to share the error details once you follow the guindance below to get the API error and code?

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md#handling-errors-in-the-microsoft-graph-net-client-library

**Comment by opcfoundation-org** [comment]
Thanks. That gave me useful debugging information:

```
BadRequest
Channel based meetings are currently not supported.
```

Any idea when the API will support channel based meetings? It is a necessary feature for us.

**Comment by andrueastman** [comment]
> Any idea when the API will support channel based meetings? It is a necessary feature for us. Also the API seems to be missing a way to select vtt/docx. What does it return if it works?

As this repo is mainly intended for issues related to the SDK, we may not be best placed to answer API related quesions. Any chance you can post the same question at the link below to get feedback from the API owners?
It would be great if you post the question link back here a comment so that anyone who comes across this may also benefit from the info.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by opcfoundation-org** [comment]
Posted feature request here:

https://learn.microsoft.com/en-us/answers/questions/368675/graph-api-meeting-recording-and-transcript?page=1&orderby=helpful&comment=answer-974058
