### ISSUE TITLE
Graph SDK V5: graphClient.DeviceAppManagement.MobileApps.Count.GetAsync throw an ODataError exception

### ISSUE THREAD

**Issue by DCourtel** [microsoftgraph/msgraph-beta-sdk-dotnet#697]
`
_graphClient.DeviceAppManagement.MobileApps.Count.GetAsync(requestConfiguration =>
                {
                    requestConfiguration.QueryParameters.Filter = "isOf('microsoft.graph.win32LobApp')";
                });
`

throw an ODataError exception with message: _No OData route exists that match template ~/singleton/navigation/$count with http verb GET for request /AppLifecycle_2307/StatelessAppMetadataFEService/deviceAppManagement/mobileApps/$count._
Same if I remove the filter.

**Comment by andrueastman** [comment]
Thanks for raising this @DCourtel 

The API route may not be valid from the API side as much as it is described in the metadata. 

Any chance you can confirm if you can confirm if the request can bee performed successfully on graph Explorer?

**Comment by DCourtel** [comment]
Thanks for your feedback.
With this URL: https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/$count?%24filter=isOf%28%27microsoft.graph.win32LobApp%27%29
I get the same message
> No OData route exists that match template ~/singleton/navigation/$count with http verb GET for request /AppLifecycle_2307/StatelessAppMetadataFEService/deviceAppManagement/mobileApps/$count.

Is it planned to get $Count implemented for MobileApps?

**Comment by andrueastman** [comment]
The count can be retrieved using the $count query parameter. 

```cs
         var result = await graphClient.DeviceAppManagement.MobileApps.GetAsync((requestConfiguration) =>
         {
             requestConfiguration.QueryParameters.Filter = "isOf('microsoft.graph.win32LobApp')";
             requestConfiguration.QueryParameters.Count = true;
         });

         var countString = result.OdataCount;
```

**Comment by DCourtel** [comment]
Thanks for your feedback. Unfortunately, this query returns a MobileAppCollectionResponse with ODataCount set to 0 and the Value property contains an enumeration of MobileApp.
I would like to have a very light query that only returns the count, not all instances of MobileApp.

![image](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/13787283/a2c4a859-96cd-4beb-9e77-2a0825a85d26)

**Comment by andrueastman** [comment]
@DCourtel Are you by any chance able to make the same request on the graph explorer and confirm that the "@odata.count" property is still 0 despite having results?

**Comment by DCourtel** [comment]
The URL generated by the SDK is the following: 
https://graph.microsoft.com/beta/deviceAppManagement/mobileApps?$filter=isOf%28%27microsoft.graph.win32LobApp%27%29&$count=true

And the result in Graph Explorer is the same:

```JSON
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#deviceAppManagement/mobileApps",
    "@odata.count": 0,
    "@microsoft.graph.tips": "Use $select to choose only the properties your app needs, as this can lead to performance improvements. For example: GET deviceAppManagement/mobileApps?$select=createdDateTime,dependentAppCount",
    "value": [
        {
            "@odata.type": "#microsoft.graph.win32LobApp",
            "id": "4783d5d8-81a0-48fe-97e3-b358ef2b9d87",

```

**Comment by andrueastman** [comment]
Thanks for confirming @DCourtel 

Any chance you can create an feedback request at the link below for $count support as it seems that the API doesn't seem to support this yet? This will enable the API owners to give feedback on when this will be supported. It would be great if you could post a link of the same as a comment so that anyone who comes across this may be able to upvote it. 

https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80

**Comment by DCourtel** [comment]
Here you go: [feedback](https://feedbackportal.microsoft.com/feedback/idea/7102e27c-7d87-ee11-a81c-000d3ae46fcb)

**Comment by andrueastman** [comment]
Thanks for this. We'll close this for now so that this may be follow up there.
