### ISSUE TITLE
Expanding detected apps does not work

### ISSUE THREAD

**Issue by Technomann** [microsoftgraph/msgraph-beta-sdk-dotnet#701]
Hi!

I wanted to query the managed devices and all the detected apps per device.

For this, I used the following query:

```
var managedDevices = (await client.DeviceManagement.ManagedDevices.GetAsync((configuration) =>
        {
            configuration.QueryParameters.Expand= new string[] { "detectedApps" };
        }, cancellationToken: cancellationToken)).Value;
The DetectedApps property of each device showed an empty list.
```

Windows 11
Beta SDK 5.11.0

**Comment by andrueastman** [comment]
Thanks for raising this @Technomann,

As `detectedApps` is a navigation property it may not support the expand query option on it. 
As this is an API related feature, this can be confirmed by asking the question at the link below to confirm the same from the API team(https://learn.microsoft.com/en-us/answers/tags/161/ms-graph). 

You may be able to get the detected apps for a given managed device as below.
```cs
var detectedApps = await graphClient.DeviceManagement.ManagedDevices["device-id"].DetectedApps.GetAsync();
```
