### ISSUE TITLE
Querying single detected application throws Microsoft.Graph.Beta.Models.ODataErrors.ODataError exception

### ISSUE THREAD

**Issue by Technomann** [microsoftgraph/msgraph-beta-sdk-dotnet#703]
First, I queried managed devices, then I queried all detected apps on these devices.
I have the Id for each app.

I want to query one app, to get it's publisher, because using ```expand``` does not work.

I use the following query:
```
await client.DeviceManagement.DetectedApps[app.Id].GetAsync(configuration =>
{
    configuration.QueryParameters.Expand = new string[] { "publisher" };
}, cancellationToken: cancellationToken);
```

When executing this query, I receive the following error, without any sensible message or error code:
Exception thrown: 'Microsoft.Graph.Beta.Models.ODataErrors.ODataError' in System.Private.CoreLib.dll ("") | Microsoft.Graph.Beta.Models.ODataErrors.ODataError

SDK version: Beta 5.42.0-preview
Windows 11
Visual Studio 2022 17.6.5

**Comment by andrueastman** [comment]
Thanks for raising this @Technomann,

As `publisher` is a simple property, I believe you should use select. Any chance the following works out for you? 

```cs
await client.DeviceManagement.DetectedApps[app.Id].GetAsync(configuration =>
{
    configuration.QueryParameters.Select = new string[] { "publisher" };
}, cancellationToken: cancellationToken);
```

**Comment by Technomann** [comment]
I will try this.
