### ISSUE TITLE
Build Error: The field, constructor or member 'Agreements' is not defined

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/msgraph-beta-sdk-dotnet#71]
Even though I have installed Microsoft.Graph.Beta (through Nuget Package Manager) and IntelliSense of Visual Studio 2019 detects/accepts graphClient.Agreements (doesn't show any errors) I can't compile the project. In the output window I get the error message ```The field, constructor or member 'Agreements' is not defined``` but the Error list shows 0 Errors.
By the way, when you change windows language settings IntelliSense also loses the capability of recognizing .Agreements - after reinstalling the Nuget Package it "worked" again

My code looks something like this:
```fs
open Microsoft.Graph
[...]

[<EntryPoint>]
let main argv =
    let confidentialClientApplication = ConfidentialClientApplicationBuilder.Create(settings.clientId).WithTenantId(settings.tenantId).WithClientSecret(settings.secret).Build();
    
    let authProvider = new ClientCredentialProvider(confidentialClientApplication)

    let graphClient = new GraphServiceClient(authProvider)

    //Here's the "Agreements" part that is picked up by intellisence but is not compileable
    let agreements = graphClient.Agreements.Request().GetAsync().Result
```

IntelliSense:
![image](https://user-images.githubusercontent.com/45571948/74659438-9f6dbc00-5194-11ea-87ce-7befd9cf1494.png)

Compiler:
```
1><Path>\Program.fs(72,33): error FS0039: The field, constructor or member 'Agreements' is not defined.
1>Done building project "Project.fsproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```
 
[AB#7162](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7162)

**Comment by andrueastman** [comment]
Closing this as this is defined [here](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/fce4f2bf18082cfc5996437520d9c6d22ef1d6b4/src/Microsoft.Graph/Generated/requests/GraphServiceClient.cs#L588).
Build error does not occur with latest package versions.
