### ISSUE TITLE
Cannot run along side the non beta in .net core on OSX

### ISSUE THREAD

**Issue by mpjones84** [microsoftgraph/msgraph-beta-sdk-dotnet#72]
<Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Microsoft.Graph.Beta'">
        <Aliases>BetaLib</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>

Does not work.

I also don't understand how the version is higher for Microsoft.Graph.  
[AB#7165](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7165)

**Comment by peombwa** [comment]
What error are you getting?
Can you elaborate on what you mean by it doesn't work?

**Comment by mpjones84** [comment]
Sorry yes, I am unable to use the alias betalib. Would you like a screen shot?

**Comment by mpjones84** [comment]
Sorry yes, I add the Target to the csproj.  But I cannot use the alias in the namespaces.

 The extern alias 'BetaLib' was not specified in a /reference option

```c
extern alias BetaLib;
using Beta = BetaLib.Microsoft.Graph;
```

**Comment by andrueastman** [comment]
@mpjones84 In your .csproj you will need to update the `PackageReference` section specifying the `Microsoft.Graph.Beta` package to have the relevant alias. It should therefore look like this.

```
    <PackageReference Include="Microsoft.Graph.Beta" Version="4.4.0-preview">
      <Aliases>BetaLib</Aliases>
    </PackageReference>
```
Please feel free to reopen the issue if you need any more clarification.
