### ISSUE TITLE
Unable to pull IdentityRisk events

### ISSUE THREAD

**Issue by mjanulaitis** [microsoftgraph/msgraph-beta-sdk-dotnet#723]
I am using Microsoft.Graph.Beta 5.25.0-preview and Microsoft.Graph.Core 3.0.5 and am unable to pull IdentityRisk events from some Client ID/Tenant IDs with the following error:

You cannot perform the requested operation, required scopes are missing in the token.

  at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<ThrowIfFailedResponse>d__28.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Graph.Beta.RiskDetections.RiskDetectionsRequestBuilder.<GetAsync>d__4.MoveNext()

```
var f = $"ActivityDateTime ge {startDT.ToUniversalTime():yyyy-MM-ddTHH:mm:ss.fffZ}";

List<RiskDetection>? auditLogRoot = null;
try
{
    var response = await graphClient.RiskDetections.GetAsync(rc =>
    {
        rc.QueryParameters.Filter = f;
        rc.QueryParameters.Orderby = new[] { "ActivityDateTime asc" };
    });
    auditLogRoot = response.Value;
}
catch (ODataError ex)
{
}
```

I am able to pull the Audit and SignIn logs without issue.

**Comment by andrueastman** [comment]
Thanks for raising this @mjanulaitis 

According to the docs, you need the `IdentityRiskEvent.Read.All` permissions/scopes added to you application. Any chance you can confirm if this is the case?

https://learn.microsoft.com/en-us/graph/api/riskdetection-list?view=graph-rest-beta&tabs=http#permissions
