### ISSUE TITLE
Update Android and iosManagedAppProtections returns No Content - 204 instead of OK - 200

### ISSUE THREAD

**Issue by dansmitt** [microsoftgraph/msgraph-beta-sdk-dotnet#738]
The documentation says, that an update of an Android or iosAppProtection should return an OK - 200 and the updated ManagedAppProtection, it  returns a No Content - 204.

We really need to get back the updated ManagedAppProtection.

Call: https://graph.microsoft.com/v1.0/deviceAppManagement/androidManagedAppProtections/{androidManagedAppProtectionId}
Request body: 

``` JSON
{
    "description": "Description Android"
}
```

Documentation: https://learn.microsoft.com/en-us/graph/api/intune-mam-androidmanagedappprotection-update?view=graph-rest-1.0&tabs=http

Happend for me in Microsoft.Graph.Beta 4.74.0-preview

We cannot upgrade so far cuz the breaking changes are to big for us at the moment.

![Screenshot](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/62943030/ae001099-cafa-4728-9f36-50f4b73f5edc)

**Comment by andrueastman** [comment]
Thanks for raising this @dansmitt 

As this is behavior related to the API side functionality and this repo is mainly intended for SDK related issues, I've created https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8701 for the API team to follow up on whether the documentation is incorrect or the API response needs fixing. 

We'll close this issue for now and follow up on the documentation/API issue from https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8701 for now.
