### ISSUE TITLE
[Trimming] Make Microsoft.Graph.Beta for .NET trimming compatible.

### ISSUE THREAD

**Issue by chrisgriffis** [microsoftgraph/msgraph-beta-sdk-dotnet#748]
## Is your feature request related to a problem? Please describe.

Yes, We're (@robsonpontin) writing a WinUI 3 Application (using Windows App SDK) which must be published as trimmed since .NET supports it, but the Microsoft.Graph dependency does not support it and give me trim warnings.

## Describe the solution you'd like

Fix all cases using reflection and every single trim warning to make the SDK fully trimmable.
This is a requirement for Native AOT which is coming soon for Windows App SDK with .NET 8.

## Describe alternatives you've considered

The alternative would be not using the .NET SDK but using REST API instead, but we should strive to improve the SDK instead.

## Additional context
link to the completed request in release/v1.0 sdk
[[Trimming] Make Microsoft.Graph for .NET trimming compatible.](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2111)

**Comment by andrueastman** [comment]
Thanks for raising this @chrisgriffis 

I believe this should have been resolved with https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/746 and available via https://www.nuget.org/packages/Microsoft.Graph.Beta/5.53.0-preview. 
Any chance you can confirm if you have any issues with the latest release?

**Comment by andrueastman** [comment]
Confirmed as resolved
