### ISSUE TITLE
.NET 8 support

### ISSUE THREAD

**Issue by VladislavAntonyuk** [microsoftgraph/msgraph-beta-sdk-dotnet#757]
error NU1107:  WebApp -> Microsoft.Graph.Beta 5.55.0-preview -> Microsoft.Graph.Core 3.1.1 -> Microsoft.Kiota.Http.HttpClientLibrary 1.3.0 -> System.Text.Json (>= 6.0.0 && < 8.0.0)

**Comment by andrueastman** [comment]
Thanks for raising this @VladislavAntonyuk 

We're tracking this via https://github.com/microsoft/kiota-serialization-json-dotnet/issues/105. So we'll close this for now as a duplicate and resolve this soon.
