### ISSUE TITLE
Cannot get PoneMethods for user; result is always empty

### ISSUE THREAD

**Issue by codefactorydevelopment** [microsoftgraph/msgraph-beta-sdk-dotnet#759]
We have an adb2c where users have defined their MFA and entered mobile phone numbers.
When user is trying to login, adb2c does send sms to the phone number and authentication works.

On the other hand, when we try to get authentication methods for that same user through Graph SDK, we always get empty result.

We request it like:
`graphClient.Users[id].Authentication.PhoneMethods.GetAsync()`

That request always returns empty result.

On the other hand, when we try:
`graphClient.Users[id].Authentication.Methods.GetAsync()`

it returns only `passwordMethod` just like `phoneMethods` are not defined at all.

And again, we are sure they are defined and they work when logging in.

We use `Microsoft.Graph 5.33.0`

**Comment by andrueastman** [comment]
Thanks for raising this @codefactorydevelopment 

According to the API documentaion, listing the PhoneMethods only seems to be available for standard Microsoft Entra ID and B2B users, but not B2C users.

https://learn.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&tabs=http

Any chance you can confirm the same if you make the request for documented type of users?
