### ISSUE TITLE
 DeviceManagementScript : createdDateTime/lastModifiedDateTime attributes

### ISSUE THREAD

**Issue by billgatesfan** [microsoftgraph/msgraph-beta-sdk-dotnet#769]
I am trying to serialize a [DeviceManagementScript ](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/05934aed87408a28f015dad08759b0f0dae538e0/src/Microsoft.Graph/Generated/Models/DeviceManagementScript.cs#L211) object using Kiota serializer, but I could not obtain their createdDateTime/lastModifiedDateTime attributes, because it seems they are missing from the Serialize method.

...while both properties exists for other classical objects : [DeviceConfiguration.cs](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/05934aed87408a28f015dad08759b0f0dae538e0/src/Microsoft.Graph/Generated/Models/DeviceConfiguration.cs#L394), or [MobileApp.cs](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/05934aed87408a28f015dad08759b0f0dae538e0/src/Microsoft.Graph/Generated/Models/MobileApp.cs#L336), or  [DeviceCompliancePolicy.cs](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/05934aed87408a28f015dad08759b0f0dae538e0/src/Microsoft.Graph/Generated/Models/DeviceCompliancePolicy.cs#L218)

May I ask if there is a reason why it is so? Would you have maybe a hint for me, how to get them into my stringified JSON?

**Comment by andrueastman** [comment]
Thanks for raising this @billgatesfan 

For context, the SDK is generated from the API metadata availalble at https://graph.microsoft.com/beta/$metadata. From this metadata, the properties are marked as readonly as meaning that they shouldn't be serialized when being sent back to the API in the event that they are serialized. 

<img width="914" alt="image" src="https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/6464005/bf3eda12-2904-447a-97f3-4862a8ba7269">

However, if you did wish for the property to show up in the json during serailization, you could add it to the AdditionalData bag before you serialize it to get the property seriliazed as below.

```cs
deviceManagementScript.AdditionalData["createdDateTime"] = deviceManagementScript.CreatedDateTime;
var jsonString = KiotaJsonSerializer.SerializeAsString(deviceManagementScript);
```

**Comment by billgatesfan** [comment]
Thx, I wasn't aware of this metadata concept.   So would you say there is no reason as well, that _createdDateTime/lastModifiedDateTime_ properties should be serialized in the last 3 objects I mentioned? 

With help of your XML metadata document, I noticed another similar (bigger) problem for me for the [managedDevice ](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/cccb9011b2e0daf8604008e989c8ae8c2d3dd32e/src/Microsoft.Graph/Generated/Models/ManagedDevice.cs#L1094C8-L1094C8) object : there are 33 "public string" properties, and only 3 of them are serialized. The most important ones, like _OsVersion,  OperatingSystem, Imei, SerialNumber, AzureADDeviceId/AzureActiveDirectoryDeviceId, DeviceName, Manufacturer, Model,_ are not in the Serialize method.

To be able to use MSGraphSDK and serialize this managedDevice object using Kiota, is my understanding correct that I need, prior to call KiotaJsonSerializer.SerializeAsString(...), to add custom code to read every missing property for this class, and re-setting it manually in the AdditionalData bag? Is this sth you could bring in future SDK versions? Parsing this XML metadata to find out which object property was not flagged to be serialized in the SDK, is also a path I would like to avoid 😉.

Waiting for your feedback @andrueastman, as it is hard for me to identify whether this is simply "work in progress", or if these are "bugs" because _Workload owners_ did not yet finish to [flag some of the properties as readonly](https://github.com/microsoftgraph/msgraph-metadata/issues/128).

**Comment by andrueastman** [comment]
>So, would you say there is no reason as well, that createdDateTime/lastModifiedDateTime properties should be serialized in the last 3 objects I mentioned?

As they are lacking Computed annotations in the metadata, the properties would be assumed to be serializable. 

From the [metadata](https://graph.microsoft.com/beta/$metadata), I can also confirm that the properties you mentioned are also marked as read-only. Sample below
![image](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/6464005/b2a63926-108e-408e-b535-5fb732f14cd8)

Just to clarify my understanding here, is the purpose of serialization here to send the values back to the API (as the intent of them missing from the Serialize method is to avoid API errors from properties that the API owners have flagged as read-only) but to simply represent them in a JSON string? If a property is missing and it's blocking the sending of a valid API call, this would ideally need to be flagged as a metadata problem.
