### ISSUE TITLE
Graph SDK V5: Cannot access mobileAppDependency

### ISSUE THREAD

**Issue by DCourtel** [microsoftgraph/msgraph-beta-sdk-dotnet#783]
I cannot find any method to List, Get, Create, Delete, or Update a MobileAppDependency as defined here: [mobileAppDependency](https://learn.microsoft.com/en-us/graph/api/resources/intune-apps-mobileappdependency?view=graph-rest-beta)

Can you add methods to work with mobileAppDependency, please?

**Comment by andrueastman** [comment]
Thanks for raising this @DCourtel 

Any chance you can confirm these APIs are available in the v1 of graph. From the documentation they are only available in beta and you would need to pull the [beta package](https://www.nuget.org/packages/Microsoft.Graph.Beta) for this. 

With the beta package you should be able to access the methods such as 

```cs
var relationshipCollectionResponse = await graphClient.DeviceAppManagement.MobileApps["mobile-appid"].Relationships.GetAsync();
```

**Comment by DCourtel** [comment]
I already use the beta SDK and I don’t see any method to work with mobileAppDependency as described in the documentation.
But if we have to use the Relationships property and we are sure it will always contain only dependency relations, that’s fine.

**Comment by andrueastman** [comment]
I believe the documentation states the use of the path `GET /deviceAppManagement/mobileApps/{mobileAppId}/relationships` which is what the SDK exposes as described before. 

https://learn.microsoft.com/en-us/graph/api/intune-apps-mobileappdependency-list?view=graph-rest-beta
