### ISSUE TITLE
Graph SDK Beta V5: Bulk add a MobileAppId to several Windows10EnrollmentCompletionPageConfiguration

### ISSUE THREAD

**Issue by DCourtel** [microsoftgraph/msgraph-beta-sdk-dotnet#784]
I cannot find a way to add an AppId to several ESPs in one shot. I need to call the Patch method on each ESP. Which is inefficient and increases the risk of throttling.

For now, I use this in a foreach loop:

```C#
var patchingData = new Windows10EnrollmentCompletionPageConfiguration()
{
    SelectedMobileAppIds = new List<string>() { appId },
};
await _graphClient.DeviceManagement.DeviceEnrollmentConfigurations[esp.Id].PatchAsync(patchingData);
```

It works, but I’m afraid to kick the throttling mechanism in case there are many ESPs to edit.

**Comment by andrueastman** [comment]
Thanks for raising this @DCourtel 

>  add an AppId to several ESPs in one shot

Any chance you can confirm if you know if this is a scenario supported by the API? If not, I believe it would be better placed to ask if the API supports the scenario at the link below.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
