### ISSUE TITLE
Missing method  DeleteAsync from user photo Beta version 5.58.0 and onwards

### ISSUE THREAD

**Issue by edwinvandriel** [microsoftgraph/msgraph-beta-sdk-dotnet#809]
When upgrading the sdk from v5.58.0 and onwards the DeleteAsync methoc is missing when trying to delete a user photo.
The error is:
PhotoRequestBuilder' does not contain a definition for 'DeleteAsync' and no accessible extension method 'DeleteAsync' accepting a first argument of type 'PhotoRequestBuilder' could be found (are you missing a using directive or an assembly reference?)	

When trying to call this sdk code .Users[identifier].Photo.DeleteAsync()

https://learn.microsoft.com/en-us/graph/api/profilephoto-delete?view=graph-rest-beta&tabs=http

This worked perfectly until v5.57.0

**Comment by andrueastman** [comment]
This should have been resolved via https://github.com/microsoftgraph/msgraph-metadata/pull/594

@edwinvandriel Any chance you can confirm this is fixed in the latest version?

**Comment by edwinvandriel** [comment]
@andrueastman  Seems to be working fine now. Thank you!
