### ISSUE TITLE
Feature Request: Full functionality of Teams through the graph

### ISSUE THREAD

**Issue by salmanmkc** [microsoftgraph/msgraph-beta-sdk-dotnet#91]
I would like to be able to see messages from Teams, see threads, view call history, etc. through the graph. I know this applies to the whole graph as a whole as opposed to not just dotnet, but I couldn't file an issue for the whole org. I'd love to help test this and such, is this planned?

**Comment by MIchaelMainer** [comment]
Please use the [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) to upvote and request features.
