### ISSUE TITLE
Nearly every single method obsolete

### ISSUE THREAD

**Issue by VictorioBerra** [microsoftgraph/msgraph-beta-sdk-dotnet#918]
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/main/src/Microsoft.Graph/Generated/Me/MeRequestBuilder.cs

Not sure what I am supposed to use?

**Comment by shemogumbe** [comment]
Hello @VictorioBerra thanks for using the SDK and for raising this, is this stil a concern with the latest version of the SDK?

**Comment by WolfgangHG** [comment]
I can confirm that the warnings are gone.

**Comment by pansaravivek** [comment]
Was facing similar issue, it's looks resolved from the latest version.
