### ISSUE TITLE
ICloudCommunicationsRequestBuilder does not contain a definition for 'CallRecords' 

### ISSUE THREAD

**Issue by murtoza** [microsoftgraph/msgraph-beta-sdk-dotnet#95]
Hello,

I am using the package Microsoft.Graph.Beta, version 0.15.0.preview to get the CallRecored. Following is the code taken from https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-beta&tabs=csharp
```
var callRecord = await graphClient.Communications.CallRecords["{id}"]
	.Request()
	.Expand("sessions($expand=segments)")
	.GetAsync();
```

I am getting the following error

```
'ICloudCommunicationsRequestBuilder' does not contain a definition for 'CallRecords' and no accessible extension method 'CallRecords' accepting a first argument of type 'ICloudCommunicationsRequestBuilder' could be found
(are you missing a using directive or an assembly reference?)
```

Do I need to add any other package to get the CallRecords? 
[AB#7167](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7167)

**Comment by JeremyWalters** [comment]
I have encountered the same issue.

**Comment by svesax** [comment]
me too, any nres ??

**Comment by adnkai** [comment]
Same here. Any news on this?

**Comment by darrelmiller** [comment]
CallRecords has been added to Microsoft Graph in a different namespace.  This is a new capability in Microsoft Graph and currently the SDKs do not support multiple namespaces.  We are working to resolve this issue.

**Comment by davidjrh** [comment]
I'm currently using 0.25.0-preview and seems that this has now been included. Thanks!!!

**Comment by andrueastman** [comment]
Closing this as the issue has already been fixed through the addition of multiple namespace support.
