### ISSUE TITLE
Places request builder always returns "Unknown Error"

### ISSUE THREAD

**Issue by brothers28** [microsoftgraph/msgraph-beta-sdk-dotnet#97]
I try to get a RoomList via the Places request builder. My code looks as follow:
`var places = (Beta.RoomList)await graphServiceClient.Places.Request().GetAsync();`
I tried replicating the code from here https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&tabs=csharp#example-2-list-all-the-room-lists-defined-in-the-tenant but there are several small changes I needed to make in order to even execute the code. 
In the documentation it says to make a request builder as follows: `graphClient.Places.Microsoft.graph.roomlist...` but there is no such property as `Microsoft` on `Places`. So since it says in the documentation 

> Both room and roomList are derived from the place object.

I tried casting the result in a `RoomList` class. 

When I exectute this code I get the following error:
`Status Code: NotAcceptable`
`Microsoft.Graph.ServiceException: Code: UnknownError` 
`Inner error:`
	`AdditionalData:`
	`request-id: 91604eab-2800-409d-a4e0-0136af86fcd8`
	`date: 2020-04-16T09:11:40`
`ClientRequestId: 91604eab-2800-409d-a4e0-0136af86fcd8`

  ` at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)`
   `at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)`
   `at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)`
  ` at Microsoft.Graph.GraphServicePlacesCollectionRequest.GetAsync(CancellationToken cancellationToken)`

Used BetaVersion: 0.15-preview
Is this a reproducable issue or am I doing something wrong? 
[AB#7168](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7168)

**Comment by darrelmiller** [comment]
We are able to reproduce this issue in Graph Explorer, so it appears this is a service issue.  I have contacted the service owner to get more details.  /cc @vrod9429

**Comment by vrod9429** [comment]
Graph SDK does not currently support filtering by derived types. Here is a workaround for accessing a collections of rooms. 
var graphClient = new GraphServiceClient(authProvider);​

​

var roomsRequestUrl = graphClient.Places.AppendSegmentToRequestUrl("microsoft.graph.room") ;​

​

var placesRequest = new GraphServicePlacesCollectionRequest(roomsRequestUrl,graphClient,null);​

​

var places = await placesRequest.GetAsync();​

​

foreach(var place in places) {​

                Console.WriteLine(place.DisplayName);​

            }

**Comment by andrueastman** [comment]
This is related to https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/239.
I will close this issue so that the work can be tracked there.
