### ISSUE TITLE
Can (should) I use the Beta Graph API in a production system?

### ISSUE THREAD

**Issue by UweKeim** [microsoftgraph/msgraph-beta-sdk-dotnet#98]
Currently evaluating the v1.0 API for an upcoming project, I saw that I can do some things only with the Beta API.

I'm unsure about stability and changing interfaces when using the Beta API.

#### My question

Is it allowed and recommended to use the Beta API in a production environment?

From what I found is that the Beta API seems to [exist since at least 2015](https://docs.microsoft.com/de-de/graph/changelog#december-2015) so I assume it is not the average Beta status of many other libraries.

----

#### Edit 1

I'm aware of [this warning](https://docs.microsoft.com/en-us/graph/whats-new-overview):

> Features, including APIs and tools, in preview status may change without notice, and some may never be promoted to generally available (GA) status. Do not use preview features in production apps.

Unfortunately, the only other option I see now would be to start an external PowerShell script from my planned web application and use PowerShell scripts to perform the things that are not yet available in the v1.0 API.

I am not sure how this workaround approach (more complex, slower) compares to the risk of using the Beta API where things _may_ change or _may_ be unreliable.

**Comment by darrelmiller** [comment]
The Beta API is not recommended for production use.  The beta API is continually being updated with new features for preview.  They features in the beta API are migrated to V1 when they are considered stable.
